// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../../Http.res.mjs";
import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Market__Raw from "./Market__Raw.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function optionalQuery(query, key, value) {
  Stdlib_Option.forEach(value, value => {
    query.push([
      key,
      value
    ]);
  });
}

async function get(client, cursor, limit) {
  let query = [];
  optionalQuery(query, "cursor", Stdlib_Option.map(cursor, value => value.toString()));
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return Stdlib_Result.map(await Http.get(client.http, "/api/markets", query, undefined, undefined, Market__Raw.MarketsResponse.t_decode), response => {
    let markets = [];
    let validationErrors = [];
    response.markets.forEach(marketResponse => {
      let market = Market__Raw.MarketResponse.toMarket(marketResponse);
      if (market.TAG === "Ok") {
        let market$1 = market._0;
        let match = market$1.status;
        switch (match) {
          case "Active" :
          case "Resolved" :
            markets.push(market$1);
            return;
          case "Pending" :
          case "Cancelled" :
            return;
        }
      } else {
        validationErrors.push(market._0);
        return;
      }
    });
    return {
      markets: markets,
      validationErrors: validationErrors
    };
  });
}

async function featured(client) {
  return Stdlib_Result.map(await Http.get(client.http, "/api/markets/search/featured", undefined, undefined, undefined, json => Spice.arrayFromJson(Market__Raw.MarketSearchResult.t_decode, json)), results => results.filter(result => {
    let match = result.marketStatus;
    return match === "Active";
  }));
}

async function getBySlug(client, slug) {
  let error = await Http.get(client.http, `/api/markets/by-slug/` + slug, undefined, undefined, undefined, Market__Raw.SingleMarketResponse.t_decode);
  if (error.TAG === "Ok") {
    return Stdlib_Result.mapError(Market__Raw.MarketResponse.toMarket(error._0.market), message => ({
      TAG: "Validation",
      _0: message
    }));
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function getByPubkey(client, pubkey) {
  let error = await Http.get(client.http, `/api/markets/` + pubkey, undefined, undefined, undefined, Market__Raw.SingleMarketResponse.t_decode);
  if (error.TAG === "Ok") {
    return Stdlib_Result.mapError(Market__Raw.MarketResponse.toMarket(error._0.market), message => ({
      TAG: "Validation",
      _0: message
    }));
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function search(client, query, limit) {
  let encoded = encodeURIComponent(query);
  let queryParams = [];
  optionalQuery(queryParams, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return await Http.get(client.http, `/api/markets/search/by-query/` + encoded, queryParams, undefined, undefined, json => Spice.arrayFromJson(Market__Raw.MarketSearchResult.t_decode, json));
}

async function globalDepositAssets(client) {
  return Stdlib_Result.map(await Http.get(client.http, "/api/global-deposit-assets", undefined, undefined, undefined, Market__Raw.GlobalDepositAssetsListResponse.t_decode), response => {
    let assets = [];
    let validationErrors = [];
    response.assets.forEach(assetResponse => {
      let asset = Market__Raw.GlobalDepositAssetResponse.toGlobalDepositAsset(assetResponse);
      if (asset.TAG === "Ok") {
        assets.push(asset._0);
        return;
      }
      validationErrors.push(asset._0);
    });
    return {
      assets: assets,
      validationErrors: validationErrors
    };
  });
}

async function getDepositMints(client, marketPubkey) {
  return await Http.get(client.http, `/api/markets/` + marketPubkey + `/deposit-assets`, undefined, undefined, undefined, Market__Raw.DepositMintsResponse.t_decode);
}

export {
  get,
  featured,
  getBySlug,
  getByPubkey,
  search,
  globalDepositAssets,
  getDepositMints,
}
/* Http Not a pure module */
