// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import DecimalJs from "decimal.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Stdlib_Ordering from "@rescript/runtime/lib/es6/Stdlib_Ordering.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function t_encode(v) {
  switch (v) {
    case "Pending" :
      return "Pending";
    case "Active" :
      return "Active";
    case "Resolved" :
      return "Resolved";
    case "Cancelled" :
      return "Cancelled";
  }
}

function t_encodeJson(v) {
  switch (v) {
    case "Pending" :
      return "Pending";
    case "Active" :
      return "Active";
    case "Resolved" :
      return "Resolved";
    case "Cancelled" :
      return "Cancelled";
  }
}

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("Pending" === v) {
        return {
          TAG: "Ok",
          _0: "Pending"
        };
      } else if ("Active" === v) {
        return {
          TAG: "Ok",
          _0: "Active"
        };
      } else if ("Resolved" === v) {
        return {
          TAG: "Ok",
          _0: "Resolved"
        };
      } else if ("Cancelled" === v) {
        return {
          TAG: "Ok",
          _0: "Cancelled"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function toString(status) {
  switch (status) {
    case "Pending" :
      return "Pending";
    case "Active" :
      return "Active";
    case "Resolved" :
      return "Resolved";
    case "Cancelled" :
      return "Cancelled";
  }
}

function fromString(value) {
  switch (value) {
    case "Active" :
      return "Active";
    case "Cancelled" :
      return "Cancelled";
    case "Pending" :
      return "Pending";
    case "Resolved" :
      return "Resolved";
    default:
      return;
  }
}

let Status = {
  t_encode: t_encode,
  t_encodeJson: t_encodeJson,
  t_decode: t_decode,
  toString: toString,
  fromString: fromString
};

function t_encode$1(v) {
  if (v === "single_winner") {
    return "single_winner";
  } else {
    return "scalar";
  }
}

function t_encodeJson$1(v) {
  if (v === "single_winner") {
    return "single_winner";
  } else {
    return "scalar";
  }
}

function t_decode$1(v) {
  switch (typeof v) {
    case "string" :
      if ("single_winner" === v) {
        return {
          TAG: "Ok",
          _0: "single_winner"
        };
      } else if ("scalar" === v) {
        return {
          TAG: "Ok",
          _0: "scalar"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let Kind = {
  t_encode: t_encode$1,
  t_encodeJson: t_encodeJson$1,
  t_decode: t_decode$1
};

function payout_encode(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "outcome_index",
      Spice.floatToJson(v.outcomeIndex)
    ],
    [
      "payout_numerator",
      Spice.floatToJson(v.payoutNumerator)
    ]
  ]));
}

function payout_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "outcome_index",
      Spice.floatToJson(v.outcomeIndex)
    ],
    [
      "payout_numerator",
      Spice.floatToJson(v.payoutNumerator)
    ]
  ]));
}

function payout_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let outcomeIndex = Stdlib_Option.getOr(Stdlib_Option.map(v["outcome_index"], Spice.floatFromJson), Spice.error(undefined, "outcome_index" + " missing", v));
  if (outcomeIndex.TAG === "Ok") {
    let payoutNumerator = Stdlib_Option.getOr(Stdlib_Option.map(v["payout_numerator"], Spice.floatFromJson), Spice.error(undefined, "payout_numerator" + " missing", v));
    if (payoutNumerator.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          outcomeIndex: outcomeIndex._0,
          payoutNumerator: payoutNumerator._0
        }
      };
    }
    let e = payoutNumerator._0;
    return Spice.error("." + ("payout_numerator" + e.path), e.message, e.value);
  }
  let e$1 = outcomeIndex._0;
  return Spice.error("." + ("outcome_index" + e$1.path), e$1.message, e$1.value);
}

function t_encode$2(v) {
  let extra = v.singleWinningOutcome;
  return Object.fromEntries(Spice.filterOptional([
    [
      "kind",
      t_encodeJson$1(v.kind)
    ],
    [
      "payout_denominator",
      Spice.floatToJson(v.payoutDenominator)
    ],
    [
      "payouts",
      Spice.arrayToJson(payout_encodeJson, v.payouts)
    ],
    [
      "single_winning_outcome",
      Spice.optionToJson(Spice.floatToJson, extra)
    ]
  ]));
}

function t_encodeJson$2(v) {
  let extra = v.singleWinningOutcome;
  return Object.fromEntries(Spice.filterOptional([
    [
      "kind",
      t_encodeJson$1(v.kind)
    ],
    [
      "payout_denominator",
      Spice.floatToJson(v.payoutDenominator)
    ],
    [
      "payouts",
      Spice.arrayToJson(payout_encodeJson, v.payouts)
    ],
    [
      "single_winning_outcome",
      Spice.optionToJson(Spice.floatToJson, extra)
    ]
  ]));
}

function t_decode$2(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let kind = Stdlib_Option.getOr(Stdlib_Option.map(v["kind"], t_decode$1), Spice.error(undefined, "kind" + " missing", v));
  if (kind.TAG === "Ok") {
    let payoutDenominator = Stdlib_Option.getOr(Stdlib_Option.map(v["payout_denominator"], Spice.floatFromJson), Spice.error(undefined, "payout_denominator" + " missing", v));
    if (payoutDenominator.TAG === "Ok") {
      let payouts = Stdlib_Option.getOr(Stdlib_Option.map(v["payouts"], extra => Spice.arrayFromJson(payout_decode, extra)), Spice.error(undefined, "payouts" + " missing", v));
      if (payouts.TAG === "Ok") {
        let singleWinningOutcome = Stdlib_Option.getOr(Stdlib_Option.map(v["single_winning_outcome"], json => Stdlib_Result.map(Spice.floatFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (singleWinningOutcome.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              kind: kind._0,
              payoutDenominator: payoutDenominator._0,
              payouts: payouts._0,
              singleWinningOutcome: singleWinningOutcome._0
            }
          };
        }
        let e = singleWinningOutcome._0;
        return Spice.error("." + ("single_winning_outcome" + e.path), e.message, e.value);
      }
      let e$1 = payouts._0;
      return Spice.error("." + ("payouts" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = payoutDenominator._0;
    return Spice.error("." + ("payout_denominator" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = kind._0;
  return Spice.error("." + ("kind" + e$3.path), e$3.message, e$3.value);
}

let Resolution = {
  Kind: Kind,
  payout_encode: payout_encode,
  payout_encodeJson: payout_encodeJson,
  payout_decode: payout_decode,
  t_encode: t_encode$2,
  t_encodeJson: t_encodeJson$2,
  t_decode: t_decode$2
};

let usdcMainnet = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";

let usdtMainnet = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";

let usdcDevnetLc = "7SrxsoXjNR7Y8T3koJCt1yV4FrNUumoAUrJExDt6tQez";

function isUsdStablecoin(pubkey) {
  if (pubkey === usdcMainnet || pubkey === usdtMainnet) {
    return true;
  } else {
    return pubkey === usdcDevnetLc;
  }
}

function currencySymbol(pubkey) {
  if (isUsdStablecoin(pubkey)) {
    return "$";
  } else {
    return "";
  }
}

function displayPriority(symbol) {
  let match = symbol.toUpperCase();
  switch (match) {
    case "SOL" :
      return 2;
    case "BTC" :
    case "WBTC" :
      return 0;
    case "ETH" :
    case "WETH" :
      return 1;
    default:
      return 255;
  }
}

function sortByDisplayPriority(items, symbolOf) {
  return items.toSorted((left, right) => {
    let leftSymbol = symbolOf(left);
    let rightSymbol = symbolOf(right);
    let byPriority = Primitive_int.compare(displayPriority(leftSymbol), displayPriority(rightSymbol));
    if (Stdlib_Ordering.isEqual(byPriority)) {
      return Primitive_string.compare(leftSymbol, rightSymbol);
    } else {
      return byPriority;
    }
  });
}

function resolveIconUrls(low, medium, high) {
  let fallback = Stdlib_Option.orElse(Stdlib_Option.orElse(low, medium), high);
  if (fallback !== undefined) {
    return [
      Stdlib_Option.getOr(Stdlib_Option.orElse(Stdlib_Option.orElse(low, medium), high), fallback),
      Stdlib_Option.getOr(Stdlib_Option.orElse(Stdlib_Option.orElse(medium, low), high), fallback),
      Stdlib_Option.getOr(Stdlib_Option.orElse(Stdlib_Option.orElse(high, medium), low), fallback)
    ];
  }
}

let Outcome = {};

function isUsdStableCoin(token) {
  return isUsdStablecoin(token.depositAsset);
}

function currencySymbol$1(token) {
  return currencySymbol(token.mint);
}

let ConditionalToken = {
  isUsdStableCoin: isUsdStableCoin,
  currencySymbol: currencySymbol$1
};

function isUsdStableCoin$1(asset) {
  return isUsdStablecoin(asset.depositAsset);
}

function currencySymbol$2(asset) {
  return currencySymbol(asset.depositAsset);
}

let DepositAsset = {
  isUsdStableCoin: isUsdStableCoin$1,
  currencySymbol: currencySymbol$2
};

let TokenMetadata = {};

let DepositAssetPair = {};

function isUsdStableCoin$2(asset) {
  return isUsdStablecoin(asset.depositAsset);
}

function currencySymbol$3(asset) {
  return currencySymbol(asset.depositAsset);
}

let GlobalDepositAsset = {
  isUsdStableCoin: isUsdStableCoin$2,
  currencySymbol: currencySymbol$3
};

function decimals(pair) {
  let baseDecimals = pair.base.decimals | 0;
  let quoteDecimals = pair.quote.decimals | 0;
  return {
    baseDecimals: baseDecimals,
    quoteDecimals: quoteDecimals,
    priceDecimals: Primitive_int.max((6 + quoteDecimals | 0) - baseDecimals | 0, 0),
    tickSize: Math.max(pair.tickSize, 0.0)
  };
}

function denominatorToken(denominator, pair) {
  if (denominator === "Base") {
    return pair.base;
  } else {
    return pair.quote;
  }
}

function denominatorSymbol(denominator, pair) {
  return denominatorToken(denominator, pair).symbol;
}

function denominatorDepositSymbol(denominator, pair) {
  return denominatorToken(denominator, pair).depositSymbol;
}

let OrderBookPair = {
  decimals: decimals,
  denominatorToken: denominatorToken,
  denominatorSymbol: denominatorSymbol,
  denominatorDepositSymbol: denominatorDepositSymbol
};

let zero = {
  sign: "",
  pct: 0.0,
  dollar: "0",
  isPositive: false
};

function parseDecimalOpt(value) {
  let decimal;
  try {
    decimal = new DecimalJs(value);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return;
    }
    throw exn;
  }
  return Primitive_option.some(decimal);
}

function pct(depositPrice, conditionalPrice) {
  let match = parseDecimalOpt(depositPrice);
  let match$1 = parseDecimalOpt(conditionalPrice);
  if (match === undefined) {
    return [
      0.0,
      ""
    ];
  }
  if (match$1 === undefined) {
    return [
      0.0,
      ""
    ];
  }
  let conditional = Primitive_option.valFromOption(match$1);
  let deposit = Primitive_option.valFromOption(match);
  if (deposit.isZero() || conditional.isZero()) {
    return [
      0.0,
      ""
    ];
  }
  let value = conditional.minus(deposit).div(deposit).times(new DecimalJs(100)).toNumber();
  return [
    value,
    value > 0.0 ? "+" : ""
  ];
}

function make(depositAssetPrice, conditionalPrice) {
  let match = parseDecimalOpt(depositAssetPrice);
  let match$1 = parseDecimalOpt(conditionalPrice);
  if (match === undefined) {
    return zero;
  }
  if (match$1 === undefined) {
    return zero;
  }
  let deposit = Primitive_option.valFromOption(match);
  if (deposit.isZero()) {
    return zero;
  }
  let conditional = Primitive_option.valFromOption(match$1);
  let pct = conditional.minus(deposit).div(deposit).times(new DecimalJs(100)).toNumber();
  return {
    sign: pct > 0.0 ? "+" : "-",
    pct: Math.abs(pct),
    dollar: conditional.minus(deposit).abs().toString(),
    isPositive: pct > 0.0
  };
}

function isResolved(market) {
  return Stdlib_Option.isSome(market.resolution);
}

function singleWinningOutcome(market) {
  return Stdlib_Option.flatMap(market.resolution, resolution => resolution.singleWinningOutcome);
}

function hasSingleWinningOutcome(market) {
  return Stdlib_Option.isSome(singleWinningOutcome(market));
}

let MarketsResult = {};

let GlobalDepositAssetsResult = {};

let Impact = {
  zero: zero,
  pct: pct,
  make: make
};

export {
  Status,
  Resolution,
  usdcMainnet,
  usdtMainnet,
  usdcDevnetLc,
  isUsdStablecoin,
  currencySymbol,
  sortByDisplayPriority,
  resolveIconUrls,
  Outcome,
  ConditionalToken,
  DepositAsset,
  TokenMetadata,
  DepositAssetPair,
  GlobalDepositAsset,
  OrderBookPair,
  Impact,
  isResolved,
  singleWinningOutcome,
  hasSingleWinningOutcome,
  MarketsResult,
  GlobalDepositAssetsResult,
}
/* decimal.js Not a pure module */
