// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";

Buntest.describe("WebCrypto", () => {
  Buntest.test("randomUUID returns a 36-char UUID string", () => {
    Buntest.expect(crypto.randomUUID().length).toBe(36);
  });
  Buntest.test("two randomUUIDs differ", () => {
    Buntest.expect(crypto.randomUUID() === crypto.randomUUID()).toBe(false);
  });
});

/*  Not a pure module */
