"""On-chain program interaction module for Lightcone.

This module provides the client and utilities for interacting with
the Lightcone smart contract on Solana.
"""

# Types
# Constants
from ..env import PROGRAM_ID

# Account deserialization
from .accounts import (
    deserialize_exchange,
    deserialize_global_deposit_token,
    deserialize_market,
    deserialize_order_status,
    deserialize_orderbook,
    deserialize_position,
    deserialize_user_nonce,
    is_exchange_account,
    is_global_deposit_token,
    is_market_account,
    is_order_status_account,
    is_orderbook_account,
    is_position_account,
    is_user_nonce_account,
)

# Order builder
from .builder import OrderBuilder
from .constants import (
    ASSOCIATED_TOKEN_PROGRAM_ID,
    COMPACT_ORDER_SIZE,
    FULL_ORDER_SIZE,
    GLOBAL_DEPOSIT_TOKEN_DISCRIMINATOR,
    GLOBAL_DEPOSIT_TOKEN_SIZE,
    INITIALIZE_AUTHORITY,
    INSTRUCTION_ACCEPT_AUTHORITY,
    INSTRUCTION_ACCEPT_MANAGER,
    INSTRUCTION_ACCEPT_OPERATOR,
    INSTRUCTION_CLOSE_ORDER_STATUS,
    INSTRUCTION_CLOSE_ORDERBOOK,
    INSTRUCTION_CLOSE_POSITION_TOKEN_ACCOUNTS,
    INSTRUCTION_CREATE_CONDITIONAL_METADATA,
    INSTRUCTION_CREATE_ORDERBOOK,
    INSTRUCTION_DEPOSIT_AND_SWAP,
    INSTRUCTION_DEPOSIT_TO_GLOBAL,
    INSTRUCTION_EVENT_BATCH,
    INSTRUCTION_GLOBAL_TO_MARKET_DEPOSIT,
    INSTRUCTION_INIT_POSITION_TOKENS,
    INSTRUCTION_SET_AUTHORITY,
    INSTRUCTION_SET_DEPOSIT_TOKEN_STATUS,
    INSTRUCTION_SET_FEE_RECEIVER,
    INSTRUCTION_SET_MANAGER,
    INSTRUCTION_SET_MARKET_FEES,
    INSTRUCTION_SET_ORACLE,
    INSTRUCTION_UPDATE_CONDITIONAL_METADATA,
    INSTRUCTION_WHITELIST_DEPOSIT_TOKEN,
    INSTRUCTION_WITHDRAW_CONDITIONAL_FROM_POSITION,
    INSTRUCTION_WITHDRAW_FROM_GLOBAL,
    INSTRUCTION_WITHDRAW_FROM_POSITION,
    INSTRUCTIONS_SYSVAR_ID,
    MAX_DEPOSIT_MINTS_PER_IX,
    MAX_DEPOSIT_MINTS_PER_MARKET,
    MAX_MAKERS,
    MAX_OUTCOMES,
    MIN_OUTCOMES,
    MPL_TOKEN_METADATA_PROGRAM_ID,
    ORDER_HASH_SIZE,
    ORDER_SIZE,
    ORDERBOOK_DISCRIMINATOR,
    ORDERBOOK_SEED,
    ORDERBOOK_SIZE,
    PARTICIPANT_MASK_LEN,
    RENT_SYSVAR_ID,
    SEED_CONDITION,
    SEED_EVENT_AUTHORITY,
    SEED_FEE_RECEIVER,
    SEED_GLOBAL_DEPOSIT,
    SEED_MPL_METADATA,
    SIGNATURE_SIZE,
    SIGNED_ORDER_SIZE,
    SYSTEM_PROGRAM_ID,
    TAKER_MASK,
    TOKEN_PROGRAM_ID,
)
from .constants import (
    EXCHANGE_DISCRIMINATOR as EXCHANGE_DISCRIMINATOR,
)
from .constants import (
    EXCHANGE_SIZE as EXCHANGE_SIZE,
)
from .constants import (
    MARKET_DISCRIMINATOR as MARKET_DISCRIMINATOR,
)
from .constants import (
    MARKET_SIZE as MARKET_SIZE,
)
from .constants import (
    NO_WINNING_OUTCOME as NO_WINNING_OUTCOME,
)
from .constants import (
    ORDER_STATUS_DISCRIMINATOR as ORDER_STATUS_DISCRIMINATOR,
)
from .constants import (
    ORDER_STATUS_SIZE as ORDER_STATUS_SIZE,
)
from .constants import (
    POSITION_DISCRIMINATOR as POSITION_DISCRIMINATOR,
)
from .constants import (
    POSITION_SIZE as POSITION_SIZE,
)
from .constants import (
    SEED_CENTRAL_STATE as SEED_CENTRAL_STATE,
)
from .constants import (
    SEED_CONDITIONAL_MINT as SEED_CONDITIONAL_MINT,
)
from .constants import (
    SEED_MARKET as SEED_MARKET,
)
from .constants import (
    SEED_MINT_AUTHORITY as SEED_MINT_AUTHORITY,
)
from .constants import (
    SEED_ORDER_STATUS as SEED_ORDER_STATUS,
)
from .constants import (
    SEED_POSITION as SEED_POSITION,
)
from .constants import (
    SEED_USER_NONCE as SEED_USER_NONCE,
)
from .constants import (
    SEED_VAULT as SEED_VAULT,
)
from .constants import (
    USER_NONCE_DISCRIMINATOR as USER_NONCE_DISCRIMINATOR,
)
from .constants import (
    USER_NONCE_SIZE as USER_NONCE_SIZE,
)

# Envelope builders
from .envelope import LimitOrderEnvelope, TriggerOrderEnvelope

# Errors
from .errors import (
    AccountNotFoundError,
    ArithmeticOverflowError,
    DepositMintMismatchError,
    DepositTokenNotActiveError,
    DivisionByZeroError,
    DuplicateScalarOutcomesError,
    EventBatchOverflowError,
    ExchangePausedError,
    FullFillRequiredError,
    InactiveDepositTokenError,
    InsufficientBalanceError,
    InsufficientGlobalDepositError,
    InvalidAccountDataError,
    InvalidAtaError,
    InvalidConditionalMintError,
    InvalidDataLengthError,
    InvalidDepositMintOrderError,
    InvalidDiscriminatorError,
    InvalidEventAuthorityError,
    InvalidEventBatchError,
    InvalidEventContractError,
    InvalidFeeRangeError,
    InvalidFeeReceiverError,
    InvalidFeeSumError,
    InvalidManagerError,
    InvalidMarketError,
    InvalidMarketStatusError,
    InvalidMintOrderError,
    InvalidOracleError,
    InvalidOrderbookError,
    InvalidOrderError,
    InvalidOutcomeCountError,
    InvalidOutcomeError,
    InvalidOutcomeIndexError,
    InvalidPayoutNumeratorsError,
    InvalidPendingRoleKindError,
    InvalidProgramIdError,
    InvalidPubkeyError,
    InvalidScalarRangeError,
    InvalidSideError,
    InvalidSignatureError,
    LightconeError,
    MarketNotActiveError,
    MarketSettledError,
    MissingFieldError,
    NoPendingRoleTransferError,
    OrderbookExistsError,
    OrderExpiredError,
    OrderNotFullyFilledError,
    OrdersDoNotCrossError,
    PayoutTooSmallError,
    PayoutVectorExceedsU32Error,
    PendingRoleMismatchError,
    PublicInstructionMustBeTopLevelError,
    Reserved50Error,
    ScalingError,
    SerializationError,
    SignatureVerificationFailedError,
    TokenAccountNotEmptyError,
    TooManyDepositMintsError,
    TooManyMakersError,
    UnsignedOrderError,
    UnsupportedEventSchemaError,
    ZeroAmountError,
)

# Instruction builders
from .instructions import (
    build_accept_authority_instruction,
    build_accept_manager_instruction,
    build_accept_operator_instruction,
    build_activate_market_instruction,
    build_add_deposit_mint_instruction,
    build_cancel_order_instruction,
    build_close_order_status_instruction,
    build_close_orderbook_instruction,
    build_close_position_token_accounts_instruction,
    build_create_conditional_metadata_instruction,
    build_create_market_instruction,
    build_create_orderbook_instruction,
    build_deposit_and_swap_instruction,
    build_deposit_instruction,
    build_deposit_to_global_instruction,
    build_global_to_market_deposit_instruction,
    build_increment_nonce_instruction,
    build_init_position_tokens_instruction,
    build_initialize_instruction,
    build_match_orders_multi_instruction,
    build_merge_complete_set_instruction,
    build_merge_instruction,
    build_mint_complete_set_instruction,
    build_redeem_winnings_instruction,
    build_set_authority_instruction,
    build_set_deposit_token_status_instruction,
    build_set_fee_receiver_instruction,
    build_set_fee_receiver_with_atas_instruction,
    build_set_manager_instruction,
    build_set_market_fees_instruction,
    build_set_operator_instruction,
    build_set_oracle_instruction,
    build_set_paused_instruction,
    build_settle_market_instruction,
    build_update_conditional_metadata_instruction,
    build_whitelist_deposit_token_instruction,
    build_withdraw_conditional_from_position_instruction,
    build_withdraw_from_global_instruction,
    build_withdraw_from_position_instruction,
)

# Order functions
from .orders import (
    apply_signature,
    calculate_taker_fill,
    cancel_all_message,
    cancel_order_message,
    cancel_trigger_order_message,
    create_ask_order,
    create_bid_order,
    create_signed_ask_order,
    create_signed_bid_order,
    derive_orderbook_id,
    deserialize_compact_order,
    deserialize_full_order,
    deserialize_order,
    generate_cancel_all_salt,
    generate_salt,
    hash_order,
    hash_order_hex,
    is_order_expired,
    is_signed,
    orders_can_cross,
    serialize_compact_order,
    serialize_full_order,
    serialize_order,
    sign_cancel_all,
    sign_cancel_order,
    sign_order,
    signature_hex,
    to_compact_order,
    to_order,
    to_submit_request,
    validate_order,
    validate_signed_order,
    verify_order_signature,
)

# PDA functions
from .pda import (
    canonical_mint_pair,
    get_all_conditional_mint_pdas,
    get_all_conditional_mints,
    get_condition_tombstone_pda,
    get_conditional_mint_pda,
    get_event_authority_pda,
    get_exchange_pda,
    get_global_deposit_pda,
    get_market_pda,
    get_mint_authority_pda,
    get_mpl_metadata_pda,
    get_order_status_pda,
    get_orderbook_pda,
    get_position_pda,
    get_user_global_deposit_pda,
    get_user_nonce_pda,
    get_vault_pda,
)
from .types import (
    AcceptRoleParams,
    ActivateMarketParams,
    AddDepositMintParams,
    AskOrderParams,
    BidOrderParams,
    BuildDepositParams,
    BuildMergeParams,
    BuildResult,
    CloseOrderbookParams,
    CloseOrderStatusParams,
    ClosePositionTokenAccountsParams,
    CompactOrder,
    ConditionalMetadataParams,
    CreateMarketParams,
    CreateOrderbookParams,
    DepositAndSwapParams,
    DepositToGlobalParams,
    Exchange,
    FullOrder,
    GlobalDepositToken,
    GlobalToMarketDepositParams,
    InitializeParams,
    InitPositionTokensParams,
    MakerFill,
    Market,
    MarketFeeUpdate,
    MarketStatus,
    MatchOrdersMultiParams,
    MergeCompleteSetParams,
    MintCompleteSetParams,
    Order,
    Orderbook,
    OrderSide,
    OrderStatus,
    PendingRoleKind,
    Position,
    RedeemWinningsParams,
    ScalarResolutionParams,
    SetAuthorityParams,
    SetDepositTokenStatusParams,
    SetFeeReceiverParams,
    SetFeeReceiverWithAtasParams,
    SetManagerParams,
    SetMarketFeesParams,
    SetOracleParams,
    SettleMarketParams,
    SignedOrder,
    UserNonce,
    WhitelistDepositTokenParams,
    WithdrawConditionalFromPositionParams,
    WithdrawFromGlobalParams,
    WithdrawFromPositionParams,
)

# Utils
from .utils import (
    decode_bool as decode_bool,
)
from .utils import (
    decode_i16 as decode_i16,
)
from .utils import (
    decode_i64 as decode_i64,
)
from .utils import (
    decode_pubkey as decode_pubkey,
)
from .utils import (
    decode_u8 as decode_u8,
)
from .utils import (
    decode_u16 as decode_u16,
)
from .utils import (
    decode_u32 as decode_u32,
)
from .utils import (
    decode_u64 as decode_u64,
)
from .utils import (
    derive_condition_id,
    get_associated_token_address,
    get_conditional_token_ata,
    keccak256,
    orders_cross,
    scalar_to_payout_numerators,
    winner_takes_all_payout_numerators,
)
from .utils import (
    encode_i16 as encode_i16,
)
from .utils import (
    encode_i64 as encode_i64,
)
from .utils import (
    encode_u8 as encode_u8,
)
from .utils import (
    encode_u16 as encode_u16,
)
from .utils import (
    encode_u32 as encode_u32,
)
from .utils import (
    encode_u64 as encode_u64,
)

__all__ = [
    # Types
    "MarketStatus",
    "OrderSide",
    "PendingRoleKind",
    "Exchange",
    "Market",
    "Position",
    "OrderStatus",
    "UserNonce",
    "Orderbook",
    "SignedOrder",
    "FullOrder",
    "Order",
    "CompactOrder",
    "GlobalDepositToken",
    "MakerFill",
    "InitializeParams",
    "CreateMarketParams",
    "AddDepositMintParams",
    "MintCompleteSetParams",
    "MergeCompleteSetParams",
    "BuildDepositParams",
    "BuildMergeParams",
    "SettleMarketParams",
    "ScalarResolutionParams",
    "RedeemWinningsParams",
    "WithdrawConditionalFromPositionParams",
    "WithdrawFromPositionParams",
    "ActivateMarketParams",
    "MatchOrdersMultiParams",
    "CreateOrderbookParams",
    "SetAuthorityParams",
    "SetManagerParams",
    "AcceptRoleParams",
    "SetOracleParams",
    "MarketFeeUpdate",
    "SetMarketFeesParams",
    "SetFeeReceiverParams",
    "SetFeeReceiverWithAtasParams",
    "ConditionalMetadataParams",
    "BidOrderParams",
    "AskOrderParams",
    "BuildResult",
    "WhitelistDepositTokenParams",
    "SetDepositTokenStatusParams",
    "DepositToGlobalParams",
    "GlobalToMarketDepositParams",
    "InitPositionTokensParams",
    "DepositAndSwapParams",
    "WithdrawFromGlobalParams",
    "CloseOrderStatusParams",
    "ClosePositionTokenAccountsParams",
    "CloseOrderbookParams",
    # Constants
    "PROGRAM_ID",
    "TOKEN_PROGRAM_ID",
    "ASSOCIATED_TOKEN_PROGRAM_ID",
    "SYSTEM_PROGRAM_ID",
    "RENT_SYSVAR_ID",
    "MPL_TOKEN_METADATA_PROGRAM_ID",
    "INITIALIZE_AUTHORITY",
    "INSTRUCTIONS_SYSVAR_ID",
    "ORDERBOOK_DISCRIMINATOR",
    "GLOBAL_DEPOSIT_TOKEN_DISCRIMINATOR",
    "ORDERBOOK_SEED",
    "SEED_CONDITION",
    "SEED_GLOBAL_DEPOSIT",
    "SEED_FEE_RECEIVER",
    "SEED_MPL_METADATA",
    "SEED_EVENT_AUTHORITY",
    "ORDERBOOK_SIZE",
    "GLOBAL_DEPOSIT_TOKEN_SIZE",
    "SIGNED_ORDER_SIZE",
    "ORDER_SIZE",
    "MAX_OUTCOMES",
    "MIN_OUTCOMES",
    "MAX_MAKERS",
    "TAKER_MASK",
    "PARTICIPANT_MASK_LEN",
    "MAX_DEPOSIT_MINTS_PER_MARKET",
    "MAX_DEPOSIT_MINTS_PER_IX",
    "FULL_ORDER_SIZE",
    "COMPACT_ORDER_SIZE",
    "SIGNATURE_SIZE",
    "ORDER_HASH_SIZE",
    "INSTRUCTION_SET_AUTHORITY",
    "INSTRUCTION_CREATE_ORDERBOOK",
    "INSTRUCTION_WHITELIST_DEPOSIT_TOKEN",
    "INSTRUCTION_DEPOSIT_TO_GLOBAL",
    "INSTRUCTION_GLOBAL_TO_MARKET_DEPOSIT",
    "INSTRUCTION_INIT_POSITION_TOKENS",
    "INSTRUCTION_DEPOSIT_AND_SWAP",
    "INSTRUCTION_WITHDRAW_CONDITIONAL_FROM_POSITION",
    "INSTRUCTION_WITHDRAW_FROM_POSITION",
    "INSTRUCTION_WITHDRAW_FROM_GLOBAL",
    "INSTRUCTION_CLOSE_ORDER_STATUS",
    "INSTRUCTION_CLOSE_POSITION_TOKEN_ACCOUNTS",
    "INSTRUCTION_CLOSE_ORDERBOOK",
    "INSTRUCTION_SET_MANAGER",
    "INSTRUCTION_SET_MARKET_FEES",
    "INSTRUCTION_SET_FEE_RECEIVER",
    "INSTRUCTION_CREATE_CONDITIONAL_METADATA",
    "INSTRUCTION_UPDATE_CONDITIONAL_METADATA",
    "INSTRUCTION_SET_ORACLE",
    "INSTRUCTION_ACCEPT_AUTHORITY",
    "INSTRUCTION_ACCEPT_MANAGER",
    "INSTRUCTION_ACCEPT_OPERATOR",
    "INSTRUCTION_SET_DEPOSIT_TOKEN_STATUS",
    "INSTRUCTION_EVENT_BATCH",
    # Errors
    "LightconeError",
    "InvalidDiscriminatorError",
    "AccountNotFoundError",
    "InvalidAccountDataError",
    "InvalidOrderError",
    "InvalidSignatureError",
    "OrderExpiredError",
    "InsufficientBalanceError",
    "MarketNotActiveError",
    "ExchangePausedError",
    "InvalidOutcomeError",
    "TooManyMakersError",
    "InactiveDepositTokenError",
    "InvalidConditionalMintError",
    "DepositMintMismatchError",
    "OrdersDoNotCrossError",
    "InvalidDataLengthError",
    "InvalidOutcomeCountError",
    "InvalidOutcomeIndexError",
    "SignatureVerificationFailedError",
    "SerializationError",
    "InvalidSideError",
    "InvalidMarketStatusError",
    "InvalidPendingRoleKindError",
    "MissingFieldError",
    "ArithmeticOverflowError",
    "InvalidPayoutNumeratorsError",
    "PayoutVectorExceedsU32Error",
    "InvalidScalarRangeError",
    "DuplicateScalarOutcomesError",
    "InvalidMintOrderError",
    "OrderbookExistsError",
    "InvalidMarketError",
    "MarketSettledError",
    "InvalidProgramIdError",
    "InvalidManagerError",
    "InvalidFeeRangeError",
    "InvalidFeeSumError",
    "InvalidFeeReceiverError",
    "InvalidOracleError",
    "NoPendingRoleTransferError",
    "PendingRoleMismatchError",
    "InvalidEventAuthorityError",
    "EventBatchOverflowError",
    "InvalidEventBatchError",
    "InvalidEventContractError",
    "UnsupportedEventSchemaError",
    "PublicInstructionMustBeTopLevelError",
    "TooManyDepositMintsError",
    "InvalidOrderbookError",
    "FullFillRequiredError",
    "DivisionByZeroError",
    "Reserved50Error",
    "DepositTokenNotActiveError",
    "InsufficientGlobalDepositError",
    "InvalidDepositMintOrderError",
    "ZeroAmountError",
    "InvalidAtaError",
    "OrderNotFullyFilledError",
    "PayoutTooSmallError",
    "TokenAccountNotEmptyError",
    "InvalidPubkeyError",
    "ScalingError",
    "UnsignedOrderError",
    # Utils
    "keccak256",
    "derive_condition_id",
    "get_associated_token_address",
    "get_conditional_token_ata",
    "orders_cross",
    "winner_takes_all_payout_numerators",
    "scalar_to_payout_numerators",
    # Account Deserialization
    "deserialize_exchange",
    "deserialize_global_deposit_token",
    "deserialize_market",
    "deserialize_position",
    "deserialize_order_status",
    "deserialize_orderbook",
    "deserialize_user_nonce",
    "is_exchange_account",
    "is_global_deposit_token",
    "is_market_account",
    "is_order_status_account",
    "is_orderbook_account",
    "is_position_account",
    "is_user_nonce_account",
    # PDA Functions
    "get_exchange_pda",
    "get_event_authority_pda",
    "get_condition_tombstone_pda",
    "get_global_deposit_pda",
    "get_market_pda",
    "get_vault_pda",
    "get_mint_authority_pda",
    "get_conditional_mint_pda",
    "get_mpl_metadata_pda",
    "get_order_status_pda",
    "get_user_nonce_pda",
    "get_position_pda",
    "get_orderbook_pda",
    "canonical_mint_pair",
    "get_all_conditional_mint_pdas",
    "get_all_conditional_mints",
    "get_user_global_deposit_pda",
    # Order Functions
    "calculate_taker_fill",
    "cancel_all_message",
    "cancel_order_message",
    "cancel_trigger_order_message",
    "create_bid_order",
    "create_ask_order",
    "create_signed_bid_order",
    "create_signed_ask_order",
    "generate_cancel_all_salt",
    "generate_salt",
    "hash_order",
    "hash_order_hex",
    "sign_cancel_all",
    "sign_cancel_order",
    "sign_order",
    "verify_order_signature",
    "serialize_full_order",
    "deserialize_full_order",
    "serialize_order",
    "serialize_compact_order",
    "deserialize_order",
    "deserialize_compact_order",
    "to_order",
    "to_compact_order",
    "to_submit_request",
    "is_order_expired",
    "orders_can_cross",
    "apply_signature",
    "derive_orderbook_id",
    "is_signed",
    "signature_hex",
    "validate_order",
    "validate_signed_order",
    # Instruction Builders
    "build_accept_authority_instruction",
    "build_accept_manager_instruction",
    "build_accept_operator_instruction",
    "build_initialize_instruction",
    "build_create_market_instruction",
    "build_add_deposit_mint_instruction",
    "build_mint_complete_set_instruction",
    "build_merge_complete_set_instruction",
    "build_deposit_instruction",
    "build_merge_instruction",
    "build_cancel_order_instruction",
    "build_increment_nonce_instruction",
    "build_settle_market_instruction",
    "build_redeem_winnings_instruction",
    "build_set_paused_instruction",
    "build_set_operator_instruction",
    "build_withdraw_conditional_from_position_instruction",
    "build_withdraw_from_position_instruction",
    "build_activate_market_instruction",
    "build_match_orders_multi_instruction",
    "build_create_orderbook_instruction",
    "build_set_authority_instruction",
    "build_set_manager_instruction",
    "build_set_oracle_instruction",
    "build_set_market_fees_instruction",
    "build_set_fee_receiver_instruction",
    "build_set_fee_receiver_with_atas_instruction",
    "build_create_conditional_metadata_instruction",
    "build_update_conditional_metadata_instruction",
    "build_whitelist_deposit_token_instruction",
    "build_set_deposit_token_status_instruction",
    "build_deposit_to_global_instruction",
    "build_global_to_market_deposit_instruction",
    "build_init_position_tokens_instruction",
    "build_deposit_and_swap_instruction",
    "build_close_order_status_instruction",
    "build_close_position_token_accounts_instruction",
    "build_close_orderbook_instruction",
    "build_withdraw_from_global_instruction",
    # Envelope Builders
    "LimitOrderEnvelope",
    "TriggerOrderEnvelope",
    # Order Builder
    "OrderBuilder",
]
