"""Constants for the Lightcone program module."""

from solders.pubkey import Pubkey
from solders.system_program import ID as _SYSTEM_PROGRAM_ID
from solders.sysvar import RENT as _RENT_SYSVAR, INSTRUCTIONS as _INSTRUCTIONS_SYSVAR
from spl.token.constants import (
    TOKEN_PROGRAM_ID as _TOKEN_PROGRAM_ID,
    TOKEN_2022_PROGRAM_ID as _TOKEN_2022_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID as _ASSOCIATED_TOKEN_PROGRAM_ID,
)


# Program IDs
PROGRAM_ID = Pubkey.from_string("8nzsoyHZFYig3uN3M717Q47MtLqzx2V2UAKaPTqDy5rV")
ALT_PROGRAM_ID = Pubkey.from_string("AddressLookupTab1e1111111111111111111111111")
TOKEN_PROGRAM_ID = _TOKEN_PROGRAM_ID
TOKEN_2022_PROGRAM_ID = _TOKEN_2022_PROGRAM_ID
ASSOCIATED_TOKEN_PROGRAM_ID = _ASSOCIATED_TOKEN_PROGRAM_ID
SYSTEM_PROGRAM_ID = _SYSTEM_PROGRAM_ID
RENT_SYSVAR_ID = _RENT_SYSVAR
INSTRUCTIONS_SYSVAR_ID = _INSTRUCTIONS_SYSVAR


# Account Discriminators (8 bytes each, SHA-256 hash prefixes)
EXCHANGE_DISCRIMINATOR = bytes([0x1E, 0xC8, 0xDC, 0x95, 0x03, 0x3D, 0x68, 0x32])
MARKET_DISCRIMINATOR = bytes([0xDB, 0xBE, 0xD5, 0x37, 0x00, 0xE3, 0xC6, 0x9A])
ORDER_STATUS_DISCRIMINATOR = bytes([0x2E, 0x5A, 0xF1, 0x49, 0xB2, 0x68, 0x41, 0x03])
USER_NONCE_DISCRIMINATOR = bytes([0xEB, 0x85, 0x01, 0xF3, 0x12, 0x87, 0x58, 0xE0])
POSITION_DISCRIMINATOR = bytes([0xAA, 0xBC, 0x8F, 0xE4, 0x7A, 0x40, 0xF7, 0xD0])
ORDERBOOK_DISCRIMINATOR = bytes([0x2B, 0x22, 0x19, 0x71, 0xC3, 0x45, 0x48, 0x07])
GLOBAL_DEPOSIT_TOKEN_DISCRIMINATOR = bytes([0x25, 0xBE, 0xA1, 0xE8, 0x7B, 0x92, 0x2A, 0x57])


# PDA Seeds
SEED_CENTRAL_STATE = b"central_state"
SEED_MARKET = b"market"
SEED_VAULT = b"market_deposit_token_account"
SEED_MINT_AUTHORITY = b"market_mint_authority"
SEED_CONDITIONAL_MINT = b"conditional_mint"
SEED_ORDER_STATUS = b"order_status"
SEED_USER_NONCE = b"user_nonce"
SEED_POSITION = b"position"
ORDERBOOK_SEED = b"orderbook"
SEED_ORDERBOOK = ORDERBOOK_SEED  # alias for SEED_* naming consistency
SEED_GLOBAL_DEPOSIT = b"global_deposit"


# Account Sizes (in bytes)
EXCHANGE_SIZE = 88
MARKET_SIZE = 120
ORDER_STATUS_SIZE = 24
USER_NONCE_SIZE = 16
POSITION_SIZE = 80
ORDERBOOK_SIZE = 144
GLOBAL_DEPOSIT_TOKEN_SIZE = 48


# Order Sizes (in bytes)
SIGNED_ORDER_SIZE = 233
ORDER_SIZE = 37
SIGNATURE_SIZE = 64
ORDER_HASH_SIZE = 32

# Order Layout Offsets (for OrderPayload)
ORDER_NONCE_OFFSET = 0
ORDER_SALT_OFFSET = 8
ORDER_MAKER_OFFSET = 16
ORDER_MARKET_OFFSET = 48
ORDER_BASE_MINT_OFFSET = 80
ORDER_QUOTE_MINT_OFFSET = 112
ORDER_SIDE_OFFSET = 144
ORDER_MAKER_AMOUNT_OFFSET = 145
ORDER_TAKER_AMOUNT_OFFSET = 153
ORDER_EXPIRATION_OFFSET = 161
ORDER_SIGNATURE_OFFSET = 169


# Instruction Discriminators
INSTRUCTION_INITIALIZE = 0
INSTRUCTION_CREATE_MARKET = 1
INSTRUCTION_ADD_DEPOSIT_MINT = 2
INSTRUCTION_MINT_COMPLETE_SET = 3
INSTRUCTION_MERGE_COMPLETE_SET = 4
INSTRUCTION_CANCEL_ORDER = 5
INSTRUCTION_INCREMENT_NONCE = 6
INSTRUCTION_SETTLE_MARKET = 7
INSTRUCTION_REDEEM_WINNINGS = 8
INSTRUCTION_SET_PAUSED = 9
INSTRUCTION_SET_OPERATOR = 10
INSTRUCTION_WITHDRAW_FROM_POSITION = 11
INSTRUCTION_ACTIVATE_MARKET = 12
INSTRUCTION_MATCH_ORDERS_MULTI = 13
INSTRUCTION_SET_AUTHORITY = 14
INSTRUCTION_CREATE_ORDERBOOK = 15
INSTRUCTION_WHITELIST_DEPOSIT_TOKEN = 16
INSTRUCTION_DEPOSIT_TO_GLOBAL = 17
INSTRUCTION_GLOBAL_TO_MARKET_DEPOSIT = 18
INSTRUCTION_INIT_POSITION_TOKENS = 19
INSTRUCTION_DEPOSIT_AND_SWAP = 20
INSTRUCTION_EXTEND_POSITION_TOKENS = 21
INSTRUCTION_WITHDRAW_FROM_GLOBAL = 22


# Limits
MAX_OUTCOMES = 6
MIN_OUTCOMES = 2
MAX_MAKERS = 5
MAX_OUTCOME_NAME_LEN = 32
MAX_OUTCOME_SYMBOL_LEN = 10
MAX_OUTCOME_URI_LEN = 200


# Special Values
NO_WINNING_OUTCOME = 255
