#!/usr/bin/env bash

# Check if any staged files are Rust files
staged_rust_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$')
if [ -n "$staged_rust_files" ]; then
    echo "Running cargo fmt..."
    cargo fmt --manifest-path rust/Cargo.toml
    echo "$staged_rust_files" | xargs git add
fi
