// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../../Http.res.mjs";
import * as Shared from "../../Shared.res.mjs";
import * as Metrics__Raw from "./Metrics__Raw.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function optionalQuery(query, key, value) {
  Stdlib_Option.forEach(value, value => {
    query.push([
      key,
      value
    ]);
  });
}

async function platform(client) {
  return await Http.get(client.http, "/api/metrics/platform", undefined, undefined, undefined, Metrics__Raw.Platform.t_decode);
}

async function markets(client) {
  return await Http.get(client.http, "/api/metrics/markets", undefined, undefined, undefined, Metrics__Raw.Markets.t_decode);
}

async function market(client, marketPubkey) {
  let path = `/api/metrics/markets/` + encodeURIComponent(marketPubkey);
  return await Http.get(client.http, path, undefined, undefined, undefined, Metrics__Raw.MarketDetail.t_decode);
}

async function orderbookTickers(client, depositAsset) {
  let query = [];
  let mint = Stdlib_Option.map(depositAsset, value => value.trim());
  if (mint !== undefined && mint !== "") {
    query.push([
      "deposit_asset",
      mint
    ]);
  }
  return await Http.get(client.http, "/api/metrics/orderbooks/tickers", query, undefined, undefined, Metrics__Raw.OrderbookTickersResponse.t_decode);
}

async function orderbook(client, orderbookId) {
  let path = `/api/metrics/orderbooks/` + encodeURIComponent(orderbookId);
  return await Http.get(client.http, path, undefined, undefined, undefined, Metrics__Raw.OrderbookVolume.t_decode);
}

async function categories(client) {
  return await Http.get(client.http, "/api/metrics/categories", undefined, undefined, undefined, Metrics__Raw.Categories.t_decode);
}

async function category(client, category$1) {
  let path = `/api/metrics/categories/` + encodeURIComponent(category$1);
  return await Http.get(client.http, path, undefined, undefined, undefined, Metrics__Raw.CategoryVolume.t_decode);
}

async function depositTokens(client) {
  return await Http.get(client.http, "/api/metrics/deposit-tokens", undefined, undefined, undefined, Metrics__Raw.DepositTokens.t_decode);
}

async function depositTokensVolumeHistory(client, fromMs, toMs, limit) {
  let query = [];
  optionalQuery(query, "from", Stdlib_Option.map(fromMs, value => value.toString()));
  optionalQuery(query, "to", Stdlib_Option.map(toMs, value => value.toString()));
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return await Http.get(client.http, "/api/metrics/deposit-tokens/volume-history", query, undefined, undefined, Metrics__Raw.DepositTokenVolumeHistory.t_decode);
}

async function openInterestHistory(client, fromMs, toMs, limit) {
  let query = [];
  optionalQuery(query, "from", Stdlib_Option.map(fromMs, value => value.toString()));
  optionalQuery(query, "to", Stdlib_Option.map(toMs, value => value.toString()));
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return await Http.get(client.http, "/api/metrics/open-interest/history", query, undefined, undefined, Metrics__Raw.OpenInterestHistory.t_decode);
}

async function uniqueTradersHistory(client, scope, scopeKey, fromMs, toMs, limit) {
  let query = [];
  optionalQuery(query, "scope", Stdlib_Option.map(scope, value => Metrics__Raw.UniqueTradersHistoryScope.toString(value)));
  optionalQuery(query, "scope_key", scopeKey);
  optionalQuery(query, "from", Stdlib_Option.map(fromMs, value => value.toString()));
  optionalQuery(query, "to", Stdlib_Option.map(toMs, value => value.toString()));
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return await Http.get(client.http, "/api/metrics/unique-traders/history", query, undefined, undefined, Metrics__Raw.UniqueTradersHistory.t_decode);
}

async function leaderboard(client, limit) {
  let query = [];
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return await Http.get(client.http, "/api/metrics/leaderboard/markets", query, undefined, undefined, Metrics__Raw.Leaderboard.t_decode);
}

async function history(client, scope, scopeKey, resolutionOpt, fromMs, toMs, limit) {
  let resolution = resolutionOpt !== undefined ? resolutionOpt : "1h";
  let path = `/api/metrics/history/` + encodeURIComponent(scope) + `/` + encodeURIComponent(scopeKey);
  let query = [[
      "resolution",
      Shared.Resolution.toString(resolution)
    ]];
  optionalQuery(query, "from", Stdlib_Option.map(fromMs, value => value.toString()));
  optionalQuery(query, "to", Stdlib_Option.map(toMs, value => value.toString()));
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  return await Http.get(client.http, path, query, undefined, undefined, Metrics__Raw.History.t_decode);
}

async function user(client, cookieHeader) {
  return await Http.get(client.http, "/api/metrics/user", undefined, undefined, cookieHeader, Metrics__Raw.User.t_decode);
}

async function userByWallet(client, walletAddress) {
  let path = `/api/metrics/user/` + encodeURIComponent(walletAddress);
  return await Http.get(client.http, path, undefined, undefined, undefined, Metrics__Raw.User.t_decode);
}

export {
  platform,
  markets,
  market,
  orderbookTickers,
  orderbook,
  categories,
  category,
  depositTokens,
  depositTokensVolumeHistory,
  openInterestHistory,
  uniqueTradersHistory,
  leaderboard,
  history,
  user,
  userByWallet,
}
/* Http Not a pure module */
