// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sha3Js from "@noble/hashes/sha3.js";

let utf8 = ((text) => new TextEncoder().encode(text));

let toHex = ((bytes) => Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join(""));

function _quickStart() {
  let digest = Sha3Js.keccak_256(utf8("abc"));
  toHex(digest);
}

function _keccak(bytes) {
  return Sha3Js.keccak_256(bytes);
}

export {
  utf8,
  toHex,
  _quickStart,
  _keccak,
}
/* @noble/hashes/sha3.js Not a pure module */
