// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Order__Raw from "./Order__Raw.res.mjs";
import DecimalJs from "decimal.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function decimalOrZero(value) {
  try {
    return new DecimalJs(value);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return new DecimalJs(0);
    }
    throw exn;
  }
}

function make() {
  return {
    orders: {}
  };
}

function byMarketOrCreate(state, marketPubkey) {
  let byOrderbook = state.orders[marketPubkey];
  if (byOrderbook !== undefined) {
    return byOrderbook;
  }
  let byOrderbook$1 = {};
  state.orders[marketPubkey] = byOrderbook$1;
  return byOrderbook$1;
}

function get(state, marketPubkey, orderbookId) {
  return Stdlib_Option.flatMap(state.orders[marketPubkey], byOrderbook => byOrderbook[orderbookId]);
}

function getByMarket(state, marketPubkey) {
  return state.orders[marketPubkey];
}

function insert(state, order) {
  let byOrderbook = byMarketOrCreate(state, order.marketPubkey);
  let orders = Stdlib_Option.getOr(byOrderbook[order.orderbookId], []);
  orders.push(order);
  byOrderbook[order.orderbookId] = orders;
}

function upsert(state, update) {
  let byOrderbook = byMarketOrCreate(state, update.marketPubkey);
  let orders = Stdlib_Option.getOr(byOrderbook[update.orderbookId], []).filter(order => order.orderHash !== update.order.orderHash);
  orders.push(Order__Raw.Update.toLimit(update));
  byOrderbook[update.orderbookId] = orders;
}

function remove(state, orderHash) {
  Object.values(state.orders).forEach(byOrderbook => {
    Object.entries(byOrderbook).forEach(param => {
      byOrderbook[param[0]] = param[1].filter(order => order.orderHash !== orderHash);
    });
  });
}

function clear(state) {
  state.orders = {};
}

function isEmpty(state) {
  return Object.values(state.orders).every(byOrderbook => Object.values(byOrderbook).every(orders => orders.length === 0));
}

function make$1() {
  return {
    orders: {}
  };
}

function get$1(state, marketPubkey, orderbookId) {
  return Stdlib_Option.flatMap(state.orders[marketPubkey], byOrderbook => byOrderbook[orderbookId]);
}

function getByMarket$1(state, marketPubkey) {
  return state.orders[marketPubkey];
}

function all(state) {
  return Object.values(state.orders).flatMap(byOrderbook => Object.values(byOrderbook).flat());
}

function getById(state, triggerOrderId) {
  return all(state).find(order => order.triggerOrderId === triggerOrderId);
}

function insert$1(state, order) {
  let byOrderbook = state.orders[order.marketPubkey];
  let byOrderbook$1;
  if (byOrderbook !== undefined) {
    byOrderbook$1 = byOrderbook;
  } else {
    let byOrderbook$2 = {};
    state.orders[order.marketPubkey] = byOrderbook$2;
    byOrderbook$1 = byOrderbook$2;
  }
  let orders = Stdlib_Option.getOr(byOrderbook$1[order.orderbookId], []);
  orders.push(order);
  byOrderbook$1[order.orderbookId] = orders;
}

function remove$1(state, triggerOrderId) {
  let removed = {
    contents: undefined
  };
  Object.values(state.orders).forEach(byOrderbook => {
    Object.entries(byOrderbook).forEach(param => {
      let orders = param[1];
      if (!Stdlib_Option.isNone(removed.contents)) {
        return;
      }
      let order = orders.find(order => order.triggerOrderId === triggerOrderId);
      if (order !== undefined) {
        removed.contents = order;
        byOrderbook[param[0]] = orders.filter(order => order.triggerOrderId !== triggerOrderId);
        return;
      }
    });
  });
  return removed.contents;
}

function clear$1(state) {
  state.orders = {};
}

function isEmpty$1(state) {
  return Object.values(state.orders).every(byOrderbook => Object.values(byOrderbook).every(orders => orders.length === 0));
}

function size(state) {
  return all(state).length;
}

let Triggers = {
  make: make$1,
  get: get$1,
  getByMarket: getByMarket$1,
  all: all,
  getById: getById,
  insert: insert$1,
  remove: remove$1,
  clear: clear$1,
  isEmpty: isEmpty$1,
  size: size
};

function fromSnapshotOrders(orders) {
  let openOrders = {
    orders: {}
  };
  let triggerOrders = {
    orders: {}
  };
  orders.forEach(order => {
    if (order.TAG !== "Limit") {
      return insert$1(triggerOrders, Order__Raw.SnapshotTrigger.toTrigger(order._0));
    }
    let limit = order._0;
    if (!decimalOrZero(limit.common.remaining).isZero()) {
      return insert(openOrders, Order__Raw.SnapshotLimit.toLimit(limit));
    }
  });
  return [
    openOrders,
    triggerOrders
  ];
}

let Limits = {
  make: make,
  get: get,
  getByMarket: getByMarket,
  insert: insert,
  upsert: upsert,
  remove: remove,
  clear: clear,
  isEmpty: isEmpty
};

export {
  Limits,
  Triggers,
  fromSnapshotOrders,
}
/* Order__Raw Not a pure module */
