// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rpc from "../../Rpc.res.mjs";
import * as Http from "../../Http.res.mjs";
import * as Client from "../../Client.res.mjs";
import * as Order__Raw from "./Order__Raw.res.mjs";
import * as Kit from "@solana/kit";
import * as OrderPayload from "../../program/OrderPayload.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function nowSeconds() {
  return Math.floor(Date.now() / 1000.0);
}

async function submit(client, request) {
  return await Http.post(client.http, "/api/orders/submit", Order__Raw.SubmitRequest.toJson(request), "NoRetry", undefined, Order__Raw.SubmitResponse.t_decode);
}

async function submitTrigger(client, request) {
  return await Http.post(client.http, "/api/orders/submit", Order__Raw.SubmitRequest.toJson(request), "NoRetry", undefined, Order__Raw.TriggerResponse.t_decode);
}

function cancelAllMessage(userPubkey, orderbookId, timestamp, salt) {
  return `cancel_all:` + userPubkey + `:` + orderbookId + `:` + timestamp.toString() + `:` + salt;
}

async function cancelBodySigned(orderHash, maker, keypair) {
  let signature = await Kit.signBytes(keypair.privateKey, Kit.getUtf8Encoder().encode(orderHash));
  return {
    orderHash: orderHash,
    maker: maker,
    signatureHex: OrderPayload.signatureHex(signature)
  };
}

async function cancelAllBodySigned(userPubkey, orderbookId, keypair) {
  let timestamp = nowSeconds();
  let salt = crypto.randomUUID();
  let text = cancelAllMessage(userPubkey, orderbookId, timestamp, salt);
  let message = Kit.getUtf8Encoder().encode(text);
  let signature = await Kit.signBytes(keypair.privateKey, message);
  return {
    userPubkey: userPubkey,
    orderbookId: orderbookId,
    signatureHex: OrderPayload.signatureHex(signature),
    timestamp: timestamp,
    salt: salt
  };
}

async function cancel(client, body) {
  let json = Object.fromEntries([
    [
      "order_hash",
      body.orderHash
    ],
    [
      "maker",
      body.maker
    ],
    [
      "signature",
      body.signatureHex
    ]
  ]);
  return await Http.post(client.http, "/api/orders/cancel", json, "NoRetry", undefined, Order__Raw.CancelSuccess.t_decode);
}

async function cancelAll(client, body) {
  let json = Object.fromEntries([
    [
      "user_pubkey",
      body.userPubkey
    ],
    [
      "orderbook_id",
      body.orderbookId
    ],
    [
      "signature",
      body.signatureHex
    ],
    [
      "timestamp",
      body.timestamp
    ],
    [
      "salt",
      body.salt
    ]
  ]);
  return await Http.post(client.http, "/api/orders/cancel-all", json, "NoRetry", undefined, Order__Raw.CancelAllSuccess.t_decode);
}

async function cancelTriggerBodySigned(triggerOrderId, maker, keypair) {
  let signature = await Kit.signBytes(keypair.privateKey, Kit.getUtf8Encoder().encode(triggerOrderId));
  return {
    triggerOrderId: triggerOrderId,
    maker: maker,
    signatureHex: OrderPayload.signatureHex(signature)
  };
}

async function cancelTrigger(client, body) {
  let json = Object.fromEntries([
    [
      "trigger_order_id",
      body.triggerOrderId
    ],
    [
      "maker",
      body.maker
    ],
    [
      "signature",
      body.signatureHex
    ]
  ]);
  return await Http.post(client.http, "/api/orders/cancel", json, "NoRetry", undefined, Order__Raw.CancelTriggerSuccess.t_decode);
}

function signerAddressOrError(client) {
  let address = Client.signerAddress(client);
  if (address !== undefined) {
    return {
      TAG: "Ok",
      _0: Primitive_option.valFromOption(address)
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no signing strategy configured; call Client.useNativeSigner or Client.useExternalSigner first"
      }
    };
  }
}

async function cancelSigned(client, orderHash) {
  let error = signerAddressOrError(client);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let error$1 = await Client.signMessageBytes(client, Kit.getUtf8Encoder().encode(orderHash));
  if (error$1.TAG === "Ok") {
    return await cancel(client, {
      orderHash: orderHash,
      maker: error._0,
      signatureHex: OrderPayload.signatureHex(error$1._0)
    });
  } else {
    return {
      TAG: "Error",
      _0: error$1._0
    };
  }
}

async function cancelAllSigned(client, orderbookId) {
  let error = signerAddressOrError(client);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let userPubkey = error._0;
  let timestamp = nowSeconds();
  let salt = crypto.randomUUID();
  let text = cancelAllMessage(userPubkey, orderbookId, timestamp, salt);
  let message = Kit.getUtf8Encoder().encode(text);
  let error$1 = await Client.signMessageBytes(client, message);
  if (error$1.TAG === "Ok") {
    return await cancelAll(client, {
      userPubkey: userPubkey,
      orderbookId: orderbookId,
      signatureHex: OrderPayload.signatureHex(error$1._0),
      timestamp: timestamp,
      salt: salt
    });
  } else {
    return {
      TAG: "Error",
      _0: error$1._0
    };
  }
}

async function cancelTriggerSigned(client, triggerOrderId) {
  let error = signerAddressOrError(client);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let error$1 = await Client.signMessageBytes(client, Kit.getUtf8Encoder().encode(triggerOrderId));
  if (error$1.TAG === "Ok") {
    return await cancelTrigger(client, {
      triggerOrderId: triggerOrderId,
      maker: error._0,
      signatureHex: OrderPayload.signatureHex(error$1._0)
    });
  } else {
    return {
      TAG: "Error",
      _0: error$1._0
    };
  }
}

async function getUserOrders(client, limit, cursor, cookieHeader) {
  let query = [];
  Stdlib_Option.forEach(limit, value => {
    query.push([
      "limit",
      value.toString()
    ]);
  });
  Stdlib_Option.forEach(cursor, value => {
    query.push([
      "cursor",
      value
    ]);
  });
  return await Http.get(client.http, "/api/users/orders", query, undefined, cookieHeader, Order__Raw.UserOrdersResponse.t_decode);
}

function orderFillsQuery(marketPubkey, limit, cursor) {
  let query = [];
  Stdlib_Option.forEach(marketPubkey, value => {
    query.push([
      "market_pubkey",
      value
    ]);
  });
  Stdlib_Option.forEach(limit, value => {
    query.push([
      "limit",
      value.toString()
    ]);
  });
  Stdlib_Option.forEach(cursor, value => {
    query.push([
      "cursor",
      value
    ]);
  });
  return query;
}

async function getUserOrderFills(client, marketPubkey, limit, cursor, cookieHeader) {
  return await Http.get(client.http, "/api/users/order-fills", orderFillsQuery(marketPubkey, limit, cursor), undefined, cookieHeader, Order__Raw.UserFillsResponse.t_decode);
}

async function getUserOrderFillsByWallet(client, walletAddress, marketPubkey, limit, cursor) {
  return await Http.get(client.http, `/api/users/` + walletAddress + `/order-fills`, orderFillsQuery(marketPubkey, limit, cursor), undefined, undefined, Order__Raw.UserFillsResponse.t_decode);
}

let getNonce = Rpc.getNonce;

let getStatus = Rpc.getOrderStatus;

export {
  submit,
  submitTrigger,
  cancelBodySigned,
  cancelAllBodySigned,
  cancel,
  cancelAll,
  cancelTriggerBodySigned,
  cancelTrigger,
  cancelSigned,
  cancelAllSigned,
  cancelTriggerSigned,
  getUserOrders,
  getUserOrderFills,
  getUserOrderFillsByWallet,
  getNonce,
  getStatus,
}
/* Rpc Not a pure module */
