/**
 * On-chain program interaction module for Lightcone.
 */

// ============================================================================
// ENVELOPE / BUILDER
// ============================================================================
export { LimitOrderEnvelope, type OrderEnvelope } from "./envelope";
export { ProgramSdkError, ProgramSdkError as SdkError } from "./error";
export type { ProgramResult, ProgramResult as SdkResult } from "./error";

// ============================================================================
// TYPES
// ============================================================================
export {
  MarketStatus,
  OrderSide,
  PendingRoleKind,
} from "./types";

export type {
  Exchange,
  GlobalDepositToken,
  Market,
  PayoutNumerators,
  Position,
  OrderStatus,
  UserNonce,
  Orderbook,
  SignedOrder,
  OrderPayload,
  Order,
  InitializeParams,
  CreateMarketParams,
  AddDepositMintParams,
  BuildDepositParams,
  BuildMergeParams,
  CancelOrderParams,
  IncrementNonceParams,
  SettleMarketParams,
  ScalarResolutionParams,
  RedeemWinningsParams,
  SetPausedParams,
  SetOperatorParams,
  WithdrawConditionalFromPositionParams,
  WithdrawFromPositionParams,
  ActivateMarketParams,
  MatchOrdersMultiParams,
  SetAuthorityParams,
  SetManagerParams,
  AcceptRoleParams,
  SetOracleParams,
  MarketFeeUpdate,
  SetMarketFeesParams,
  SetFeeReceiverParams,
  SetFeeReceiverWithAtasParams,
  ConditionalMetadataParams,
  CreateOrderbookParams,
  WhitelistDepositTokenParams,
  SetDepositTokenStatusParams,
  DepositToGlobalParams,
  GlobalToMarketDepositParams,
  InitPositionTokensParams,
  MakerFill,
  DepositAndSwapParams,
  WithdrawFromGlobalParams,
  CloseOrderStatusParams,
  ClosePositionTokenAccountsParams,
  CloseOrderbookParams,
  BuildResult,
  InitializeAccounts,
  CreateMarketAccounts,
  AddDepositMintAccounts,
  MintCompleteSetAccounts,
  MergeCompleteSetAccounts,
  CancelOrderAccounts,
  IncrementNonceAccounts,
  SettleMarketAccounts,
  RedeemWinningsAccounts,
  ActivateMarketAccounts,
  MatchOrdersMultiAccounts,
  BidOrderParams,
  AskOrderParams,
} from "./types";

// ============================================================================
// CONSTANTS
// ============================================================================
export { PROGRAM_ID } from "../env";
export {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  SYSTEM_PROGRAM_ID,
  RENT_SYSVAR_ID,
  MPL_TOKEN_METADATA_PROGRAM_ID,
  INITIALIZE_AUTHORITY,
  INSTRUCTION,
  DISCRIMINATOR,
  ACCOUNT_SIZE,
  ORDER_SIZE,
  MAX_OUTCOMES,
  MIN_OUTCOMES,
  MAX_MAKERS,
  TAKER_MASK,
  PARTICIPANT_MASK_LEN,
  MAX_DEPOSIT_MINTS_PER_MARKET,
  MAX_DEPOSIT_MINTS_PER_IX,
  SEEDS,
} from "./constants";

// ============================================================================
// UTILITIES
// ============================================================================
export {
  toLeBytes,
  fromLeBytes,
  toBeBytes,
  fromBeBytes,
  toU8,
  toU16Le,
  toI16Le,
  toU32Le,
  toU64Le,
  toI64Le,
  fromI64Le,
  keccak256,
  deriveConditionId,
  getAssociatedTokenAddress,
  getConditionalTokenAta,
  getDepositTokenAta,
  serializeString,
  serializeStringU32,
  serializeConditionalMetadata,
  deserializeString,
  validateOutcomes,
  validateOutcomeIndex,
  validateFeePair,
  validate32Bytes,
  winnerTakesAllPayoutNumerators,
  scalarToPayoutNumerators,
} from "./utils";

// ============================================================================
// PDA FUNCTIONS
// ============================================================================
export {
  getExchangePda,
  getEventAuthorityPda,
  getMarketPda,
  getConditionTombstonePda,
  getVaultPda,
  getMintAuthorityPda,
  getConditionalMintPda,
  getAllConditionalMintPdas,
  getMplMetadataPda,
  getOrderStatusPda,
  getUserNoncePda,
  getPositionPda,
  canonicalMintPair,
  getOrderbookPda,
  getGlobalDepositTokenPda,
  getUserGlobalDepositPda,
  pda,
} from "./pda";

// ============================================================================
// ACCOUNT DESERIALIZATION
// ============================================================================
export {
  deserializeExchange,
  deserializeMarket,
  deserializePosition,
  deserializeOrderStatus,
  deserializeUserNonce,
  deserializeOrderbook,
  getOrderbookBaseDepositMint,
  getOrderbookQuoteDepositMint,
  deserializeGlobalDepositToken,
  isExchangeAccount,
  isMarketAccount,
  isPositionAccount,
  isOrderStatusAccount,
  isUserNonceAccount,
  isOrderbookAccount,
  isGlobalDepositTokenAccount,
} from "./accounts";

// ============================================================================
// INSTRUCTION BUILDERS
// ============================================================================
export {
  buildInitializeIx,
  buildCreateMarketIx,
  buildAddDepositMintIx,
  buildDepositIx,
  buildMergeIx,
  buildCancelOrderIx,
  buildIncrementNonceIx,
  buildSettleMarketIx,
  buildRedeemWinningsIx,
  buildSetPausedIx,
  buildSetOperatorIx,
  buildWithdrawConditionalFromPositionIx,
  buildWithdrawFromPositionIx,
  buildActivateMarketIx,
  buildMatchOrdersMultiIx,
  buildSetAuthorityIx,
  buildSetManagerIx,
  buildAcceptAuthorityIx,
  buildAcceptManagerIx,
  buildAcceptOperatorIx,
  buildSetOracleIx,
  buildSetMarketFeesIx,
  buildSetFeeReceiverIx,
  buildSetFeeReceiverWithAtasIx,
  buildCreateConditionalMetadataIx,
  buildUpdateConditionalMetadataIx,
  buildCreateOrderbookIx,
  buildWhitelistDepositTokenIx,
  buildSetDepositTokenStatusIx,
  buildDepositToGlobalIx,
  buildGlobalToMarketDepositIx,
  buildInitPositionTokensIx,
  buildDepositAndSwapIx,
  buildWithdrawFromGlobalIx,
  buildCloseOrderStatusIx,
  buildClosePositionTokenAccountsIx,
  buildCloseOrderbookIx,
  buildInitializeTx,
  buildCreateMarketTx,
  buildAddDepositMintTx,
  buildDepositTx,
  buildMergeTx,
  buildCancelOrderTx,
  buildIncrementNonceTx,
  buildSettleMarketTx,
  buildRedeemWinningsTx,
  buildSetPausedTx,
  buildSetOperatorTx,
  buildWithdrawConditionalFromPositionTx,
  buildWithdrawFromPositionTx,
  buildActivateMarketTx,
  buildMatchOrdersMultiTx,
  buildSetAuthorityTx,
  buildSetManagerTx,
  buildAcceptAuthorityTx,
  buildAcceptManagerTx,
  buildAcceptOperatorTx,
  buildSetOracleTx,
  buildSetMarketFeesTx,
  buildSetFeeReceiverTx,
  buildSetFeeReceiverWithAtasTx,
  buildCreateConditionalMetadataTx,
  buildUpdateConditionalMetadataTx,
  buildCreateOrderbookTx,
  buildWhitelistDepositTokenTx,
  buildSetDepositTokenStatusTx,
  buildDepositToGlobalTx,
  buildGlobalToMarketDepositTx,
  buildInitPositionTokensTx,
  buildDepositAndSwapTx,
  buildWithdrawFromGlobalTx,
  buildCloseOrderStatusTx,
  buildClosePositionTokenAccountsTx,
  buildCloseOrderbookTx,
} from "./instructions";

// ============================================================================
// ORDER UTILITIES
// ============================================================================
export {
  generateSalt,
  hashOrder,
  hashOrderHex,
  getOrderMessage,
  signOrder,
  signOrderFull,
  verifyOrderSignature,
  serializeSignedOrder,
  deserializeSignedOrder,
  serializeOrder,
  deserializeOrder,
  signedOrderToOrder,
  createBidOrder,
  createAskOrder,
  createSignedBidOrder,
  createSignedAskOrder,
  isOrderExpired,
  ordersCanCross,
  calculateTakerFill,
  signatureHex,
  isSigned,
  applySignature,
  orderToSigned,
  deriveOrderbookId,
  toSubmitRequest,
  cancelOrderMessage,
  signCancelOrder,
  cancelAllMessage,
  generateCancelAllSalt,
  signCancelAll,
  is_order_expired,
  orders_can_cross,
  calculate_taker_fill,
  cancel_order_message,
  cancel_all_message,
  generate_cancel_all_salt,
  derive_condition_id,
  apply_signature,
  order_to_signed,
} from "./orders";

// ============================================================================
// ORDER BUILDER
// ============================================================================
export { OrderBuilder } from "./builder";
