// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Messages from "./Messages.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Subscriptions from "./Subscriptions.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let defaultConfig = {
  reconnect: true,
  maxReconnectAttempts: 10,
  baseReconnectDelayMs: 1000,
  pingIntervalMs: 30000,
  pongTimeoutMs: 10000
};

function sendMessage(connection, message) {
  let socket = connection.socket;
  if (socket === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Ws",
        _0: "NotConnected"
      }
    };
  }
  let socket$1 = Primitive_option.valFromOption(socket);
  if (socket$1.readyState !== 1) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Ws",
        _0: "NotConnected"
      }
    };
  }
  let text = JSON.stringify(Subscriptions.toJson(message));
  try {
    socket$1.send(text);
    return {
      TAG: "Ok",
      _0: undefined
    };
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "Ws",
          _0: {
            TAG: "SendFailed",
            _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "socket send failed")
          }
        }
      };
    }
    throw error;
  }
}

function clearPongTimer(connection) {
  Stdlib_Option.forEach(connection.pongTimer, timer => {
    clearTimeout(timer);
  });
  connection.pongTimer = undefined;
}

function clearTimers(connection) {
  Stdlib_Option.forEach(connection.pingTimer, timer => {
    clearInterval(timer);
  });
  connection.pingTimer = undefined;
  clearPongTimer(connection);
}

function reconnectDelay(connection, code) {
  let raw = connection.reconnectAttempts - 1 | 0;
  let cappedExponent = raw > 10 ? 10 : raw;
  let base = connection.config.baseReconnectDelayMs * Math.pow(2.0, cappedExponent);
  let match = code === 1008 ? [
      1000.0,
      300000.0
    ] : [
      500.0,
      60000.0
    ];
  let jitter = Math.random() * match[0];
  return Math.min(base + jitter, match[1]) | 0;
}

function establish(connection) {
  let socket = new WebSocket(connection.url);
  connection.socket = Primitive_option.some(socket);
  socket.onopen = () => {
    connection.reconnectAttempts = 0;
    connection.activeSubscriptions.forEach(params => {
      sendMessage(connection, {
        TAG: "Subscribe",
        _0: params
      });
    });
    startHeartbeat(connection);
    connection.onConnected();
  };
  socket.onmessage = event => {
    clearPongTimer(connection);
    let text = event.data;
    let json;
    try {
      json = JSON.parse(text);
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === "JsExn") {
        return connection.onError({
          TAG: "Ws",
          _0: {
            TAG: "DeserializationError",
            _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "invalid JSON frame")
          }
        });
      }
      throw error;
    }
    let message = Messages.decodeMessage(json);
    if (message.TAG === "Ok") {
      return connection.onMessage(message._0);
    } else {
      return connection.onError(message._0);
    }
  };
  socket.onerror = _event => connection.onError({
    TAG: "Ws",
    _0: {
      TAG: "ConnectionFailed",
      _0: "websocket error"
    }
  });
  socket.onclose = event => {
    let code = event.code;
    let reason = event.reason;
    clearTimers(connection);
    connection.socket = undefined;
    connection.onDisconnected(code, reason);
    if (!connection.closedByUser && connection.config.reconnect && code !== 1000) {
      if (connection.reconnectAttempts >= connection.config.maxReconnectAttempts) {
        return connection.onError({
          TAG: "Ws",
          _0: {
            TAG: "ConnectionFailed",
            _0: `max reconnect attempts (` + connection.config.maxReconnectAttempts.toString() + `) reached`
          }
        });
      }
      connection.reconnectAttempts = connection.reconnectAttempts + 1 | 0;
      let delay = reconnectDelay(connection, code);
      setTimeout(() => {
        if (!connection.closedByUser) {
          return establish(connection);
        }
      }, delay);
      return;
    }
  };
}

function startHeartbeat(connection) {
  Stdlib_Option.forEach(connection.pingTimer, timer => {
    clearInterval(timer);
  });
  let timer = setInterval(() => {
    let match = sendMessage(connection, "Ping");
    if (match.TAG !== "Ok") {
      return;
    }
    clearPongTimer(connection);
    connection.pongTimer = Primitive_option.some(setTimeout(() => Stdlib_Option.forEach(connection.socket, socket => {
      socket.close();
    }), connection.config.pongTimeoutMs));
  }, connection.config.pingIntervalMs);
  connection.pingTimer = Primitive_option.some(timer);
}

function connect(url, onMessage, onConnectedOpt, onDisconnectedOpt, onErrorOpt, configOpt, param) {
  let onConnected = onConnectedOpt !== undefined ? onConnectedOpt : () => {};
  let onDisconnected = onDisconnectedOpt !== undefined ? onDisconnectedOpt : (param, param$1) => {};
  let onError = onErrorOpt !== undefined ? onErrorOpt : param => {};
  let config = configOpt !== undefined ? configOpt : defaultConfig;
  let connection = {
    url: url,
    config: config,
    onMessage: onMessage,
    onConnected: onConnected,
    onDisconnected: onDisconnected,
    onError: onError,
    socket: undefined,
    activeSubscriptions: [],
    reconnectAttempts: 0,
    closedByUser: false,
    pingTimer: undefined,
    pongTimer: undefined
  };
  establish(connection);
  return connection;
}

function isConnected(connection) {
  let socket = connection.socket;
  if (socket !== undefined) {
    return Primitive_option.valFromOption(socket).readyState === 1;
  } else {
    return false;
  }
}

function subscribe(connection, params) {
  let key = Subscriptions.subscriptionKey(params);
  let alreadyTracked = connection.activeSubscriptions.some(existing => Subscriptions.subscriptionKey(existing) === key);
  if (!alreadyTracked) {
    connection.activeSubscriptions.push(params);
  }
  sendMessage(connection, {
    TAG: "Subscribe",
    _0: params
  });
  return {
    TAG: "Ok",
    _0: undefined
  };
}

function unsubscribe(connection, params) {
  connection.activeSubscriptions = connection.activeSubscriptions.filter(sub => !Subscriptions.matchesUnsubscribe(sub, params));
  sendMessage(connection, {
    TAG: "Unsubscribe",
    _0: params
  });
  return {
    TAG: "Ok",
    _0: undefined
  };
}

function ping(connection) {
  return sendMessage(connection, "Ping");
}

function disconnect(connection) {
  connection.closedByUser = true;
  clearTimers(connection);
  Stdlib_Option.forEach(connection.socket, socket => {
    socket.close(1000, "Client disconnect");
  });
  connection.socket = undefined;
}

export {
  defaultConfig,
  connect,
  isConnected,
  subscribe,
  unsubscribe,
  ping,
  disconnect,
}
/* Messages Not a pure module */
