// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as SortedBtree from "../SortedBtree.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function intCompare(left, right) {
  return left - right | 0;
}

function emptyTree() {
  return SortedBtree.make(undefined, intCompare, undefined);
}

function seededTree() {
  let tree = emptyTree();
  tree.set(3, "c");
  tree.set(1, "a");
  tree.set(2, "b");
  return tree;
}

Buntest.describe("SortedBtree — construction", () => {
  Buntest.test("make with ~entries seeds and sorts the tree", () => {
    let tree = SortedBtree.make([
      [
        2,
        "b"
      ],
      [
        1,
        "a"
      ],
      [
        3,
        "c"
      ]
    ], intCompare, undefined);
    Buntest.expect(tree.keysArray()).toEqual([
      1,
      2,
      3
    ]);
    Buntest.expect(Stdlib_Option.getOr(tree.get(1), "?")).toBe("a");
  });
});

Buntest.describe("SortedBtree — mutation", () => {
  Buntest.test("set returns true for a new key", () => {
    Buntest.expect(emptyTree().set(5, "e")).toBe(true);
  });
  Buntest.test("set returns false when overwriting an existing key", () => {
    let tree = seededTree();
    Buntest.expect(tree.set(1, "A")).toBe(false);
    Buntest.expect(Stdlib_Option.getOr(tree.get(1), "?")).toBe("A");
  });
  Buntest.test("delete returns true and shrinks the tree", () => {
    let tree = seededTree();
    Buntest.expect(tree.delete(2)).toBe(true);
    Buntest.expect(tree.size).toBe(2);
    Buntest.expect(tree.has(2)).toBe(false);
  });
  Buntest.test("delete returns false for an absent key", () => {
    Buntest.expect(seededTree().delete(99)).toBe(false);
  });
  Buntest.test("clear empties the tree", () => {
    let tree = seededTree();
    tree.clear();
    Buntest.expect(tree.size).toBe(0);
    Buntest.expect(Stdlib_Option.isNone(tree.minKey())).toBe(true);
  });
});

Buntest.describe("SortedBtree — lookup", () => {
  Buntest.test("get returns Some for a present key", () => {
    Buntest.expect(Stdlib_Option.getOr(seededTree().get(2), "?")).toBe("b");
  });
  Buntest.test("get returns None for an absent key", () => {
    Buntest.expect(Stdlib_Option.isNone(seededTree().get(9))).toBe(true);
  });
  Buntest.test("has reflects membership", () => {
    let tree = seededTree();
    Buntest.expect(tree.has(1)).toBe(true);
    Buntest.expect(tree.has(9)).toBe(false);
  });
  Buntest.test("size counts the entries", () => {
    Buntest.expect(seededTree().size).toBe(3);
  });
  Buntest.test("minKey returns Some(smallest), None when empty", () => {
    Buntest.expect(Stdlib_Option.getOr(seededTree().minKey(), -1)).toBe(1);
    Buntest.expect(Stdlib_Option.isNone(emptyTree().minKey())).toBe(true);
  });
  Buntest.test("maxKey returns Some(largest), None when empty", () => {
    Buntest.expect(Stdlib_Option.getOr(seededTree().maxKey(), -1)).toBe(3);
    Buntest.expect(Stdlib_Option.isNone(emptyTree().maxKey())).toBe(true);
  });
});

Buntest.describe("SortedBtree — ordered snapshots", () => {
  Buntest.test("keysArray is ascending regardless of insert order", () => {
    Buntest.expect(seededTree().keysArray()).toEqual([
      1,
      2,
      3
    ]);
  });
  Buntest.test("valuesArray follows key order", () => {
    Buntest.expect(seededTree().valuesArray()).toEqual([
      "a",
      "b",
      "c"
    ]);
  });
  Buntest.test("toArray returns (key, value) tuples in key order", () => {
    Buntest.expect(seededTree().toArray()).toEqual([
      [
        1,
        "a"
      ],
      [
        2,
        "b"
      ],
      [
        3,
        "c"
      ]
    ]);
  });
  Buntest.test("forEachPair visits pairs in ascending key order and returns the count", () => {
    let tree = seededTree();
    let seenKeys = [];
    let visited = tree.forEachPair((key, _value) => {
      seenKeys.push(key);
    });
    Buntest.expect(seenKeys).toEqual([
      1,
      2,
      3
    ]);
    Buntest.expect(visited).toBe(3);
  });
});

export {
  intCompare,
  emptyTree,
  seededTree,
}
/*  Not a pure module */
