// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Shared from "../../Shared.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function t_encode(v) {
  let extra = v.m;
  let extra$1 = v.o;
  let extra$2 = v.h;
  let extra$3 = v.l;
  let extra$4 = v.c;
  let extra$5 = v.v;
  let extra$6 = v.bb;
  let extra$7 = v.ba;
  return Object.fromEntries(Spice.filterOptional([
    [
      "t",
      Spice.floatToJson(v.t)
    ],
    [
      "m",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "o",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "h",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ],
    [
      "l",
      Spice.optionToJson(Spice.stringToJson, extra$3)
    ],
    [
      "c",
      Spice.optionToJson(Spice.stringToJson, extra$4)
    ],
    [
      "v",
      Spice.optionToJson(Spice.stringToJson, extra$5)
    ],
    [
      "bb",
      Spice.optionToJson(Spice.stringToJson, extra$6)
    ],
    [
      "ba",
      Spice.optionToJson(Spice.stringToJson, extra$7)
    ]
  ]));
}

function t_encodeJson(v) {
  let extra = v.m;
  let extra$1 = v.o;
  let extra$2 = v.h;
  let extra$3 = v.l;
  let extra$4 = v.c;
  let extra$5 = v.v;
  let extra$6 = v.bb;
  let extra$7 = v.ba;
  return Object.fromEntries(Spice.filterOptional([
    [
      "t",
      Spice.floatToJson(v.t)
    ],
    [
      "m",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "o",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "h",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ],
    [
      "l",
      Spice.optionToJson(Spice.stringToJson, extra$3)
    ],
    [
      "c",
      Spice.optionToJson(Spice.stringToJson, extra$4)
    ],
    [
      "v",
      Spice.optionToJson(Spice.stringToJson, extra$5)
    ],
    [
      "bb",
      Spice.optionToJson(Spice.stringToJson, extra$6)
    ],
    [
      "ba",
      Spice.optionToJson(Spice.stringToJson, extra$7)
    ]
  ]));
}

function t_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let t = Stdlib_Option.getOr(Stdlib_Option.map(v["t"], Spice.floatFromJson), Spice.error(undefined, "t" + " missing", v));
  if (t.TAG === "Ok") {
    let m = Stdlib_Option.getOr(Stdlib_Option.map(v["m"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
      TAG: "Ok",
      _0: undefined
    });
    if (m.TAG === "Ok") {
      let o = Stdlib_Option.getOr(Stdlib_Option.map(v["o"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (o.TAG === "Ok") {
        let h = Stdlib_Option.getOr(Stdlib_Option.map(v["h"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (h.TAG === "Ok") {
          let l = Stdlib_Option.getOr(Stdlib_Option.map(v["l"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
            TAG: "Ok",
            _0: undefined
          });
          if (l.TAG === "Ok") {
            let c = Stdlib_Option.getOr(Stdlib_Option.map(v["c"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
              TAG: "Ok",
              _0: undefined
            });
            if (c.TAG === "Ok") {
              let v$1 = Stdlib_Option.getOr(Stdlib_Option.map(v["v"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
                TAG: "Ok",
                _0: undefined
              });
              if (v$1.TAG === "Ok") {
                let bb = Stdlib_Option.getOr(Stdlib_Option.map(v["bb"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
                  TAG: "Ok",
                  _0: undefined
                });
                if (bb.TAG === "Ok") {
                  let ba = Stdlib_Option.getOr(Stdlib_Option.map(v["ba"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
                    TAG: "Ok",
                    _0: undefined
                  });
                  if (ba.TAG === "Ok") {
                    return {
                      TAG: "Ok",
                      _0: {
                        t: t._0,
                        m: m._0,
                        o: o._0,
                        h: h._0,
                        l: l._0,
                        c: c._0,
                        v: v$1._0,
                        bb: bb._0,
                        ba: ba._0
                      }
                    };
                  }
                  let e = ba._0;
                  return Spice.error("." + ("ba" + e.path), e.message, e.value);
                }
                let e$1 = bb._0;
                return Spice.error("." + ("bb" + e$1.path), e$1.message, e$1.value);
              }
              let e$2 = v$1._0;
              return Spice.error("." + ("v" + e$2.path), e$2.message, e$2.value);
            }
            let e$3 = c._0;
            return Spice.error("." + ("c" + e$3.path), e$3.message, e$3.value);
          }
          let e$4 = l._0;
          return Spice.error("." + ("l" + e$4.path), e$4.message, e$4.value);
        }
        let e$5 = h._0;
        return Spice.error("." + ("h" + e$5.path), e$5.message, e$5.value);
      }
      let e$6 = o._0;
      return Spice.error("." + ("o" + e$6.path), e$6.message, e$6.value);
    }
    let e$7 = m._0;
    return Spice.error("." + ("m" + e$7.path), e$7.message, e$7.value);
  }
  let e$8 = t._0;
  return Spice.error("." + ("t" + e$8.path), e$8.message, e$8.value);
}

function toLineData(candle) {
  let midpoint = candle.m;
  let value = midpoint !== undefined ? midpoint : Stdlib_Option.getOr(candle.c, "");
  return {
    time: candle.t,
    value: value
  };
}

let OrderbookCandle = {
  t_encode: t_encode,
  t_encodeJson: t_encodeJson,
  t_decode: t_decode,
  toLineData: toLineData
};

function t_encode$1(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "t",
      Spice.floatToJson(v.t)
    ],
    [
      "tc",
      Spice.floatToJson(v.tc)
    ],
    [
      "c",
      Spice.stringToJson(v.c)
    ]
  ]));
}

function t_encodeJson$1(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "t",
      Spice.floatToJson(v.t)
    ],
    [
      "tc",
      Spice.floatToJson(v.tc)
    ],
    [
      "c",
      Spice.stringToJson(v.c)
    ]
  ]));
}

function t_decode$1(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let t = Stdlib_Option.getOr(Stdlib_Option.map(v["t"], Spice.floatFromJson), Spice.error(undefined, "t" + " missing", v));
  if (t.TAG === "Ok") {
    let tc = Stdlib_Option.getOr(Stdlib_Option.map(v["tc"], Spice.floatFromJson), Spice.error(undefined, "tc" + " missing", v));
    if (tc.TAG === "Ok") {
      let c = Stdlib_Option.getOr(Stdlib_Option.map(v["c"], Spice.stringFromJson), Spice.error(undefined, "c" + " missing", v));
      if (c.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            t: t._0,
            tc: tc._0,
            c: c._0
          }
        };
      }
      let e = c._0;
      return Spice.error("." + ("c" + e.path), e.message, e.value);
    }
    let e$1 = tc._0;
    return Spice.error("." + ("tc" + e$1.path), e$1.message, e$1.value);
  }
  let e$2 = t._0;
  return Spice.error("." + ("t" + e$2.path), e$2.message, e$2.value);
}

let DepositCandle = {
  t_encode: t_encode$1,
  t_encodeJson: t_encodeJson$1,
  t_decode: t_decode$1
};

function t_encode$2(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "price",
      Spice.floatToJson(v.price)
    ],
    [
      "volume",
      Spice.floatToJson(v.volume)
    ]
  ]));
}

function t_encodeJson$2(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "price",
      Spice.floatToJson(v.price)
    ],
    [
      "volume",
      Spice.floatToJson(v.volume)
    ]
  ]));
}

function t_decode$2(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let price = Stdlib_Option.getOr(Stdlib_Option.map(v["price"], Spice.floatFromJson), Spice.error(undefined, "price" + " missing", v));
  if (price.TAG === "Ok") {
    let volume = Stdlib_Option.getOr(Stdlib_Option.map(v["volume"], Spice.floatFromJson), Spice.error(undefined, "volume" + " missing", v));
    if (volume.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          price: price._0,
          volume: volume._0
        }
      };
    }
    let e = volume._0;
    return Spice.error("." + ("volume" + e.path), e.message, e.value);
  }
  let e$1 = price._0;
  return Spice.error("." + ("price" + e$1.path), e$1.message, e$1.value);
}

let Decimals = {
  t_encode: t_encode$2,
  t_encodeJson: t_encodeJson$2,
  t_decode: t_decode$2
};

function t_encode$3(v) {
  let extra = v.prices;
  let extra$1 = v.nextCursor;
  return Object.fromEntries(Spice.filterOptional([
    [
      "orderbook_id",
      Shared.orderBookId_encodeJson(v.orderbookId)
    ],
    [
      "resolution",
      Shared.Resolution.t_encodeJson(v.resolution)
    ],
    [
      "include_ohlcv",
      Spice.boolToJson(v.includeOhlcv)
    ],
    [
      "prices",
      Spice.arrayToJson(t_encodeJson, extra)
    ],
    [
      "next_cursor",
      Spice.optionToJson(Spice.floatToJson, extra$1)
    ],
    [
      "has_more",
      Spice.boolToJson(v.hasMore)
    ],
    [
      "decimals",
      t_encodeJson$2(v.decimals)
    ]
  ]));
}

function t_encodeJson$3(v) {
  let extra = v.prices;
  let extra$1 = v.nextCursor;
  return Object.fromEntries(Spice.filterOptional([
    [
      "orderbook_id",
      Shared.orderBookId_encodeJson(v.orderbookId)
    ],
    [
      "resolution",
      Shared.Resolution.t_encodeJson(v.resolution)
    ],
    [
      "include_ohlcv",
      Spice.boolToJson(v.includeOhlcv)
    ],
    [
      "prices",
      Spice.arrayToJson(t_encodeJson, extra)
    ],
    [
      "next_cursor",
      Spice.optionToJson(Spice.floatToJson, extra$1)
    ],
    [
      "has_more",
      Spice.boolToJson(v.hasMore)
    ],
    [
      "decimals",
      t_encodeJson$2(v.decimals)
    ]
  ]));
}

function t_decode$3(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let orderbookId = Stdlib_Option.getOr(Stdlib_Option.map(v["orderbook_id"], Shared.orderBookId_decode), Spice.error(undefined, "orderbook_id" + " missing", v));
  if (orderbookId.TAG === "Ok") {
    let resolution = Stdlib_Option.getOr(Stdlib_Option.map(v["resolution"], Shared.Resolution.t_decode), Spice.error(undefined, "resolution" + " missing", v));
    if (resolution.TAG === "Ok") {
      let includeOhlcv = Stdlib_Option.getOr(Stdlib_Option.map(v["include_ohlcv"], Spice.boolFromJson), Spice.error(undefined, "include_ohlcv" + " missing", v));
      if (includeOhlcv.TAG === "Ok") {
        let prices = Stdlib_Option.getOr(Stdlib_Option.map(v["prices"], extra => Spice.arrayFromJson(t_decode, extra)), Spice.error(undefined, "prices" + " missing", v));
        if (prices.TAG === "Ok") {
          let nextCursor = Stdlib_Option.getOr(Stdlib_Option.map(v["next_cursor"], json => Stdlib_Result.map(Spice.floatFromJson(json), v => v)), {
            TAG: "Ok",
            _0: undefined
          });
          if (nextCursor.TAG === "Ok") {
            let hasMore = Stdlib_Option.getOr(Stdlib_Option.map(v["has_more"], Spice.boolFromJson), Spice.error(undefined, "has_more" + " missing", v));
            if (hasMore.TAG === "Ok") {
              let decimals = Stdlib_Option.getOr(Stdlib_Option.map(v["decimals"], t_decode$2), Spice.error(undefined, "decimals" + " missing", v));
              if (decimals.TAG === "Ok") {
                return {
                  TAG: "Ok",
                  _0: {
                    orderbookId: orderbookId._0,
                    resolution: resolution._0,
                    includeOhlcv: includeOhlcv._0,
                    prices: prices._0,
                    nextCursor: nextCursor._0,
                    hasMore: hasMore._0,
                    decimals: decimals._0
                  }
                };
              }
              let e = decimals._0;
              return Spice.error("." + ("decimals" + e.path), e.message, e.value);
            }
            let e$1 = hasMore._0;
            return Spice.error("." + ("has_more" + e$1.path), e$1.message, e$1.value);
          }
          let e$2 = nextCursor._0;
          return Spice.error("." + ("next_cursor" + e$2.path), e$2.message, e$2.value);
        }
        let e$3 = prices._0;
        return Spice.error("." + ("prices" + e$3.path), e$3.message, e$3.value);
      }
      let e$4 = includeOhlcv._0;
      return Spice.error("." + ("include_ohlcv" + e$4.path), e$4.message, e$4.value);
    }
    let e$5 = resolution._0;
    return Spice.error("." + ("resolution" + e$5.path), e$5.message, e$5.value);
  }
  let e$6 = orderbookId._0;
  return Spice.error("." + ("orderbook_id" + e$6.path), e$6.message, e$6.value);
}

let OrderbookResponse = {
  t_encode: t_encode$3,
  t_encodeJson: t_encodeJson$3,
  t_decode: t_decode$3
};

function t_encode$4(v) {
  let extra = v.prices;
  let extra$1 = v.nextCursor;
  return Object.fromEntries(Spice.filterOptional([
    [
      "deposit_asset",
      Shared.pubkeyStr_encodeJson(v.depositAsset)
    ],
    [
      "binance_symbol",
      Spice.stringToJson(v.binanceSymbol)
    ],
    [
      "resolution",
      Shared.Resolution.t_encodeJson(v.resolution)
    ],
    [
      "prices",
      Spice.arrayToJson(t_encodeJson$1, extra)
    ],
    [
      "next_cursor",
      Spice.optionToJson(Spice.floatToJson, extra$1)
    ],
    [
      "has_more",
      Spice.boolToJson(v.hasMore)
    ]
  ]));
}

function t_encodeJson$4(v) {
  let extra = v.prices;
  let extra$1 = v.nextCursor;
  return Object.fromEntries(Spice.filterOptional([
    [
      "deposit_asset",
      Shared.pubkeyStr_encodeJson(v.depositAsset)
    ],
    [
      "binance_symbol",
      Spice.stringToJson(v.binanceSymbol)
    ],
    [
      "resolution",
      Shared.Resolution.t_encodeJson(v.resolution)
    ],
    [
      "prices",
      Spice.arrayToJson(t_encodeJson$1, extra)
    ],
    [
      "next_cursor",
      Spice.optionToJson(Spice.floatToJson, extra$1)
    ],
    [
      "has_more",
      Spice.boolToJson(v.hasMore)
    ]
  ]));
}

function t_decode$4(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let depositAsset = Stdlib_Option.getOr(Stdlib_Option.map(v["deposit_asset"], Shared.pubkeyStr_decode), Spice.error(undefined, "deposit_asset" + " missing", v));
  if (depositAsset.TAG === "Ok") {
    let binanceSymbol = Stdlib_Option.getOr(Stdlib_Option.map(v["binance_symbol"], Spice.stringFromJson), Spice.error(undefined, "binance_symbol" + " missing", v));
    if (binanceSymbol.TAG === "Ok") {
      let resolution = Stdlib_Option.getOr(Stdlib_Option.map(v["resolution"], Shared.Resolution.t_decode), Spice.error(undefined, "resolution" + " missing", v));
      if (resolution.TAG === "Ok") {
        let prices = Stdlib_Option.getOr(Stdlib_Option.map(v["prices"], extra => Spice.arrayFromJson(t_decode$1, extra)), Spice.error(undefined, "prices" + " missing", v));
        if (prices.TAG === "Ok") {
          let nextCursor = Stdlib_Option.getOr(Stdlib_Option.map(v["next_cursor"], json => Stdlib_Result.map(Spice.floatFromJson(json), v => v)), {
            TAG: "Ok",
            _0: undefined
          });
          if (nextCursor.TAG === "Ok") {
            let hasMore = Stdlib_Option.getOr(Stdlib_Option.map(v["has_more"], Spice.boolFromJson), Spice.error(undefined, "has_more" + " missing", v));
            if (hasMore.TAG === "Ok") {
              return {
                TAG: "Ok",
                _0: {
                  depositAsset: depositAsset._0,
                  binanceSymbol: binanceSymbol._0,
                  resolution: resolution._0,
                  prices: prices._0,
                  nextCursor: nextCursor._0,
                  hasMore: hasMore._0
                }
              };
            }
            let e = hasMore._0;
            return Spice.error("." + ("has_more" + e.path), e.message, e.value);
          }
          let e$1 = nextCursor._0;
          return Spice.error("." + ("next_cursor" + e$1.path), e$1.message, e$1.value);
        }
        let e$2 = prices._0;
        return Spice.error("." + ("prices" + e$2.path), e$2.message, e$2.value);
      }
      let e$3 = resolution._0;
      return Spice.error("." + ("resolution" + e$3.path), e$3.message, e$3.value);
    }
    let e$4 = binanceSymbol._0;
    return Spice.error("." + ("binance_symbol" + e$4.path), e$4.message, e$4.value);
  }
  let e$5 = depositAsset._0;
  return Spice.error("." + ("deposit_asset" + e$5.path), e$5.message, e$5.value);
}

let DepositResponse = {
  t_encode: t_encode$4,
  t_encodeJson: t_encodeJson$4,
  t_decode: t_decode$4
};

function t_encode$5(v) {
  let extra = v.prices;
  return Object.fromEntries(Spice.filterOptional([[
      "prices",
      Spice.dictToJson(Spice.stringToJson, extra)
    ]]));
}

function t_encodeJson$5(v) {
  let extra = v.prices;
  return Object.fromEntries(Spice.filterOptional([[
      "prices",
      Spice.dictToJson(Spice.stringToJson, extra)
    ]]));
}

function t_decode$5(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let prices = Stdlib_Option.getOr(Stdlib_Option.map(v["prices"], extra => Spice.dictFromJson(Spice.stringFromJson, extra)), Spice.error(undefined, "prices" + " missing", v));
  if (prices.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        prices: prices._0
      }
    };
  }
  let e = prices._0;
  return Spice.error("." + ("prices" + e.path), e.message, e.value);
}

let DepositPricesSnapshotResponse = {
  t_encode: t_encode$5,
  t_encodeJson: t_encodeJson$5,
  t_decode: t_decode$5
};

export {
  OrderbookCandle,
  DepositCandle,
  Decimals,
  OrderbookResponse,
  DepositResponse,
  DepositPricesSnapshotResponse,
}
/* Shared Not a pure module */
