#![doc = include_str!("ADMIN.md")]

pub mod client;
pub mod wire;

pub use wire::{
    AddMetadataCategoryRequest, AddMetadataCategoryResponse, AdminCategoriesQuery,
    AdminCategoriesResponse, AdminCategoryRow, AdminConditionalMintRow,
    AdminConditionalTokenMetadataEntry, AdminConditionalTokenMetadataRow,
    AdminDepositTokenMetadataListResponse, AdminDepositTokenMetadataResponse, AdminDepositTokenRow,
    AdminDepositTokensQuery, AdminDepositTokensResponse, AdminImageVariants, AdminLogEvent,
    AdminLogEventsQuery, AdminLogEventsResponse, AdminLogMetricBreakdown,
    AdminLogMetricHistoryQuery, AdminLogMetricHistoryResponse, AdminLogMetricPoint,
    AdminLogMetricSummary, AdminLogMetricsQuery, AdminLogMetricsResponse, AdminLoginRequest,
    AdminLoginResponse, AdminMarketDepositAsset, AdminMarketMetadataResponse,
    AdminMarketMetadataRow, AdminMarketRow, AdminMarketStatus, AdminMarketStatusFilter,
    AdminMarketsQuery, AdminMarketsResponse, AdminMetadataMarket, AdminMetricsTableQuery,
    AdminMissingMetadata, AdminNonceResponse, AdminOutcomeMetadataEntry, AdminOutcomeMetadataRow,
    AllocateCodesRequest, AllocateCodesResponse, CodeListEntry,
    ConditionalTokenMetadataJsonResponse, ConditionalTokenMetadataPayload,
    ConditionalTokenMetadataRow, CreateNotificationRequest, CreateNotificationResponse,
    CriticalLogErrors24hCountResponse, DepositTokenMetadataPayload, DepositTokenMetadataResponse,
    DismissNotificationRequest, DismissNotificationResponse, ListCodesRequest, ListCodesResponse,
    MarketDeploymentConditionalToken, MarketDeploymentDepositAsset, MarketDeploymentMarket,
    MarketDeploymentOutcome, MarketMetadataPayload, MarketsToSettleCountResponse,
    MarketsToSettleQuery, MarketsToSettleResponse, MetadataCategoriesResponse,
    MetadataImageTargetType, MetadataImageUpdate, MetadataImageUpdateResponse,
    OutcomeMetadataPayload, ReferralConfig, ResyncConditionalTokenDerivedMetadataResponse,
    RevokeRequest, RevokeResponse, TargetSpec, UnifiedMetadataRequest, UnifiedMetadataResponse,
    UnrevokeRequest, UnrevokeResponse, UpdateCodeRequest, UpdateCodeResponse,
    UpdateConditionalTokenImageRequest, UpdateConditionalTokenMetadataJsonRequest,
    UpdateConditionalTokenMetadataPayload, UpdateConfigRequest, UpdateDepositTokenImagesRequest,
    UpdateDepositTokenMetadataRequest, UpdateDepositTokenMetadataResponse,
    UpdateMarketImagesRequest, UpdateMarketMetadataPayload, UpdateMarketMetadataRequest,
    UpdateMarketMetadataResponse, UpdateOutcomeImageRequest, UpdateOutcomeMetadataPayload,
    UploadDepositTokenImagesRequest, UploadDepositTokenImagesResponse,
    UploadMarketDeploymentAssetsRequest, UploadMarketDeploymentAssetsResponse,
    UploadedConditionalToken, UploadedDepositAssetImages, UploadedMarketImages,
    UploadedOutcomeImages, WhitelistRequest, WhitelistResponse,
};
