// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kit from "@solana/kit";

function signinMessage(nonce) {
  return `Sign in to Lightcone\nNonce: ` + nonce;
}

let bytesToIntArray = ((bytes) => Array.from(bytes));

function signedLogin(message, signature, address) {
  return {
    message: message,
    signatureBs58: Kit.getBase58Decoder().decode(signature),
    pubkeyBytes: bytesToIntArray(Kit.getAddressEncoder().encode(address))
  };
}

async function signLoginMessage(keypair, nonce) {
  let message = signinMessage(nonce);
  let messageBytes = Kit.getUtf8Encoder().encode(message);
  let signature = await Kit.signBytes(keypair.privateKey, messageBytes);
  let address = await Kit.getAddressFromPublicKey(keypair.publicKey);
  return signedLogin(message, signature, address);
}

export {
  signinMessage,
  signedLogin,
  signLoginMessage,
}
/* @solana/kit Not a pure module */
