// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function t_encode(v) {
  if (v === "privy") {
    return "privy";
  } else {
    return "lightcone";
  }
}

function t_encodeJson(v) {
  if (v === "privy") {
    return "privy";
  } else {
    return "lightcone";
  }
}

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("privy" === v) {
        return {
          TAG: "Ok",
          _0: "privy"
        };
      } else if ("lightcone" === v) {
        return {
          TAG: "Ok",
          _0: "lightcone"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let Method = {
  t_encode: t_encode,
  t_encodeJson: t_encodeJson,
  t_decode: t_decode
};

function t_encode$1(v) {
  if (v === "solana") {
    return "solana";
  } else {
    return "ethereum";
  }
}

function t_encodeJson$1(v) {
  if (v === "solana") {
    return "solana";
  } else {
    return "ethereum";
  }
}

function t_decode$1(v) {
  switch (typeof v) {
    case "string" :
      if ("solana" === v) {
        return {
          TAG: "Ok",
          _0: "solana"
        };
      } else if ("ethereum" === v) {
        return {
          TAG: "Ok",
          _0: "ethereum"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let ChainType = {
  t_encode: t_encode$1,
  t_encodeJson: t_encodeJson$1,
  t_decode: t_decode$1
};

function t_encodeJson$2(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "privy_id",
      Spice.stringToJson(v.privyId)
    ],
    [
      "chain",
      t_encodeJson$1(v.chain)
    ],
    [
      "address",
      Spice.stringToJson(v.address)
    ]
  ]));
}

function t_decode$2(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let privyId = Stdlib_Option.getOr(Stdlib_Option.map(v["privy_id"], Spice.stringFromJson), Spice.error(undefined, "privy_id" + " missing", v));
  if (privyId.TAG === "Ok") {
    let chain = Stdlib_Option.getOr(Stdlib_Option.map(v["chain"], t_decode$1), Spice.error(undefined, "chain" + " missing", v));
    if (chain.TAG === "Ok") {
      let address = Stdlib_Option.getOr(Stdlib_Option.map(v["address"], Spice.stringFromJson), Spice.error(undefined, "address" + " missing", v));
      if (address.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            privyId: privyId._0,
            chain: chain._0,
            address: address._0
          }
        };
      }
      let e = address._0;
      return Spice.error("." + ("address" + e.path), e.message, e.value);
    }
    let e$1 = chain._0;
    return Spice.error("." + ("chain" + e$1.path), e$1.message, e$1.value);
  }
  let e$2 = privyId._0;
  return Spice.error("." + ("privy_id" + e$2.path), e$2.message, e$2.value);
}

function t_encode$2(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.stringToJson(v.id)
    ],
    [
      "wallet",
      t_encodeJson$2(v.wallet)
    ]
  ]));
}

function t_encodeJson$3(v) {
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.stringToJson(v.id)
    ],
    [
      "wallet",
      t_encodeJson$2(v.wallet)
    ]
  ]));
}

function t_decode$3(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let id = Stdlib_Option.getOr(Stdlib_Option.map(v["id"], Spice.stringFromJson), Spice.error(undefined, "id" + " missing", v));
  if (id.TAG === "Ok") {
    let wallet = Stdlib_Option.getOr(Stdlib_Option.map(v["wallet"], t_decode$2), Spice.error(undefined, "wallet" + " missing", v));
    if (wallet.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          id: id._0,
          wallet: wallet._0
        }
      };
    }
    let e = wallet._0;
    return Spice.error("." + ("wallet" + e.path), e.message, e.value);
  }
  let e$1 = id._0;
  return Spice.error("." + ("id" + e$1.path), e$1.message, e$1.value);
}

let PrivyData = {
  t_encode: t_encode$2,
  t_encodeJson: t_encodeJson$3,
  t_decode: t_decode$3
};

function t_encode$3(v) {
  let extra = v.userId;
  let extra$1 = v.displayName;
  let extra$2 = v.avatarUrl;
  return Object.fromEntries(Spice.filterOptional([
    [
      "user_id",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "username",
      Spice.stringToJson(v.username)
    ],
    [
      "display_name",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "avatar_url",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ]
  ]));
}

function t_encodeJson$4(v) {
  let extra = v.userId;
  let extra$1 = v.displayName;
  let extra$2 = v.avatarUrl;
  return Object.fromEntries(Spice.filterOptional([
    [
      "user_id",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "username",
      Spice.stringToJson(v.username)
    ],
    [
      "display_name",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "avatar_url",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ]
  ]));
}

function t_decode$4(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let userId = Stdlib_Option.getOr(Stdlib_Option.map(v["user_id"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
    TAG: "Ok",
    _0: undefined
  });
  if (userId.TAG === "Ok") {
    let username = Stdlib_Option.getOr(Stdlib_Option.map(v["username"], Spice.stringFromJson), Spice.error(undefined, "username" + " missing", v));
    if (username.TAG === "Ok") {
      let displayName = Stdlib_Option.getOr(Stdlib_Option.map(v["display_name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (displayName.TAG === "Ok") {
        let avatarUrl = Stdlib_Option.getOr(Stdlib_Option.map(v["avatar_url"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (avatarUrl.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              userId: userId._0,
              username: username._0,
              displayName: displayName._0,
              avatarUrl: avatarUrl._0
            }
          };
        }
        let e = avatarUrl._0;
        return Spice.error("." + ("avatar_url" + e.path), e.message, e.value);
      }
      let e$1 = displayName._0;
      return Spice.error("." + ("display_name" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = username._0;
    return Spice.error("." + ("username" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = userId._0;
  return Spice.error("." + ("user_id" + e$3.path), e$3.message, e$3.value);
}

let XAccount = {
  t_encode: t_encode$3,
  t_encodeJson: t_encodeJson$4,
  t_decode: t_decode$4
};

function t_encode$4(v) {
  let extra = v.name;
  let extra$1 = v.givenName;
  let extra$2 = v.familyName;
  let extra$3 = v.avatarUrl;
  return Object.fromEntries(Spice.filterOptional([
    [
      "email",
      Spice.stringToJson(v.email)
    ],
    [
      "name",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "given_name",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "family_name",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ],
    [
      "avatar_url",
      Spice.optionToJson(Spice.stringToJson, extra$3)
    ]
  ]));
}

function t_encodeJson$5(v) {
  let extra = v.name;
  let extra$1 = v.givenName;
  let extra$2 = v.familyName;
  let extra$3 = v.avatarUrl;
  return Object.fromEntries(Spice.filterOptional([
    [
      "email",
      Spice.stringToJson(v.email)
    ],
    [
      "name",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "given_name",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "family_name",
      Spice.optionToJson(Spice.stringToJson, extra$2)
    ],
    [
      "avatar_url",
      Spice.optionToJson(Spice.stringToJson, extra$3)
    ]
  ]));
}

function t_decode$5(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let email = Stdlib_Option.getOr(Stdlib_Option.map(v["email"], Spice.stringFromJson), Spice.error(undefined, "email" + " missing", v));
  if (email.TAG === "Ok") {
    let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
      TAG: "Ok",
      _0: undefined
    });
    if (name.TAG === "Ok") {
      let givenName = Stdlib_Option.getOr(Stdlib_Option.map(v["given_name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (givenName.TAG === "Ok") {
        let familyName = Stdlib_Option.getOr(Stdlib_Option.map(v["family_name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (familyName.TAG === "Ok") {
          let avatarUrl = Stdlib_Option.getOr(Stdlib_Option.map(v["avatar_url"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
            TAG: "Ok",
            _0: undefined
          });
          if (avatarUrl.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                email: email._0,
                name: name._0,
                givenName: givenName._0,
                familyName: familyName._0,
                avatarUrl: avatarUrl._0
              }
            };
          }
          let e = avatarUrl._0;
          return Spice.error("." + ("avatar_url" + e.path), e.message, e.value);
        }
        let e$1 = familyName._0;
        return Spice.error("." + ("family_name" + e$1.path), e$1.message, e$1.value);
      }
      let e$2 = givenName._0;
      return Spice.error("." + ("given_name" + e$2.path), e$2.message, e$2.value);
    }
    let e$3 = name._0;
    return Spice.error("." + ("name" + e$3.path), e$3.message, e$3.value);
  }
  let e$4 = email._0;
  return Spice.error("." + ("email" + e$4.path), e$4.message, e$4.value);
}

let GoogleAccount = {
  t_encode: t_encode$4,
  t_encodeJson: t_encodeJson$5,
  t_decode: t_decode$5
};

let Identity = {};

let User = {};

let Session = {};

let SignedLogin = {};

let PrivyEmbeddedWallet = {};

export {
  Method,
  ChainType,
  PrivyEmbeddedWallet,
  PrivyData,
  XAccount,
  GoogleAccount,
  Identity,
  User,
  Session,
  SignedLogin,
}
/* No side effect */
