// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.mjs";
import * as Client from "../Client.res.mjs";
import * as Auth__Raw from "./Auth__Raw.res.mjs";
import * as Kit from "@solana/kit";
import * as Auth__Native from "./Auth__Native.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

async function getNonce(client) {
  return Stdlib_Result.map(await Http.get(client.http, "/api/auth/nonce", undefined, undefined, undefined, Auth__Raw.Nonce.t_decode), response => response.nonce);
}

async function loginWithMessage(client, signed, useEmbeddedWallet) {
  return await Http.post(client.http, "/api/auth/login_or_register_with_message", Auth__Raw.SignedLogin.toJson(signed, useEmbeddedWallet), undefined, undefined, Auth__Raw.decodeSession);
}

async function login(client, useEmbeddedWallet) {
  let address = Client.signerAddress(client);
  if (address === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no signing strategy configured; call Client.useNativeSigner or Client.useExternalSigner first"
      }
    };
  }
  let error = await getNonce(client);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let message = Auth__Native.signinMessage(error._0);
  let messageBytes = Kit.getUtf8Encoder().encode(message);
  let error$1 = await Client.signMessageBytes(client, messageBytes);
  if (error$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error$1._0
    };
  }
  let signed = Auth__Native.signedLogin(message, error$1._0, Primitive_option.valFromOption(address));
  return await loginWithMessage(client, signed, useEmbeddedWallet);
}

async function registerPrivy(client) {
  return await Http.post(client.http, "/api/auth/register-privy", {}, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
}

async function disconnectX(client) {
  return await Http.post(client.http, "/api/auth/disconnect_x", {}, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
}

function connectXUrl(client) {
  return Http.baseUrl(client.http) + `/api/auth/oauth/link/x`;
}

async function checkSession(client, cookieHeader) {
  return await Http.get(client.http, "/api/auth/me", undefined, undefined, cookieHeader, Auth__Raw.decodeSession);
}

function isAuthenticated(client) {
  return Stdlib_Option.isSome(Client.authToken(client));
}

async function logout(client) {
  let result = await Http.post(client.http, "/api/auth/logout", {}, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
  Client.clearAuth(client);
  return result;
}

export {
  getNonce,
  loginWithMessage,
  login,
  checkSession,
  isAuthenticated,
  logout,
  registerPrivy,
  disconnectX,
  connectXUrl,
}
/* Http Not a pure module */
