// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Auth__Model from "./Auth__Model.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function t_encode(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "nonce",
      Spice.stringToJson(v.nonce)
    ]]));
}

function t_encodeJson(v) {
  return Object.fromEntries(Spice.filterOptional([[
      "nonce",
      Spice.stringToJson(v.nonce)
    ]]));
}

function t_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let nonce = Stdlib_Option.getOr(Stdlib_Option.map(v["nonce"], Spice.stringFromJson), Spice.error(undefined, "nonce" + " missing", v));
  if (nonce.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        nonce: nonce._0
      }
    };
  }
  let e = nonce._0;
  return Spice.error("." + ("nonce" + e.path), e.message, e.value);
}

let Nonce = {
  t_encode: t_encode,
  t_encodeJson: t_encodeJson,
  t_decode: t_decode
};

function decodeIdentity(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "identity is not an object", json);
  }
  let match = json["type"];
  if (match === undefined) {
    return Spice.error(undefined, "unknown identity type", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "unknown identity type", json);
  }
  switch (match) {
    case "google" :
      let match$1 = json["account"];
      let match$2 = json["privy"];
      if (match$1 === undefined) {
        return Spice.error(undefined, "google identity missing account/privy", json);
      }
      if (match$2 === undefined) {
        return Spice.error(undefined, "google identity missing account/privy", json);
      }
      let match$3 = Auth__Model.GoogleAccount.t_decode(match$1);
      let match$4 = Auth__Model.PrivyData.t_decode(match$2);
      if (match$3.TAG === "Ok") {
        if (match$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Google",
              account: match$3._0,
              privy: match$4._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: match$4._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$3._0
        };
      }
    case "wallet" :
      let match$5 = json["address"];
      let match$6 = json["chain"];
      if (match$5 === undefined) {
        return Spice.error(undefined, "wallet identity missing address/chain", json);
      }
      if (typeof match$5 !== "string") {
        return Spice.error(undefined, "wallet identity missing address/chain", json);
      }
      if (match$6 === undefined) {
        return Spice.error(undefined, "wallet identity missing address/chain", json);
      }
      let chain = Auth__Model.ChainType.t_decode(match$6);
      if (chain.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: chain._0
        };
      }
      let privy = Stdlib_Option.flatMap(json["privy"], json => Stdlib_Result.mapOr(Auth__Model.PrivyData.t_decode(json), undefined, value => value));
      return {
        TAG: "Ok",
        _0: {
          TAG: "Wallet",
          address: match$5,
          chain: chain._0,
          privy: privy
        }
      };
    case "x" :
      let match$7 = json["account"];
      let match$8 = json["privy"];
      if (match$7 === undefined) {
        return Spice.error(undefined, "x identity missing account/privy", json);
      }
      if (match$8 === undefined) {
        return Spice.error(undefined, "x identity missing account/privy", json);
      }
      let match$9 = Auth__Model.XAccount.t_decode(match$7);
      let match$10 = Auth__Model.PrivyData.t_decode(match$8);
      if (match$9.TAG === "Ok") {
        if (match$10.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "X",
              account: match$9._0,
              privy: match$10._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: match$10._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$9._0
        };
      }
    default:
      return Spice.error(undefined, "unknown identity type", json);
  }
}

function decodeUser(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "user is not an object", json);
  }
  let match = json["user_id"];
  let match$1 = json["identity"];
  if (match === undefined) {
    return Spice.error(undefined, "user missing user_id/identity", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "user missing user_id/identity", json);
  }
  if (match$1 === undefined) {
    return Spice.error(undefined, "user missing user_id/identity", json);
  }
  let identity = decodeIdentity(match$1);
  if (identity.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: identity._0
    };
  }
  let connectedX = Stdlib_Option.flatMap(json["connected_x"], json => Stdlib_Result.mapOr(Auth__Model.XAccount.t_decode(json), undefined, value => value));
  return {
    TAG: "Ok",
    _0: {
      userId: match,
      identity: identity._0,
      connectedX: connectedX
    }
  };
}

function decodeSession(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "session response is not an object", json);
  }
  let match = json["user"];
  let match$1 = json["expires_at"];
  let match$2 = json["auth_method"];
  let match$3 = json["is_beta"];
  if (match === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (match$1 === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (typeof match$1 !== "number") {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (match$2 === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (match$3 === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (typeof match$3 !== "boolean") {
    return Spice.error(undefined, "session response missing fields", json);
  }
  let match$4 = decodeUser(match);
  let match$5 = Auth__Model.Method.t_decode(match$2);
  if (match$4.TAG === "Ok") {
    if (match$5.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          user: match$4._0,
          expiresAt: match$1,
          authMethod: match$5._0,
          isBeta: match$3
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: match$5._0
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: match$4._0
    };
  }
}

function toJson(signed, useEmbeddedWallet) {
  let fields = [
    [
      "message",
      signed.message
    ],
    [
      "signature_bs58",
      signed.signatureBs58
    ],
    [
      "pubkey_bytes",
      signed.pubkeyBytes.map(byte => (byte))
    ]
  ];
  Stdlib_Option.forEach(useEmbeddedWallet, value => {
    fields.push([
      "use_embedded_wallet",
      value
    ]);
  });
  return Object.fromEntries(fields);
}

let SignedLogin = {
  toJson: toJson
};

export {
  Nonce,
  decodeSession,
  SignedLogin,
}
/* No side effect */
