// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kit from "@solana/kit";
import * as Token from "@solana-program/token";

async function _quickStart() {
  let seeds_owner = Kit.address("So11111111111111111111111111111111111111112");
  let seeds_mint = Kit.address("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");
  let seeds = {
    owner: seeds_owner,
    tokenProgram: Token.TOKEN_PROGRAM_ADDRESS,
    mint: seeds_mint
  };
  await Token.findAssociatedTokenPda(seeds);
}

let _tokenProgram = Token.TOKEN_PROGRAM_ADDRESS;

let _ataProgram = Token.ASSOCIATED_TOKEN_PROGRAM_ADDRESS;

let _seeds_owner = Kit.address("So11111111111111111111111111111111111111112");

let _seeds_mint = Kit.address("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");

let _seeds = {
  owner: _seeds_owner,
  tokenProgram: Token.TOKEN_PROGRAM_ADDRESS,
  mint: _seeds_mint
};

export {
  _quickStart,
  _tokenProgram,
  _ataProgram,
  _seeds,
}
/* _tokenProgram Not a pure module */
