"""WebSocket client protocol (interface)."""

from typing import Any, Callable, Optional, Protocol

from . import ReadyState


class IWsClient(Protocol):
    """WebSocket client interface."""

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def send(self, message: dict) -> None: ...
    async def subscribe(self, params: dict) -> None: ...
    async def unsubscribe(self, params: dict) -> None: ...
    def is_connected(self) -> bool: ...
    def ready_state(self) -> ReadyState: ...
    def on(self, callback: Callable) -> Callable[[], None]: ...


__all__ = ["IWsClient"]
