// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "../src/Client.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Kit from "@solana/kit";
import * as Auth__Client from "../src/auth/Auth__Client.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Order__Client from "../src/domain/order/Order__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  let secretKey = Common__Example.walletSecretKey();
  await Client.useNativeSigner(client, secretKey);
  let keypair = await Kit.createKeyPairFromBytes(secretKey);
  let maker = await Kit.getAddressFromPublicKey(keypair.publicKey);
  let error = await Auth__Client.login(client, undefined);
  if (error.TAG === "Ok") {
    let error$1 = await Order__Client.getUserOrders(client, 50, undefined, undefined);
    if (error$1.TAG === "Ok") {
      let firstLimit = Stdlib_Array.findMap(error$1._0.orders, order => {
        if (order.TAG === "Limit") {
          return order._0;
        }
      });
      if (firstLimit !== undefined) {
        let body = await Order__Client.cancelBodySigned(firstLimit.common.orderHash, maker, keypair);
        let cancelled = await Order__Client.cancel(client, body);
        if (cancelled.TAG === "Ok") {
          let cancelled$1 = cancelled._0;
          console.log(`cancelled: ` + cancelled$1.orderHash + ` remaining=` + cancelled$1.remaining);
          return;
        }
        console.error(SdkError.toMessage(cancelled._0));
        return;
      }
      console.log("No open limit orders to cancel.");
      return;
    }
    console.error(SdkError.toMessage(error$1._0));
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
