// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "../src/Auth.res.mjs";
import * as Client from "../src/Client.res.mjs";
import * as Position from "../src/domain/Position.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

async function main() {
  let client = Common__Example.client();
  await Client.useNativeSigner(client, Common__Example.walletSecretKey());
  let error = await Auth.login(client, undefined);
  if (error.TAG === "Ok") {
    let balances = await Position.depositTokenBalances(client, undefined);
    if (balances.TAG === "Ok") {
      let entries = Object.values(balances._0);
      console.log(`tracked balances: ` + entries.length.toString());
      entries.toSorted((a, b) => Primitive_string.compare(a.symbol, b.symbol)).forEach(balance => {
        console.log(`  ` + balance.symbol + `  ` + balance.mint + `  idle=` + balance.idle);
      });
      let error$1 = await Auth.logout(client);
      if (error$1.TAG === "Ok") {
        return;
      }
      console.error(SdkError.toMessage(error$1._0));
      return;
    }
    console.error(SdkError.toMessage(balances._0));
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
