// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Faucet from "../src/domain/Faucet.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Kit from "@solana/kit";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  let keypair = await Kit.createKeyPairFromBytes(Common__Example.walletSecretKey());
  let wallet = await Kit.getAddressFromPublicKey(keypair.publicKey);
  let result = await Faucet.claim(client, wallet);
  if (result.TAG === "Ok") {
    let result$1 = result._0;
    console.log(`claim tx: ` + result$1.signature);
    console.log(`sol: ` + result$1.sol.toString());
    result$1.tokens.forEach(token => {
      console.log(`  - ` + token.symbol + `: ` + token.amount.toString());
    });
    return;
  }
  console.error(SdkError.toMessage(result._0));
}

main();

export {
  main,
}
/*  Not a pure module */
