// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "../src/Client.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Auth__Client from "../src/auth/Auth__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  await Client.useNativeSigner(client, Common__Example.walletSecretKey());
  let session = await Auth__Client.login(client, undefined);
  if (session.TAG === "Ok") {
    let session$1 = session._0;
    console.log(`Logged in as user ` + session$1.user.userId);
    let match = session$1.authMethod;
    let method;
    method = match === "privy" ? "privy" : "lightcone";
    console.log(`Auth method: ` + method + `, beta: ` + (
      session$1.isBeta ? "yes" : "no"
    ));
    return;
  }
  console.error(SdkError.toMessage(session._0));
}

main();

export {
  main,
}
/*  Not a pure module */
