// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SdkError from "../src/SdkError.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Market__Client from "../src/domain/market/Market__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  let error = await Market__Client.get(client, undefined, 1);
  if (error.TAG === "Ok") {
    let market = error._0.markets[0];
    if (market !== undefined) {
      let error$1 = await Market__Client.getDepositMints(client, market.pubkey);
      if (error$1.TAG === "Ok") {
        let response = error$1._0;
        console.log(`market ` + market.slug + ` (` + response.marketPubkey + `): ` + response.total.toString() + ` deposit assets`);
        response.depositAssets.forEach(asset => {
          console.log(`  - ` + Stdlib_Option.getOr(asset.symbol, "?") + ` (` + asset.depositAsset + `) — ` + asset.conditionalMints.length.toString() + ` conditional mints`);
        });
        return;
      }
      console.error(SdkError.toMessage(error$1._0));
      return;
    }
    console.log("no markets found");
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
