// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SdkError from "../src/SdkError.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Market__Client from "../src/domain/market/Market__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";
import * as Orderbook__Model from "../src/domain/orderbook/Orderbook__Model.res.mjs";
import * as Orderbook__Client from "../src/domain/orderbook/Orderbook__Client.res.mjs";

async function main() {
  let client = Common__Example.client();
  let error = await Market__Client.get(client, undefined, 1);
  if (error.TAG === "Ok") {
    let market = error._0.markets[0];
    if (market !== undefined) {
      let pair = market.orderbookPairs[0];
      if (pair !== undefined) {
        let orderbookId = pair.orderbookId;
        let error$1 = await Orderbook__Client.get(client, orderbookId, 10, undefined, undefined);
        if (error$1.TAG === "Ok") {
          let depth = error$1._0;
          console.log(`market: ` + market.slug);
          console.log(`orderbook: ` + orderbookId);
          console.log(`best bid: ` + Stdlib_Option.getOr(depth.bestBid, "—") + `, best ask: ` + Stdlib_Option.getOr(depth.bestAsk, "—"));
          console.log(`levels: ` + depth.bids.length.toString() + ` bids / ` + depth.asks.length.toString() + ` asks`);
          console.log(`token decimals: base=` + pair.base.decimals.toString() + `, quote=` + pair.quote.decimals.toString());
          let depthDecimals = depth.decimals;
          if (depthDecimals !== undefined) {
            console.log(`depth decimals: price=` + depthDecimals.price.toString() + `, size=` + depthDecimals.size.toString());
          }
          let message = Orderbook__Model.Aggregation.validate(5, 2);
          if (message.TAG === "Ok") {
            let aggregation = message._0;
            let error$2 = await Orderbook__Client.get(client, orderbookId, undefined, aggregation, undefined);
            if (error$2.TAG === "Ok") {
              let grouped = error$2._0;
              console.log(`grouped (` + Orderbook__Model.Aggregation.keySuffix(aggregation) + `): ` + grouped.bids.length.toString() + ` bids / ` + grouped.asks.length.toString() + ` asks`);
              return;
            }
            console.error(SdkError.toMessage(error$2._0));
            return;
          }
          console.error(message._0);
          return;
        }
        console.error(SdkError.toMessage(error$1._0));
        return;
      }
      console.log("market has no orderbooks");
      return;
    }
    console.log("no markets found");
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
