// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "../src/Auth.res.mjs";
import * as Client from "../src/Client.res.mjs";
import * as Market from "../src/domain/Market.res.mjs";
import * as Position from "../src/domain/Position.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  await Client.useNativeSigner(client, Common__Example.walletSecretKey());
  let error = await Auth.login(client, undefined);
  if (error.TAG === "Ok") {
    let match = error._0.user.identity;
    let wallet;
    switch (match.TAG) {
      case "Google" :
      case "X" :
        wallet = match.privy.wallet.address;
        break;
      case "Wallet" :
        wallet = match.address;
        break;
    }
    let error$1 = await Market.get(client, undefined, 1);
    if (error$1.TAG === "Ok") {
      let market = error$1._0.markets[0];
      if (market !== undefined) {
        let error$2 = await Position.get(client, wallet);
        if (error$2.TAG === "Ok") {
          let error$3 = await Position.getForMarket(client, wallet, market.pubkey);
          if (error$3.TAG === "Ok") {
            console.log(`wallet: ` + wallet);
            console.log(`markets with positions: ` + error$2._0.totalMarkets.toString());
            console.log(`positions in ` + market.slug + `: ` + error$3._0.positions.length.toString());
            return;
          }
          console.error(SdkError.toMessage(error$3._0));
          return;
        }
        console.error(SdkError.toMessage(error$2._0));
        return;
      }
      console.log("no markets found");
      return;
    }
    console.error(SdkError.toMessage(error$1._0));
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
