// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Market from "../src/domain/Market.res.mjs";
import * as Shared from "../src/Shared.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as PriceHistory from "../src/domain/PriceHistory.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  let error = await Market.get(client, undefined, 1);
  if (error.TAG === "Ok") {
    let market = error._0.markets[0];
    if (market !== undefined) {
      let pair = market.orderbookPairs[0];
      if (pair !== undefined) {
        let toMs = Date.now();
        let fromMs = toMs - 7.0 * 24.0 * 60.0 * 60.0 * 1000.0;
        let error$1 = await PriceHistory.get(client, pair.orderbookId, "1h", fromMs, toMs);
        if (error$1.TAG === "Ok") {
          let history = error$1._0;
          console.log(`market: ` + market.slug);
          console.log(`orderbook: ` + history.orderbookId);
          console.log(Shared.Resolution.toString(history.resolution) + ` candles: ` + history.prices.length.toString() + ` (has_more=` + (
            history.hasMore ? "true" : "false"
          ) + `)`);
          console.log(`decimals: price=` + history.decimals.price.toString() + `, volume=` + history.decimals.volume.toString());
          history.prices.slice(0, 5).forEach(candle => {
            console.log(`  t=` + candle.t.toString() + ` mid=` + Stdlib_Option.getOr(candle.m, "—"));
          });
          return;
        }
        console.error(SdkError.toMessage(error$1._0));
        return;
      }
      console.log("market has no orderbooks");
      return;
    }
    console.log("no markets found");
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
