// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ws from "../src/ws/Ws.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Market__Client from "../src/domain/market/Market__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";
import * as PriceHistory__Client from "../src/domain/priceHistory/PriceHistory__Client.res.mjs";

let delay = ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));

async function main() {
  let client = Common__Example.client();
  let error = await Market__Client.get(client, undefined, 1);
  if (error.TAG === "Ok") {
    let pair = Stdlib_Option.flatMap(error._0.markets[0], market => market.orderbookPairs[0]);
    if (pair !== undefined) {
      let orderbookId = pair.orderbookId;
      let error$1 = await PriceHistory__Client.getLineData(client, orderbookId, "5m", undefined, undefined, undefined, 1000.0);
      if (error$1.TAG === "Ok") {
        console.log("=== REST API ===");
        console.log(`  points: ` + error$1._0.length.toString());
      } else {
        console.error(SdkError.toMessage(error$1._0));
      }
      let wsFrames = {
        contents: 0
      };
      let connection = Ws.connect(client.wsUrl, message => {
        let match = message.kind;
        if (typeof match !== "object" || match.TAG !== "PriceHistory") {
          return;
        } else {
          wsFrames.contents = wsFrames.contents + 1 | 0;
          return;
        }
      }, undefined, undefined, undefined, undefined, undefined);
      Ws.subscribe(connection, {
        TAG: "PriceHistory",
        _0: {
          orderbookId: orderbookId,
          resolution: "5m",
          includeOhlcv: false
        }
      });
      await delay(5000);
      console.log("=== WebSocket ===");
      console.log(`  price_history frames: ` + wsFrames.contents.toString());
      return Ws.disconnect(connection);
    }
    console.log("no orderbook found");
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  delay,
  main,
}
/*  Not a pure module */
