// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rpc from "../src/Rpc.res.mjs";
import * as Client from "../src/Client.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let deadPrimary = "https://dead-primary.invalid";

let backupRpc = "https://api.devnet.solana.com";

async function main() {
  let client = Client.make(undefined, undefined, undefined, deadPrimary, backupRpc, undefined, undefined, undefined);
  console.log(`primary : ` + client.rpcUrl);
  console.log(`backup  : ` + Stdlib_Option.getOr(client.backupRpcUrl, "(none)"));
  let blockhash = await Rpc.getLatestBlockhash(client);
  if (blockhash.TAG === "Ok") {
    console.log(`blockhash: ` + blockhash._0);
    return;
  }
  console.error(`(expected until failover lands) ` + SdkError.toMessage(blockhash._0));
}

main();

export {
  deadPrimary,
  backupRpc,
  main,
}
/*  Not a pure module */
