// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "../src/Client.res.mjs";
import * as Envelope from "../src/program/Envelope.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import DecimalJs from "decimal.js";
import * as Kit from "@solana/kit";
import * as Auth__Client from "../src/auth/Auth__Client.res.mjs";
import * as Order__Client from "../src/domain/order/Order__Client.res.mjs";
import * as Stdlib_BigInt from "@rescript/runtime/lib/es6/Stdlib_BigInt.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Market__Client from "../src/domain/market/Market__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";
import * as Position__Client from "../src/domain/position/Position__Client.res.mjs";
import * as Position__Builders from "../src/domain/position/Position__Builders.res.mjs";

let delay = ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));

async function waitForGlobalBalance(client, mint, minimum) {
  let target = new DecimalJs(minimum);
  console.log(`waiting for global balance: mint=` + mint + ` required=` + minimum);
  let attempt = async n => {
    let error = await Position__Client.depositTokenBalances(client, undefined);
    if (error.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: SdkError.toMessage(error._0)
      };
    }
    let balance = error._0[mint];
    let idle = balance !== undefined ? balance.idle : "0";
    if (new DecimalJs(idle).gte(target)) {
      console.log(`global balance ready: idle=` + idle + ` (attempt ` + n.toString() + `)`);
      return {
        TAG: "Ok",
        _0: undefined
      };
    } else if (n >= 15) {
      return {
        TAG: "Error",
        _0: `global balance for ` + mint + ` did not reach ` + minimum + ` within 30s`
      };
    } else {
      console.log(`global balance not ready: idle=` + idle + `/` + minimum + ` (attempt ` + n.toString() + `)`);
      await delay(2000);
      return await attempt(n + 1 | 0);
    }
  };
  return await attempt(1);
}

async function submitOrder(client, pair, maker, keypair) {
  let baseDecimals = pair.base.decimals | 0;
  let quoteDecimals = pair.quote.decimals | 0;
  let priceDecimals = (6 + quoteDecimals | 0) - baseDecimals | 0;
  let decimals_priceDecimals = priceDecimals > 0 ? priceDecimals : 0;
  let decimals_tickSize = pair.tickSize > 0.0 ? pair.tickSize : 0.0;
  let decimals = {
    baseDecimals: baseDecimals,
    quoteDecimals: quoteDecimals,
    priceDecimals: decimals_priceDecimals,
    tickSize: decimals_tickSize
  };
  let value = await Order__Client.getNonce(client, maker);
  let nonce;
  nonce = value.TAG === "Ok" ? Stdlib_Option.getOr(Stdlib_BigInt.fromFloat(value._0), 0n) : 0n;
  let response = await Envelope.submitLimitOrder(client, maker, Kit.address(pair.marketPubkey), Kit.address(pair.base.mint), Kit.address(pair.quote.mint), 0, "0.55", "2", decimals, pair.orderbookId, keypair, nonce, undefined, undefined, undefined, undefined);
  if (response.TAG === "Ok") {
    let response$1 = response._0;
    let match = response$1.status;
    let status;
    switch (match) {
      case "accepted" :
        status = "accepted";
        break;
      case "partial_fill" :
        status = "partial_fill";
        break;
      case "filled" :
        status = "filled";
        break;
    }
    console.log(`submitted: ` + response$1.orderHash + ` status=` + status + ` filled=` + response$1.filled + ` remaining=` + response$1.remaining + ` fills=` + response$1.fills.length.toString());
    return;
  }
  console.error(SdkError.toMessage(response._0));
}

async function main() {
  let client = Common__Example.client();
  let secretKey = Common__Example.walletSecretKey();
  await Client.useNativeSigner(client, secretKey);
  let keypair = await Kit.createKeyPairFromBytes(secretKey);
  let maker = await Kit.getAddressFromPublicKey(keypair.publicKey);
  let error = await Auth__Client.login(client, undefined);
  if (error.TAG === "Ok") {
    let error$1 = await Market__Client.get(client, undefined, 1);
    if (error$1.TAG === "Ok") {
      let market = error$1._0.markets[0];
      if (market !== undefined) {
        let pair = Stdlib_Option.orElse(market.orderbookPairs.find(pair => pair.active), market.orderbookPairs[0]);
        if (pair !== undefined) {
          let mintAddress = Kit.address(pair.quote.depositAsset);
          let error$2 = await Position__Builders.depositToGlobal(client, maker, mintAddress, 1100000n);
          if (error$2.TAG === "Ok") {
            console.log(`deposit_to_global: confirmed ` + error$2._0);
            let message = await waitForGlobalBalance(client, pair.quote.depositAsset, "1.1");
            if (message.TAG === "Ok") {
              return await submitOrder(client, pair, maker, keypair);
            }
            console.error(message._0);
            return;
          }
          console.error(`deposit_to_global: ` + SdkError.toMessage(error$2._0));
          return;
        }
        console.log("selected market has no orderbooks");
        return;
      }
      console.log("no markets found");
      return;
    }
    console.error(SdkError.toMessage(error$1._0));
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

let orderQuoteAmount = 1100000n;

export {
  orderQuoteAmount,
  delay,
  waitForGlobalBalance,
  submitOrder,
  main,
}
/*  Not a pure module */
