// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Auth from "../src/Auth.res.mjs";
import * as Order from "../src/domain/Order.res.mjs";
import * as Client from "../src/Client.res.mjs";
import * as Shared from "../src/Shared.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Common__Example from "./Common__Example.res.mjs";

async function main() {
  let client = Common__Example.client();
  await Client.useNativeSigner(client, Common__Example.walletSecretKey());
  let error = await Auth.login(client, undefined);
  if (error.TAG === "Ok") {
    let snapshot = await Order.getUserOrders(client, 10, undefined, undefined);
    if (snapshot.TAG === "Ok") {
      let snapshot$1 = snapshot._0;
      let match = Stdlib_Array.reduce(snapshot$1.orders, [
        0,
        0
      ], (param, order) => {
        let triggers = param[1];
        let limits = param[0];
        if (order.TAG === "Limit") {
          return [
            limits + 1 | 0,
            triggers
          ];
        } else {
          return [
            limits,
            triggers + 1 | 0
          ];
        }
      });
      console.log(`orders: ` + match[0].toString() + ` limit / ` + match[1].toString() + ` trigger`);
      console.log(`market balances: ` + snapshot$1.marketBalances.length.toString());
      console.log(`has more: ` + (
        snapshot$1.hasMore ? "yes" : "no"
      ));
      let match$1 = snapshot$1.orders[0];
      if (match$1 !== undefined) {
        if (match$1.TAG === "Limit") {
          let order = match$1._0;
          console.log(`first limit: ` + order.common.orderHash + ` ` + Shared.Side.toString(order.common.side) + ` @ ` + order.common.price);
        } else {
          let order$1 = match$1._0;
          console.log(`first trigger: ` + order$1.triggerOrderId + ` ` + Shared.Side.toString(order$1.common.side) + ` ` + (`@ ` + order$1.common.price + ` (trigger ` + order$1.triggerPrice + `)`));
        }
      }
      let cursor = snapshot$1.nextCursor;
      if (cursor === undefined) {
        return;
      }
      let next = await Order.getUserOrders(client, 10, cursor, undefined);
      if (next.TAG === "Ok") {
        console.log(`next page: ` + next._0.orders.length.toString() + ` order(s)`);
        return;
      }
      console.error(SdkError.toMessage(next._0));
      return;
    }
    console.error(SdkError.toMessage(snapshot._0));
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
