// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "../src/Client.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as Auth__Client from "../src/auth/Auth__Client.res.mjs";
import * as Order__Client from "../src/domain/order/Order__Client.res.mjs";
import * as Common__Example from "./Common__Example.res.mjs";
import * as Position__Client from "../src/domain/position/Position__Client.res.mjs";

async function main() {
  let client = Common__Example.client();
  await Client.useNativeSigner(client, Common__Example.walletSecretKey());
  let error = await Auth__Client.login(client, undefined);
  if (error.TAG === "Ok") {
    let token = Client.authToken(client);
    if (token !== undefined) {
      Client.clearAuth(client);
      let cookieHeader = `lightcone-token=` + token;
      let balances = await Position__Client.depositTokenBalances(client, cookieHeader);
      if (balances.TAG === "Ok") {
        console.log(`tracked deposit balances: ` + Object.keys(balances._0).length.toString());
      } else {
        console.error(SdkError.toMessage(balances._0));
      }
      let orders = await Order__Client.getUserOrders(client, 50, undefined, cookieHeader);
      if (orders.TAG === "Ok") {
        console.log(`open orders: ` + orders._0.orders.length.toString());
        return;
      }
      console.error(SdkError.toMessage(orders._0));
      return;
    }
    console.error("auth token not set after login — the SDK should have captured it");
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  main,
}
/*  Not a pure module */
