// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ws from "../src/ws/Ws.res.mjs";
import * as Auth from "../src/Auth.res.mjs";
import * as Client from "../src/Client.res.mjs";
import * as Market from "../src/domain/Market.res.mjs";
import * as SdkError from "../src/SdkError.res.mjs";
import * as OrderState from "../src/domain/OrderState.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Common__Example from "./Common__Example.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let delay = ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));

async function main() {
  let client = Common__Example.client();
  await Client.useNativeSigner(client, Common__Example.walletSecretKey());
  let error = await Auth.login(client, undefined);
  if (error.TAG === "Ok") {
    let address = Client.signerAddress(client);
    if (address !== undefined) {
      let error$1 = await Market.get(client, undefined, 1);
      if (error$1.TAG === "Ok") {
        let market = error$1._0.markets[0];
        if (market !== undefined) {
          let marketPubkey = market.pubkey;
          let sawAuth = {
            contents: false
          };
          let sawUser = {
            contents: false
          };
          let sawMarket = {
            contents: false
          };
          let connection = Ws.connect(client.wsUrl, msg => {
            let update = msg.kind;
            if (typeof update !== "object") {
              return;
            }
            switch (update.TAG) {
              case "User" :
                let update$1 = update._0;
                sawUser.contents = true;
                let label;
                switch (update$1.TAG) {
                  case "Snapshot" :
                    let snapshot = update$1._0;
                    let match = OrderState.ofSnapshotOrders(snapshot.orders);
                    let orders = snapshot.orders.length.toString();
                    let triggers = OrderState.UserTriggerOrders.size(match[1]).toString();
                    let balances = snapshot.marketBalances.length.toString();
                    label = `snapshot: ` + orders + ` orders (` + triggers + ` trigger), ` + balances + ` market balances`;
                    break;
                  case "Order" :
                    let update$2 = update$1._0;
                    if (update$2.TAG === "Limit") {
                      let update$3 = update$2._0;
                      label = `limit order ` + update$3.order.orderHash + ` remaining=` + update$3.order.remaining;
                    } else {
                      let update$4 = update$2._0;
                      label = `trigger order ` + update$4.triggerOrderId + ` @ ` + update$4.triggerPrice;
                    }
                    break;
                  case "BalanceUpdate" :
                    label = `balance update for ` + update$1._0.marketPubkey;
                    break;
                  case "GlobalDepositUpdate" :
                    let deposit = update$1._0;
                    label = `global deposit ` + deposit.balance + ` (` + deposit.mint + `)`;
                    break;
                  case "NonceUpdate" :
                    label = `nonce → ` + update$1._0.newNonce.toString();
                    break;
                  case "NotificationPush" :
                    label = "notification";
                    break;
                }
                console.log(`user: ` + label);
                return;
              case "Market" :
                let event = update._0;
                sawMarket.contents = true;
                let label$1;
                switch (event.TAG) {
                  case "Settled" :
                    label$1 = `settled ` + event._0;
                    break;
                  case "Created" :
                    label$1 = `created ` + event._0;
                    break;
                  case "Opened" :
                    label$1 = `opened ` + event._0;
                    break;
                  case "Paused" :
                    label$1 = `paused ` + event._0;
                    break;
                  case "OrderbookCreated" :
                    label$1 = `orderbook ` + event._1 + ` created in ` + event._0;
                    break;
                }
                console.log(`market: ` + label$1);
                return;
              case "Auth" :
                let update$5 = update._0;
                sawAuth.contents = true;
                let label$2;
                label$2 = update$5.TAG === "Authenticated" ? `authenticated as ` + update$5._0 : `anonymous (` + Stdlib_Option.getOr(update$5._0, "no reason") + `)`;
                console.log(`auth: ` + label$2);
                return;
              default:
                return;
            }
          }, () => {
            console.log("connected — subscribing to user + market streams");
          }, undefined, error => {
            console.error(SdkError.toMessage(error));
          }, undefined, undefined);
          Ws.subscribe(connection, {
            TAG: "User",
            _0: Primitive_option.valFromOption(address)
          });
          Ws.subscribe(connection, {
            TAG: "Market",
            _0: marketPubkey
          });
          await delay(20000);
          Ws.disconnect(connection);
          if (!sawAuth.contents && !sawUser.contents) {
            console.log("received no websocket events — connection may be unreachable");
          }
          console.log(`market event received: ` + (
            sawMarket.contents ? "yes" : "no"
          ));
          return;
        }
        console.log("no markets found");
        return;
      }
      console.error(SdkError.toMessage(error$1._0));
      return;
    }
    console.log("no signer configured");
    return;
  }
  console.error(SdkError.toMessage(error._0));
}

main();

export {
  delay,
  main,
}
/*  Not a pure module */
