// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Decimal from "../Decimal.res.mjs";
import DecimalJs from "decimal.js";

function _quickStart() {
  new DecimalJs("1.5").times(new DecimalJs(2)).toFixed(1);
  new DecimalJs("0.1").plus(new DecimalJs("0.2")).toFixed(1);
}

function _fromString() {
  return new DecimalJs("1.5");
}

function _fromInt() {
  return new DecimalJs(42);
}

function _fromFloat() {
  return new DecimalJs(2.5);
}

function _arithmetic(left, right) {
  left.plus(right);
  left.minus(right);
  left.times(right);
  left.div(right);
  left.pow(right);
  left.pow(3);
}

function _rounding(value) {
  value.abs();
  value.floor();
  value.ceil();
  value.round();
  value.toSignificantDigits(2);
  value.toDecimalPlaces(2, Decimal.roundDown);
}

function _comparison(left, right) {
  left.cmp(right);
  left.eq(right);
  left.gt(right);
  left.gte(right);
  left.lt(right);
  left.lte(right);
  left.isZero();
  left.isNeg();
}

function _terminal(value) {
  value.toFixed(3);
  value.toString();
  value.toNumber();
}

let _roundDown = Decimal.roundDown;

export {
  _quickStart,
  _fromString,
  _fromInt,
  _fromFloat,
  _arithmetic,
  _rounding,
  _comparison,
  _terminal,
  _roundDown,
}
/* decimal.js Not a pure module */
