"""Constants for the Lightcone SDK."""

from solders.pubkey import Pubkey


# Program IDs
PROGRAM_ID = Pubkey.from_string("EfRvELrn4b5aJRwddD1VUrqzsfm1pewBLPebq3iMPDp2")
TOKEN_PROGRAM_ID = Pubkey.from_string("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
TOKEN_2022_PROGRAM_ID = Pubkey.from_string("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb")
ASSOCIATED_TOKEN_PROGRAM_ID = Pubkey.from_string(
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
)
SYSTEM_PROGRAM_ID = Pubkey.from_string("11111111111111111111111111111111")
RENT_SYSVAR_ID = Pubkey.from_string("SysvarRent111111111111111111111111111111111")
INSTRUCTIONS_SYSVAR_ID = Pubkey.from_string(
    "Sysvar1nstructions1111111111111111111111111"
)
ED25519_PROGRAM_ID = Pubkey.from_string("Ed25519SigVerify111111111111111111111111111")


# Account Discriminators (8 bytes each)
EXCHANGE_DISCRIMINATOR = b"exchange"
MARKET_DISCRIMINATOR = b"market\x00\x00"
ORDER_STATUS_DISCRIMINATOR = b"ordstat\x00"
USER_NONCE_DISCRIMINATOR = b"usrnonce"
POSITION_DISCRIMINATOR = b"position"


# PDA Seeds
SEED_CENTRAL_STATE = b"central_state"
SEED_MARKET = b"market"
SEED_VAULT = b"market_deposit_token_account"
SEED_MINT_AUTHORITY = b"market_mint_authority"
SEED_CONDITIONAL_MINT = b"conditional_mint"
SEED_ORDER_STATUS = b"order_status"
SEED_USER_NONCE = b"user_nonce"
SEED_POSITION = b"position"


# Account Sizes (in bytes)
EXCHANGE_SIZE = 88
MARKET_SIZE = 120
ORDER_STATUS_SIZE = 24
USER_NONCE_SIZE = 16
POSITION_SIZE = 80


# Order Sizes (in bytes)
FULL_ORDER_SIZE = 225
COMPACT_ORDER_SIZE = 65
SIGNATURE_SIZE = 64
ORDER_HASH_SIZE = 32


# Order Layout Offsets (for FullOrder)
ORDER_NONCE_OFFSET = 0
ORDER_MAKER_OFFSET = 8
ORDER_MARKET_OFFSET = 40
ORDER_BASE_MINT_OFFSET = 72
ORDER_QUOTE_MINT_OFFSET = 104
ORDER_SIDE_OFFSET = 136
ORDER_MAKER_AMOUNT_OFFSET = 137
ORDER_TAKER_AMOUNT_OFFSET = 145
ORDER_EXPIRATION_OFFSET = 153
ORDER_SIGNATURE_OFFSET = 161


# Instruction Discriminators
INSTRUCTION_INITIALIZE = 0
INSTRUCTION_CREATE_MARKET = 1
INSTRUCTION_ADD_DEPOSIT_MINT = 2
INSTRUCTION_MINT_COMPLETE_SET = 3
INSTRUCTION_MERGE_COMPLETE_SET = 4
INSTRUCTION_CANCEL_ORDER = 5
INSTRUCTION_INCREMENT_NONCE = 6
INSTRUCTION_SETTLE_MARKET = 7
INSTRUCTION_REDEEM_WINNINGS = 8
INSTRUCTION_SET_PAUSED = 9
INSTRUCTION_SET_OPERATOR = 10
INSTRUCTION_WITHDRAW_FROM_POSITION = 11
INSTRUCTION_ACTIVATE_MARKET = 12
INSTRUCTION_MATCH_ORDERS_MULTI = 13


# Limits
MAX_OUTCOMES = 6
MIN_OUTCOMES = 2
MAX_MAKERS = 5
MAX_OUTCOME_NAME_LEN = 32
MAX_OUTCOME_SYMBOL_LEN = 10
MAX_OUTCOME_URI_LEN = 200


# Special Values
NO_WINNING_OUTCOME = 255
