"""Lightcone SDK - Python SDK for the Lightcone protocol on Solana."""

__version__ = "0.3.21"

# ============================================================================
# Layer 1: Core
# ============================================================================

from .shared import (
    # Types
    OrderBookId,
    PubkeyStr,
    Side,
    TimeInForce,
    TriggerType,
    TriggerStatus,
    TriggerResultStatus,
    OrderUpdateType,
    TriggerUpdateType,
    DepositSource,
    Resolution,
    SubmitOrderRequest,
    SubmitTriggerOrderRequest,
    abbr_number,
    display,
    display_decimal,
    display_formatted_string,
    display_with_decimals,
    # Price
    parse_decimal,
    format_decimal,
    is_zero,
    from_decimal_value,
    # Scaling
    OrderbookDecimals,
    ScaledAmounts,
    ScalingError,
    scale_price_size,
    # Utils
    derive_orderbook_id,
    to_base_units,
    to_decimal_value,
)

from .error import (
    SdkError,
    DeserializationError,
    HttpError,
    HttpErrorKind,
    WsError,
    WsErrorKind,
    AuthError,
    AuthErrorKind,
)

from .network import DEFAULT_API_URL, DEFAULT_WS_URL

# ============================================================================
# Layer 2: Auth + Privy
# ============================================================================

from .auth import (
    User,
    AuthCredentials,
    LinkedAccount,
    EmbeddedWallet,
    LinkedAccountType,
    ChainType,
    LoginRequest,
    LoginResponse,
    MeResponse,
    NonceResponse,
    generate_signin_message,
)

from .auth.client import Auth, sign_login_message

from .privy import (
    PrivyOrderEnvelope,
    SignAndSendTxRequest,
    SignAndSendTxResponse,
    SignAndSendOrderRequest,
    SignAndCancelOrderRequest,
    SignAndCancelAllRequest,
    ExportWalletRequest,
    ExportWalletResponse,
    privy_order_from_limit_envelope,
    privy_order_from_trigger_envelope,
)

from .privy.client import Privy

# ============================================================================
# Layer 3: HTTP
# ============================================================================

from .http import (
    LightconeHttp,
    RetryPolicy,
    RetryConfig,
    DEFAULT_RETRY_CONFIG,
    delay_for_attempt,
)

# ============================================================================
# Layer 4: WebSocket
# ============================================================================

from .ws import (
    WsConfig,
    WS_DEFAULT_CONFIG,
    WsEvent,
    WsEventType,
    MessageIn,
    MessageInType,
    ReadyState,
    WsErrorData,
    ping,
    subscribe_books,
    unsubscribe_books,
    subscribe_trades,
    unsubscribe_trades,
    subscribe_user,
    unsubscribe_user,
    subscribe_price_history,
    unsubscribe_price_history,
    subscribe_ticker,
    unsubscribe_ticker,
    subscribe_market,
    unsubscribe_market,
    subscribe_deposit_price,
    unsubscribe_deposit_price,
    parse_message_in,
)

from .ws.client import WsClient

# ============================================================================
# Layer 5: Client
# ============================================================================

from .client import LightconeClient, LightconeClientBuilder

# ============================================================================
# Program layer (on-chain interaction)
# ============================================================================

from .program import (
    # Client
    LightconePinocchioClient,
    # Types - Enums
    MarketStatus,
    OrderSide,
    # Types - Account Data
    Exchange,
    Market,
    Position,
    OrderStatus,
    UserNonce,
    Orderbook,
    GlobalDepositToken,
    # Types - Orders
    SignedOrder,
    FullOrder,
    Order,
    CompactOrder,
    OutcomeMetadata,
    MakerFill,
    # Types - Params
    InitializeParams,
    CreateMarketParams,
    AddDepositMintParams,
    MintCompleteSetParams,
    MergeCompleteSetParams,
    SettleMarketParams,
    RedeemWinningsParams,
    WithdrawFromPositionParams,
    ActivateMarketParams,
    MatchOrdersMultiParams,
    CreateOrderbookParams,
    SetAuthorityParams,
    BidOrderParams,
    AskOrderParams,
    BuildResult,
    WhitelistDepositTokenParams,
    DepositToGlobalParams,
    GlobalToMarketDepositParams,
    InitPositionTokensParams,
    DepositAndSwapParams,
    ExtendPositionTokensParams,
    # Constants
    PROGRAM_ID,
    ALT_PROGRAM_ID,
    TOKEN_PROGRAM_ID,
    TOKEN_2022_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID,
    SYSTEM_PROGRAM_ID,
    RENT_SYSVAR_ID,
    INSTRUCTIONS_SYSVAR_ID,
    SIGNED_ORDER_SIZE,
    ORDER_SIZE,
    ORDERBOOK_SIZE,
    MAX_OUTCOMES,
    MIN_OUTCOMES,
    MAX_MAKERS,
    SEED_GLOBAL_DEPOSIT,
    GLOBAL_DEPOSIT_TOKEN_DISCRIMINATOR,
    GLOBAL_DEPOSIT_TOKEN_SIZE,
    # Errors
    LightconeError,
    InvalidDiscriminatorError,
    AccountNotFoundError,
    InvalidAccountDataError,
    InvalidOrderError,
    InvalidSignatureError,
    OrderExpiredError,
    InsufficientBalanceError,
    MarketNotActiveError,
    ExchangePausedError,
    InvalidOutcomeError,
    TooManyMakersError,
    OrdersDoNotCrossError,
    # Utils
    keccak256,
    derive_condition_id,
    get_associated_token_address,
    get_associated_token_address_2022,
    orders_cross,
    # Account Deserialization
    deserialize_exchange,
    deserialize_market,
    deserialize_position,
    deserialize_order_status,
    deserialize_orderbook,
    deserialize_user_nonce,
    deserialize_global_deposit_token,
    is_global_deposit_token,
    # PDA Functions
    get_exchange_pda,
    get_market_pda,
    get_vault_pda,
    get_mint_authority_pda,
    get_conditional_mint_pda,
    get_order_status_pda,
    get_user_nonce_pda,
    get_position_pda,
    get_orderbook_pda,
    get_alt_pda,
    get_all_conditional_mint_pdas,
    get_all_conditional_mints,
    get_global_deposit_pda,
    get_position_alt_pda,
    get_user_global_deposit_pda,
    # Order Functions
    create_bid_order,
    create_ask_order,
    create_signed_bid_order,
    create_signed_ask_order,
    hash_order,
    hash_order_hex,
    sign_order,
    verify_order_signature,
    serialize_full_order,
    deserialize_full_order,
    serialize_order,
    serialize_compact_order,
    deserialize_order,
    deserialize_compact_order,
    to_order,
    to_compact_order,
    to_submit_request,
    is_signed,
    signature_hex,
    validate_order,
    validate_signed_order,
    calculate_taker_fill,
    cancel_all_message,
    cancel_order_message,
    cancel_trigger_order_message,
    generate_cancel_all_salt,
    sign_cancel_all,
    sign_cancel_order,
    is_order_expired,
    orders_can_cross,
    derive_orderbook_id,
    apply_signature,
    # Instruction Builders
    build_initialize_instruction,
    build_create_market_instruction,
    build_add_deposit_mint_instruction,
    build_mint_complete_set_instruction,
    build_merge_complete_set_instruction,
    build_cancel_order_instruction,
    build_increment_nonce_instruction,
    build_settle_market_instruction,
    build_redeem_winnings_instruction,
    build_set_paused_instruction,
    build_set_operator_instruction,
    build_withdraw_from_position_instruction,
    build_activate_market_instruction,
    build_match_orders_multi_instruction,
    build_create_orderbook_instruction,
    build_set_authority_instruction,
    build_whitelist_deposit_token_instruction,
    build_deposit_to_global_instruction,
    build_global_to_market_deposit_instruction,
    build_init_position_tokens_instruction,
    build_deposit_and_swap_instruction,
    build_extend_position_tokens_instruction,
    # Envelope & Builder
    LimitOrderEnvelope,
    TriggerOrderEnvelope,
    OrderBuilder,
)

# ============================================================================
# Submodule access
# ============================================================================

from . import shared
from . import program
from . import domain
from . import auth
from . import privy
from . import http
from . import ws
from . import error
from . import network


__all__ = [
    # Version
    "__version__",
    # Client
    "LightconeClient",
    "LightconeClientBuilder",
    # Shared types
    "OrderBookId",
    "PubkeyStr",
    "Side",
    "TimeInForce",
    "TriggerType",
    "TriggerStatus",
    "TriggerResultStatus",
    "OrderUpdateType",
    "TriggerUpdateType",
    "DepositSource",
    "Resolution",
    "SubmitOrderRequest",
    "SubmitTriggerOrderRequest",
    # Shared utils
    "abbr_number",
    "display",
    "display_decimal",
    "display_formatted_string",
    "display_with_decimals",
    "parse_decimal",
    "format_decimal",
    "is_zero",
    "from_decimal_value",
    "OrderbookDecimals",
    "ScaledAmounts",
    "ScalingError",
    "scale_price_size",
    "derive_orderbook_id",
    "to_base_units",
    "to_decimal_value",
    # Errors
    "SdkError",
    "HttpError",
    "HttpErrorKind",
    "WsError",
    "WsErrorKind",
    "AuthError",
    "AuthErrorKind",
    # Network
    "DEFAULT_API_URL",
    "DEFAULT_WS_URL",
    # Auth
    "User",
    "AuthCredentials",
    "LinkedAccount",
    "EmbeddedWallet",
    "LoginRequest",
    "LoginResponse",
    "MeResponse",
    "NonceResponse",
    "generate_signin_message",
    "Auth",
    "sign_login_message",
    # Privy
    "PrivyOrderEnvelope",
    "SignAndSendTxRequest",
    "SignAndSendTxResponse",
    "SignAndSendOrderRequest",
    "SignAndCancelOrderRequest",
    "SignAndCancelAllRequest",
    "ExportWalletRequest",
    "ExportWalletResponse",
    "Privy",
    "privy_order_from_limit_envelope",
    "privy_order_from_trigger_envelope",
    # HTTP
    "LightconeHttp",
    "RetryPolicy",
    "RetryConfig",
    "DEFAULT_RETRY_CONFIG",
    "delay_for_attempt",
    # WebSocket
    "WsConfig",
    "WS_DEFAULT_CONFIG",
    "WsEvent",
    "WsEventType",
    "MessageIn",
    "MessageInType",
    "ReadyState",
    "WsErrorData",
    "WsClient",
    "ping",
    "subscribe_books",
    "unsubscribe_books",
    "subscribe_trades",
    "unsubscribe_trades",
    "subscribe_user",
    "unsubscribe_user",
    "subscribe_price_history",
    "unsubscribe_price_history",
    "subscribe_ticker",
    "unsubscribe_ticker",
    "subscribe_market",
    "unsubscribe_market",
    "subscribe_deposit_price",
    "unsubscribe_deposit_price",
    "parse_message_in",
    # Program - Client
    "LightconePinocchioClient",
    # Program - Types
    "MarketStatus",
    "OrderSide",
    "Exchange",
    "Market",
    "Position",
    "OrderStatus",
    "UserNonce",
    "Orderbook",
    "GlobalDepositToken",
    "SignedOrder",
    "FullOrder",
    "Order",
    "CompactOrder",
    "OutcomeMetadata",
    "MakerFill",
    # Program - Params
    "InitializeParams",
    "CreateMarketParams",
    "AddDepositMintParams",
    "MintCompleteSetParams",
    "MergeCompleteSetParams",
    "SettleMarketParams",
    "RedeemWinningsParams",
    "WithdrawFromPositionParams",
    "ActivateMarketParams",
    "MatchOrdersMultiParams",
    "CreateOrderbookParams",
    "SetAuthorityParams",
    "BidOrderParams",
    "AskOrderParams",
    "BuildResult",
    "WhitelistDepositTokenParams",
    "DepositToGlobalParams",
    "GlobalToMarketDepositParams",
    "InitPositionTokensParams",
    "DepositAndSwapParams",
    "ExtendPositionTokensParams",
    # Program - Constants
    "PROGRAM_ID",
    "ALT_PROGRAM_ID",
    "TOKEN_PROGRAM_ID",
    "TOKEN_2022_PROGRAM_ID",
    "ASSOCIATED_TOKEN_PROGRAM_ID",
    "SYSTEM_PROGRAM_ID",
    "RENT_SYSVAR_ID",
    "INSTRUCTIONS_SYSVAR_ID",
    "SIGNED_ORDER_SIZE",
    "ORDER_SIZE",
    "ORDERBOOK_SIZE",
    "MAX_OUTCOMES",
    "MIN_OUTCOMES",
    "MAX_MAKERS",
    "SEED_GLOBAL_DEPOSIT",
    "GLOBAL_DEPOSIT_TOKEN_DISCRIMINATOR",
    "GLOBAL_DEPOSIT_TOKEN_SIZE",
    # Program - Errors
    "LightconeError",
    "InvalidDiscriminatorError",
    "AccountNotFoundError",
    "InvalidAccountDataError",
    "InvalidOrderError",
    "InvalidSignatureError",
    "OrderExpiredError",
    "InsufficientBalanceError",
    "MarketNotActiveError",
    "ExchangePausedError",
    "InvalidOutcomeError",
    "TooManyMakersError",
    "OrdersDoNotCrossError",
    # Program - Utils
    "keccak256",
    "derive_condition_id",
    "get_associated_token_address",
    "get_associated_token_address_2022",
    "orders_cross",
    # Program - Accounts
    "deserialize_exchange",
    "deserialize_market",
    "deserialize_position",
    "deserialize_order_status",
    "deserialize_orderbook",
    "deserialize_user_nonce",
    "deserialize_global_deposit_token",
    "is_global_deposit_token",
    # Program - PDAs
    "get_exchange_pda",
    "get_market_pda",
    "get_vault_pda",
    "get_mint_authority_pda",
    "get_conditional_mint_pda",
    "get_order_status_pda",
    "get_user_nonce_pda",
    "get_position_pda",
    "get_orderbook_pda",
    "get_alt_pda",
    "get_all_conditional_mint_pdas",
    "get_all_conditional_mints",
    "get_global_deposit_pda",
    "get_position_alt_pda",
    "get_user_global_deposit_pda",
    # Program - Orders
    "create_bid_order",
    "create_ask_order",
    "create_signed_bid_order",
    "create_signed_ask_order",
    "hash_order",
    "hash_order_hex",
    "sign_order",
    "verify_order_signature",
    "serialize_full_order",
    "deserialize_full_order",
    "serialize_order",
    "serialize_compact_order",
    "deserialize_order",
    "deserialize_compact_order",
    "to_order",
    "to_compact_order",
    "to_submit_request",
    "is_signed",
    "signature_hex",
    "validate_order",
    "validate_signed_order",
    "calculate_taker_fill",
    "cancel_all_message",
    "cancel_order_message",
    "cancel_trigger_order_message",
    "generate_cancel_all_salt",
    "sign_cancel_all",
    "sign_cancel_order",
    "is_order_expired",
    "orders_can_cross",
    "derive_orderbook_id",
    "apply_signature",
    # Program - Instructions (all 23)
    "build_initialize_instruction",
    "build_create_market_instruction",
    "build_add_deposit_mint_instruction",
    "build_mint_complete_set_instruction",
    "build_merge_complete_set_instruction",
    "build_cancel_order_instruction",
    "build_increment_nonce_instruction",
    "build_settle_market_instruction",
    "build_redeem_winnings_instruction",
    "build_set_paused_instruction",
    "build_set_operator_instruction",
    "build_withdraw_from_position_instruction",
    "build_activate_market_instruction",
    "build_match_orders_multi_instruction",
    "build_create_orderbook_instruction",
    "build_set_authority_instruction",
    "build_whitelist_deposit_token_instruction",
    "build_deposit_to_global_instruction",
    "build_global_to_market_deposit_instruction",
    "build_init_position_tokens_instruction",
    "build_deposit_and_swap_instruction",
    "build_extend_position_tokens_instruction",
    # Program - Envelope & Builder
    "LimitOrderEnvelope",
    "TriggerOrderEnvelope",
    "OrderBuilder",
    # Submodules
    "shared",
    "program",
    "domain",
    "auth",
    "privy",
    "http",
    "ws",
    "error",
    "network",
]
