// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.mjs";
import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function optString(dict, key) {
  let match = dict[key];
  if (typeof match === "string") {
    return match;
  }
}

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("single_winner" === v) {
        return {
          TAG: "Ok",
          _0: "single_winner"
        };
      } else if ("scalar" === v) {
        return {
          TAG: "Ok",
          _0: "scalar"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function payout_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let outcomeIndex = Stdlib_Option.getOr(Stdlib_Option.map(v["outcome_index"], Spice.floatFromJson), Spice.error(undefined, "outcome_index" + " missing", v));
  if (outcomeIndex.TAG === "Ok") {
    let payoutNumerator = Stdlib_Option.getOr(Stdlib_Option.map(v["payout_numerator"], Spice.floatFromJson), Spice.error(undefined, "payout_numerator" + " missing", v));
    if (payoutNumerator.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          outcomeIndex: outcomeIndex._0,
          payoutNumerator: payoutNumerator._0
        }
      };
    }
    let e = payoutNumerator._0;
    return Spice.error("." + ("payout_numerator" + e.path), e.message, e.value);
  }
  let e$1 = outcomeIndex._0;
  return Spice.error("." + ("outcome_index" + e$1.path), e$1.message, e$1.value);
}

function decode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "market resolution is not an object", json);
  }
  let match = json["kind"];
  let match$1 = json["payout_denominator"];
  let match$2 = json["payouts"];
  if (match === undefined) {
    return Spice.error(undefined, "market resolution missing kind/payout_denominator/payouts", json);
  }
  if (match$1 === undefined) {
    return Spice.error(undefined, "market resolution missing kind/payout_denominator/payouts", json);
  }
  if (typeof match$1 !== "number") {
    return Spice.error(undefined, "market resolution missing kind/payout_denominator/payouts", json);
  }
  if (match$2 === undefined) {
    return Spice.error(undefined, "market resolution missing kind/payout_denominator/payouts", json);
  }
  let match$3 = t_decode(match);
  let match$4 = Spice.arrayFromJson(payout_decode, match$2);
  if (match$3.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: match$3._0
    };
  }
  if (match$4.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: match$4._0
    };
  }
  let match$5 = json["single_winning_outcome"];
  let singleWinningOutcome = typeof match$5 === "number" ? match$5 : undefined;
  return {
    TAG: "Ok",
    _0: {
      kind: match$3._0,
      payoutDenominator: match$1,
      payouts: match$4._0,
      singleWinningOutcome: singleWinningOutcome
    }
  };
}

function marketResolvedDataDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "market_resolved data is not an object", json);
  }
  let match = json["market_pubkey"];
  if (match === undefined) {
    return Spice.error(undefined, "market_resolved data missing market_pubkey", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "market_resolved data missing market_pubkey", json);
  }
  let resolution = Stdlib_Option.flatMap(json["resolution"], value => Stdlib_Result.mapOr(decode(value), undefined, value => value));
  return {
    TAG: "Ok",
    _0: {
      marketPubkey: match,
      marketSlug: optString(json, "market_slug"),
      marketName: optString(json, "market_name"),
      resolution: resolution
    }
  };
}

function orderFilledDataDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "order_filled data is not an object", json);
  }
  let match = json["order_hash"];
  let match$1 = json["market_pubkey"];
  let match$2 = json["side"];
  let match$3 = json["price"];
  let match$4 = json["filled"];
  let match$5 = json["remaining"];
  if (typeof match === "string" && typeof match$1 === "string" && typeof match$2 === "string" && typeof match$3 === "string" && typeof match$4 === "string" && typeof match$5 === "string") {
    return {
      TAG: "Ok",
      _0: {
        orderHash: match,
        marketPubkey: match$1,
        side: match$2,
        price: match$3,
        filled: match$4,
        remaining: match$5,
        marketSlug: optString(json, "market_slug"),
        marketName: optString(json, "market_name"),
        outcomeName: optString(json, "outcome_name"),
        outcomeNameLong: optString(json, "outcome_name_long"),
        outcomeIconUrlLow: optString(json, "outcome_icon_url_low"),
        outcomeIconUrlMedium: optString(json, "outcome_icon_url_medium"),
        outcomeIconUrlHigh: optString(json, "outcome_icon_url_high")
      }
    };
  } else {
    return Spice.error(undefined, "order_filled data missing required fields", json);
  }
}

function marketDataDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "market data is not an object", json);
  }
  let match = json["market_pubkey"];
  if (typeof match === "string") {
    return {
      TAG: "Ok",
      _0: {
        marketPubkey: match,
        marketSlug: optString(json, "market_slug"),
        marketName: optString(json, "market_name")
      }
    };
  } else {
    return Spice.error(undefined, "market data missing market_pubkey", json);
  }
}

function notificationKindDecode(dict, json) {
  let match = dict["notification_type"];
  if (match === undefined) {
    return Spice.error(undefined, "unknown notification_type", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "unknown notification_type", json);
  }
  switch (match) {
    case "global" :
      return {
        TAG: "Ok",
        _0: "Global"
      };
    case "market_resolved" :
      let data = dict["data"];
      if (data !== undefined) {
        return Stdlib_Result.map(marketResolvedDataDecode(data), value => ({
          TAG: "MarketResolved",
          _0: value
        }));
      } else {
        return Spice.error(undefined, "market_resolved notification missing data", json);
      }
    case "new_market" :
      let data$1 = dict["data"];
      if (data$1 !== undefined) {
        return Stdlib_Result.map(marketDataDecode(data$1), value => ({
          TAG: "NewMarket",
          _0: value
        }));
      } else {
        return Spice.error(undefined, "new_market notification missing data", json);
      }
    case "order_filled" :
      let data$2 = dict["data"];
      if (data$2 !== undefined) {
        return Stdlib_Result.map(orderFilledDataDecode(data$2), value => ({
          TAG: "OrderFilled",
          _0: value
        }));
      } else {
        return Spice.error(undefined, "order_filled notification missing data", json);
      }
    case "rules_clarified" :
      let data$3 = dict["data"];
      if (data$3 !== undefined) {
        return Stdlib_Result.map(marketDataDecode(data$3), value => ({
          TAG: "RulesClarified",
          _0: value
        }));
      } else {
        return Spice.error(undefined, "rules_clarified notification missing data", json);
      }
    default:
      return Spice.error(undefined, "unknown notification_type", json);
  }
}

function notificationDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "notification is not an object", json);
  }
  let match = json["id"];
  let match$1 = json["title"];
  let match$2 = json["message"];
  let match$3 = json["created_at"];
  if (match === undefined) {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (match$1 === undefined) {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (typeof match$1 !== "string") {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (match$2 === undefined) {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (typeof match$2 !== "string") {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (match$3 === undefined) {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  if (typeof match$3 !== "string") {
    return Spice.error(undefined, "notification missing id/title/message/created_at", json);
  }
  let kind = notificationKindDecode(json, json);
  if (kind.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        id: match,
        kind: kind._0,
        title: match$1,
        message: match$2,
        expiresAt: optString(json, "expires_at"),
        createdAt: match$3
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: kind._0
    };
  }
}

function notificationsResponseDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "notifications response is not an object", json);
  }
  let notificationsJson = json["notifications"];
  if (notificationsJson !== undefined) {
    return Spice.arrayFromJson(notificationDecode, notificationsJson);
  } else {
    return Spice.error(undefined, "notifications response missing 'notifications'", json);
  }
}

function isGlobal(notification) {
  let match = notification.kind;
  return typeof match !== "object";
}

function marketSlug(notification) {
  let data = notification.kind;
  if (typeof data !== "object") {
    return;
  }
  switch (data.TAG) {
    case "OrderFilled" :
      return data._0.marketSlug;
    case "MarketResolved" :
    case "NewMarket" :
    case "RulesClarified" :
      return data._0.marketSlug;
  }
}

async function fetch(client, cookieHeader) {
  return await Http.get(client.http, "/api/notifications", undefined, undefined, cookieHeader, notificationsResponseDecode);
}

async function dismiss(client, notificationId) {
  let body = Object.fromEntries([[
      "notification_id",
      notificationId
    ]]);
  return await Http.post(client.http, "/api/notifications/dismiss", body, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
}

let MarketResolution = {
  Kind: {}
};

export {
  MarketResolution,
  notificationDecode,
  isGlobal,
  marketSlug,
  fetch,
  dismiss,
}
/* Http Not a pure module */
