// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../Http.res.mjs";
import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Shared from "../Shared.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function tradeResponse_encode(v) {
  let extra = v.takerFee;
  let extra$1 = v.makerFee;
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.floatToJson(v.id)
    ],
    [
      "trade_id",
      Spice.stringToJson(v.tradeId)
    ],
    [
      "orderbook_id",
      Shared.orderBookId_encodeJson(v.orderbookId)
    ],
    [
      "taker_pubkey",
      Spice.stringToJson(v.takerPubkey)
    ],
    [
      "maker_pubkey",
      Spice.stringToJson(v.makerPubkey)
    ],
    [
      "side",
      Shared.Side.t_encodeJson(v.side)
    ],
    [
      "size",
      Spice.stringToJson(v.size)
    ],
    [
      "price",
      Spice.stringToJson(v.price)
    ],
    [
      "taker_fee",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "maker_fee",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "executed_at",
      Spice.floatToJson(v.executedAt)
    ]
  ]));
}

function tradeResponse_encodeJson(v) {
  let extra = v.takerFee;
  let extra$1 = v.makerFee;
  return Object.fromEntries(Spice.filterOptional([
    [
      "id",
      Spice.floatToJson(v.id)
    ],
    [
      "trade_id",
      Spice.stringToJson(v.tradeId)
    ],
    [
      "orderbook_id",
      Shared.orderBookId_encodeJson(v.orderbookId)
    ],
    [
      "taker_pubkey",
      Spice.stringToJson(v.takerPubkey)
    ],
    [
      "maker_pubkey",
      Spice.stringToJson(v.makerPubkey)
    ],
    [
      "side",
      Shared.Side.t_encodeJson(v.side)
    ],
    [
      "size",
      Spice.stringToJson(v.size)
    ],
    [
      "price",
      Spice.stringToJson(v.price)
    ],
    [
      "taker_fee",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "maker_fee",
      Spice.optionToJson(Spice.stringToJson, extra$1)
    ],
    [
      "executed_at",
      Spice.floatToJson(v.executedAt)
    ]
  ]));
}

function tradeResponse_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let id = Stdlib_Option.getOr(Stdlib_Option.map(v["id"], Spice.floatFromJson), Spice.error(undefined, "id" + " missing", v));
  if (id.TAG === "Ok") {
    let tradeId = Stdlib_Option.getOr(Stdlib_Option.map(v["trade_id"], Spice.stringFromJson), Spice.error(undefined, "trade_id" + " missing", v));
    if (tradeId.TAG === "Ok") {
      let orderbookId = Stdlib_Option.getOr(Stdlib_Option.map(v["orderbook_id"], Shared.orderBookId_decode), Spice.error(undefined, "orderbook_id" + " missing", v));
      if (orderbookId.TAG === "Ok") {
        let takerPubkey = Stdlib_Option.getOr(Stdlib_Option.map(v["taker_pubkey"], Spice.stringFromJson), Spice.error(undefined, "taker_pubkey" + " missing", v));
        if (takerPubkey.TAG === "Ok") {
          let makerPubkey = Stdlib_Option.getOr(Stdlib_Option.map(v["maker_pubkey"], Spice.stringFromJson), Spice.error(undefined, "maker_pubkey" + " missing", v));
          if (makerPubkey.TAG === "Ok") {
            let side = Stdlib_Option.getOr(Stdlib_Option.map(v["side"], Shared.Side.t_decode), Spice.error(undefined, "side" + " missing", v));
            if (side.TAG === "Ok") {
              let size = Stdlib_Option.getOr(Stdlib_Option.map(v["size"], Spice.stringFromJson), Spice.error(undefined, "size" + " missing", v));
              if (size.TAG === "Ok") {
                let price = Stdlib_Option.getOr(Stdlib_Option.map(v["price"], Spice.stringFromJson), Spice.error(undefined, "price" + " missing", v));
                if (price.TAG === "Ok") {
                  let takerFee = Stdlib_Option.getOr(Stdlib_Option.map(v["taker_fee"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
                    TAG: "Ok",
                    _0: undefined
                  });
                  if (takerFee.TAG === "Ok") {
                    let makerFee = Stdlib_Option.getOr(Stdlib_Option.map(v["maker_fee"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
                      TAG: "Ok",
                      _0: undefined
                    });
                    if (makerFee.TAG === "Ok") {
                      let executedAt = Stdlib_Option.getOr(Stdlib_Option.map(v["executed_at"], Spice.floatFromJson), Spice.error(undefined, "executed_at" + " missing", v));
                      if (executedAt.TAG === "Ok") {
                        return {
                          TAG: "Ok",
                          _0: {
                            id: id._0,
                            tradeId: tradeId._0,
                            orderbookId: orderbookId._0,
                            takerPubkey: takerPubkey._0,
                            makerPubkey: makerPubkey._0,
                            side: side._0,
                            size: size._0,
                            price: price._0,
                            takerFee: takerFee._0,
                            makerFee: makerFee._0,
                            executedAt: executedAt._0
                          }
                        };
                      }
                      let e = executedAt._0;
                      return Spice.error("." + ("executed_at" + e.path), e.message, e.value);
                    }
                    let e$1 = makerFee._0;
                    return Spice.error("." + ("maker_fee" + e$1.path), e$1.message, e$1.value);
                  }
                  let e$2 = takerFee._0;
                  return Spice.error("." + ("taker_fee" + e$2.path), e$2.message, e$2.value);
                }
                let e$3 = price._0;
                return Spice.error("." + ("price" + e$3.path), e$3.message, e$3.value);
              }
              let e$4 = size._0;
              return Spice.error("." + ("size" + e$4.path), e$4.message, e$4.value);
            }
            let e$5 = side._0;
            return Spice.error("." + ("side" + e$5.path), e$5.message, e$5.value);
          }
          let e$6 = makerPubkey._0;
          return Spice.error("." + ("maker_pubkey" + e$6.path), e$6.message, e$6.value);
        }
        let e$7 = takerPubkey._0;
        return Spice.error("." + ("taker_pubkey" + e$7.path), e$7.message, e$7.value);
      }
      let e$8 = orderbookId._0;
      return Spice.error("." + ("orderbook_id" + e$8.path), e$8.message, e$8.value);
    }
    let e$9 = tradeId._0;
    return Spice.error("." + ("trade_id" + e$9.path), e$9.message, e$9.value);
  }
  let e$10 = id._0;
  return Spice.error("." + ("id" + e$10.path), e$10.message, e$10.value);
}

function tradesResponse_encode(v) {
  let extra = v.nextCursor;
  return Object.fromEntries(Spice.filterOptional([
    [
      "orderbook_id",
      Shared.orderBookId_encodeJson(v.orderbookId)
    ],
    [
      "trades",
      Spice.arrayToJson(tradeResponse_encodeJson, v.trades)
    ],
    [
      "next_cursor",
      Spice.optionToJson(Spice.floatToJson, extra)
    ],
    [
      "has_more",
      Spice.boolToJson(v.hasMore)
    ]
  ]));
}

function tradesResponse_encodeJson(v) {
  let extra = v.nextCursor;
  return Object.fromEntries(Spice.filterOptional([
    [
      "orderbook_id",
      Shared.orderBookId_encodeJson(v.orderbookId)
    ],
    [
      "trades",
      Spice.arrayToJson(tradeResponse_encodeJson, v.trades)
    ],
    [
      "next_cursor",
      Spice.optionToJson(Spice.floatToJson, extra)
    ],
    [
      "has_more",
      Spice.boolToJson(v.hasMore)
    ]
  ]));
}

function tradesResponse_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let orderbookId = Stdlib_Option.getOr(Stdlib_Option.map(v["orderbook_id"], Shared.orderBookId_decode), Spice.error(undefined, "orderbook_id" + " missing", v));
  if (orderbookId.TAG === "Ok") {
    let trades = Stdlib_Option.getOr(Stdlib_Option.map(v["trades"], extra => Spice.arrayFromJson(tradeResponse_decode, extra)), Spice.error(undefined, "trades" + " missing", v));
    if (trades.TAG === "Ok") {
      let nextCursor = Stdlib_Option.getOr(Stdlib_Option.map(v["next_cursor"], json => Stdlib_Result.map(Spice.floatFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (nextCursor.TAG === "Ok") {
        let hasMore = Stdlib_Option.getOr(Stdlib_Option.map(v["has_more"], Spice.boolFromJson), {
          TAG: "Ok",
          _0: false
        });
        if (hasMore.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              orderbookId: orderbookId._0,
              trades: trades._0,
              nextCursor: nextCursor._0,
              hasMore: hasMore._0
            }
          };
        }
        let e = hasMore._0;
        return Spice.error("." + ("has_more" + e.path), e.message, e.value);
      }
      let e$1 = nextCursor._0;
      return Spice.error("." + ("next_cursor" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = trades._0;
    return Spice.error("." + ("trades" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = orderbookId._0;
  return Spice.error("." + ("orderbook_id" + e$3.path), e$3.message, e$3.value);
}

function marketTradesResponse_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let marketPubkey = Stdlib_Option.getOr(Stdlib_Option.map(v["market_pubkey"], Shared.pubkeyStr_decode), Spice.error(undefined, "market_pubkey" + " missing", v));
  if (marketPubkey.TAG === "Ok") {
    let trades = Stdlib_Option.getOr(Stdlib_Option.map(v["trades"], extra => Spice.arrayFromJson(tradeResponse_decode, extra)), Spice.error(undefined, "trades" + " missing", v));
    if (trades.TAG === "Ok") {
      let nextCursor = Stdlib_Option.getOr(Stdlib_Option.map(v["next_cursor"], json => Stdlib_Result.map(Spice.floatFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (nextCursor.TAG === "Ok") {
        let hasMore = Stdlib_Option.getOr(Stdlib_Option.map(v["has_more"], Spice.boolFromJson), {
          TAG: "Ok",
          _0: false
        });
        if (hasMore.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              marketPubkey: marketPubkey._0,
              trades: trades._0,
              nextCursor: nextCursor._0,
              hasMore: hasMore._0
            }
          };
        }
        let e = hasMore._0;
        return Spice.error("." + ("has_more" + e.path), e.message, e.value);
      }
      let e$1 = nextCursor._0;
      return Spice.error("." + ("next_cursor" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = trades._0;
    return Spice.error("." + ("trades" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = marketPubkey._0;
  return Spice.error("." + ("market_pubkey" + e$3.path), e$3.message, e$3.value);
}

function tradeOfResponse(response) {
  return {
    orderbookId: response.orderbookId,
    tradeId: response.tradeId,
    cursorId: response.id,
    timestamp: response.executedAt,
    price: response.price,
    size: response.size,
    side: response.side,
    sequence: 0.0
  };
}

function pageOfTrades(trades, nextCursor, hasMore) {
  return {
    trades: trades.map(tradeOfResponse),
    nextCursor: nextCursor,
    hasMore: hasMore
  };
}

function optionalQuery(query, key, value) {
  Stdlib_Option.forEach(value, value => {
    query.push([
      key,
      value
    ]);
  });
}

async function get(client, orderbookId, limit, cursor) {
  let query = [[
      "orderbook_id",
      orderbookId
    ]];
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  optionalQuery(query, "cursor", Stdlib_Option.map(cursor, value => value.toString()));
  return Stdlib_Result.map(await Http.get(client.http, "/api/trades", query, undefined, undefined, tradesResponse_decode), response => pageOfTrades(response.trades, response.nextCursor, response.hasMore));
}

async function getByMarket(client, marketPubkey, limit, cursor) {
  let query = [[
      "market_pubkey",
      marketPubkey
    ]];
  optionalQuery(query, "limit", Stdlib_Option.map(limit, value => value.toString()));
  optionalQuery(query, "cursor", Stdlib_Option.map(cursor, value => value.toString()));
  return Stdlib_Result.map(await Http.get(client.http, "/api/trades/market", query, undefined, undefined, marketTradesResponse_decode), response => pageOfTrades(response.trades, response.nextCursor, response.hasMore));
}

export {
  get,
  getByMarket,
  tradeResponse_encode,
  tradeResponse_encodeJson,
  tradeResponse_decode,
  tradesResponse_encode,
  tradesResponse_encodeJson,
  tradesResponse_decode,
  pageOfTrades,
}
/* Http Not a pure module */
