// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kit from "@solana/kit";

function _address() {
  return Kit.address("So11111111111111111111111111111111111111112");
}

function _u64() {
  return Kit.getU64Encoder().encode(1n);
}

function _hex(bytes) {
  return Kit.getBase16Decoder().decode(bytes);
}

async function _sign(keypair, message) {
  return await Kit.signBytes(keypair.privateKey, message);
}

function _pda(input) {
  return Kit.getProgramDerivedAddress(input);
}

function _rpc(url) {
  return Kit.createSolanaRpc(url);
}

export {
  _address,
  _u64,
  _hex,
  _sign,
  _pda,
  _rpc,
}
/* @solana/kit Not a pure module */
