// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "./Http.res.mjs";
import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Client from "./Client.res.mjs";
import * as Kit from "@solana/kit";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("privy" === v) {
        return {
          TAG: "Ok",
          _0: "privy"
        };
      } else if ("lightcone" === v) {
        return {
          TAG: "Ok",
          _0: "lightcone"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function t_decode$1(v) {
  switch (typeof v) {
    case "string" :
      if ("solana" === v) {
        return {
          TAG: "Ok",
          _0: "solana"
        };
      } else if ("ethereum" === v) {
        return {
          TAG: "Ok",
          _0: "ethereum"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function privyEmbeddedWallet_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let privyId = Stdlib_Option.getOr(Stdlib_Option.map(v["privy_id"], Spice.stringFromJson), Spice.error(undefined, "privy_id" + " missing", v));
  if (privyId.TAG === "Ok") {
    let chain = Stdlib_Option.getOr(Stdlib_Option.map(v["chain"], t_decode$1), Spice.error(undefined, "chain" + " missing", v));
    if (chain.TAG === "Ok") {
      let address = Stdlib_Option.getOr(Stdlib_Option.map(v["address"], Spice.stringFromJson), Spice.error(undefined, "address" + " missing", v));
      if (address.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            privyId: privyId._0,
            chain: chain._0,
            address: address._0
          }
        };
      }
      let e = address._0;
      return Spice.error("." + ("address" + e.path), e.message, e.value);
    }
    let e$1 = chain._0;
    return Spice.error("." + ("chain" + e$1.path), e$1.message, e$1.value);
  }
  let e$2 = privyId._0;
  return Spice.error("." + ("privy_id" + e$2.path), e$2.message, e$2.value);
}

function userPrivyData_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let id = Stdlib_Option.getOr(Stdlib_Option.map(v["id"], Spice.stringFromJson), Spice.error(undefined, "id" + " missing", v));
  if (id.TAG === "Ok") {
    let wallet = Stdlib_Option.getOr(Stdlib_Option.map(v["wallet"], privyEmbeddedWallet_decode), Spice.error(undefined, "wallet" + " missing", v));
    if (wallet.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          id: id._0,
          wallet: wallet._0
        }
      };
    }
    let e = wallet._0;
    return Spice.error("." + ("wallet" + e.path), e.message, e.value);
  }
  let e$1 = id._0;
  return Spice.error("." + ("id" + e$1.path), e$1.message, e$1.value);
}

function xAccountData_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let userId = Stdlib_Option.getOr(Stdlib_Option.map(v["user_id"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
    TAG: "Ok",
    _0: undefined
  });
  if (userId.TAG === "Ok") {
    let username = Stdlib_Option.getOr(Stdlib_Option.map(v["username"], Spice.stringFromJson), Spice.error(undefined, "username" + " missing", v));
    if (username.TAG === "Ok") {
      let displayName = Stdlib_Option.getOr(Stdlib_Option.map(v["display_name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (displayName.TAG === "Ok") {
        let avatarUrl = Stdlib_Option.getOr(Stdlib_Option.map(v["avatar_url"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (avatarUrl.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              userId: userId._0,
              username: username._0,
              displayName: displayName._0,
              avatarUrl: avatarUrl._0
            }
          };
        }
        let e = avatarUrl._0;
        return Spice.error("." + ("avatar_url" + e.path), e.message, e.value);
      }
      let e$1 = displayName._0;
      return Spice.error("." + ("display_name" + e$1.path), e$1.message, e$1.value);
    }
    let e$2 = username._0;
    return Spice.error("." + ("username" + e$2.path), e$2.message, e$2.value);
  }
  let e$3 = userId._0;
  return Spice.error("." + ("user_id" + e$3.path), e$3.message, e$3.value);
}

function googleAccountData_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let email = Stdlib_Option.getOr(Stdlib_Option.map(v["email"], Spice.stringFromJson), Spice.error(undefined, "email" + " missing", v));
  if (email.TAG === "Ok") {
    let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
      TAG: "Ok",
      _0: undefined
    });
    if (name.TAG === "Ok") {
      let givenName = Stdlib_Option.getOr(Stdlib_Option.map(v["given_name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
        TAG: "Ok",
        _0: undefined
      });
      if (givenName.TAG === "Ok") {
        let familyName = Stdlib_Option.getOr(Stdlib_Option.map(v["family_name"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
          TAG: "Ok",
          _0: undefined
        });
        if (familyName.TAG === "Ok") {
          let avatarUrl = Stdlib_Option.getOr(Stdlib_Option.map(v["avatar_url"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
            TAG: "Ok",
            _0: undefined
          });
          if (avatarUrl.TAG === "Ok") {
            return {
              TAG: "Ok",
              _0: {
                email: email._0,
                name: name._0,
                givenName: givenName._0,
                familyName: familyName._0,
                avatarUrl: avatarUrl._0
              }
            };
          }
          let e = avatarUrl._0;
          return Spice.error("." + ("avatar_url" + e.path), e.message, e.value);
        }
        let e$1 = familyName._0;
        return Spice.error("." + ("family_name" + e$1.path), e$1.message, e$1.value);
      }
      let e$2 = givenName._0;
      return Spice.error("." + ("given_name" + e$2.path), e$2.message, e$2.value);
    }
    let e$3 = name._0;
    return Spice.error("." + ("name" + e$3.path), e$3.message, e$3.value);
  }
  let e$4 = email._0;
  return Spice.error("." + ("email" + e$4.path), e$4.message, e$4.value);
}

function userIdentityDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "identity is not an object", json);
  }
  let match = json["type"];
  if (match === undefined) {
    return Spice.error(undefined, "unknown identity type", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "unknown identity type", json);
  }
  switch (match) {
    case "google" :
      let match$1 = json["account"];
      let match$2 = json["privy"];
      if (match$1 === undefined) {
        return Spice.error(undefined, "google identity missing account/privy", json);
      }
      if (match$2 === undefined) {
        return Spice.error(undefined, "google identity missing account/privy", json);
      }
      let match$3 = googleAccountData_decode(match$1);
      let match$4 = userPrivyData_decode(match$2);
      if (match$3.TAG === "Ok") {
        if (match$4.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "Google",
              account: match$3._0,
              privy: match$4._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: match$4._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$3._0
        };
      }
    case "wallet" :
      let match$5 = json["address"];
      let match$6 = json["chain"];
      if (match$5 === undefined) {
        return Spice.error(undefined, "wallet identity missing address/chain", json);
      }
      if (typeof match$5 !== "string") {
        return Spice.error(undefined, "wallet identity missing address/chain", json);
      }
      if (match$6 === undefined) {
        return Spice.error(undefined, "wallet identity missing address/chain", json);
      }
      let chain = t_decode$1(match$6);
      if (chain.TAG !== "Ok") {
        return {
          TAG: "Error",
          _0: chain._0
        };
      }
      let privy = Stdlib_Option.flatMap(json["privy"], json => Stdlib_Result.mapOr(userPrivyData_decode(json), undefined, value => value));
      return {
        TAG: "Ok",
        _0: {
          TAG: "Wallet",
          address: match$5,
          chain: chain._0,
          privy: privy
        }
      };
    case "x" :
      let match$7 = json["account"];
      let match$8 = json["privy"];
      if (match$7 === undefined) {
        return Spice.error(undefined, "x identity missing account/privy", json);
      }
      if (match$8 === undefined) {
        return Spice.error(undefined, "x identity missing account/privy", json);
      }
      let match$9 = xAccountData_decode(match$7);
      let match$10 = userPrivyData_decode(match$8);
      if (match$9.TAG === "Ok") {
        if (match$10.TAG === "Ok") {
          return {
            TAG: "Ok",
            _0: {
              TAG: "X",
              account: match$9._0,
              privy: match$10._0
            }
          };
        } else {
          return {
            TAG: "Error",
            _0: match$10._0
          };
        }
      } else {
        return {
          TAG: "Error",
          _0: match$9._0
        };
      }
    default:
      return Spice.error(undefined, "unknown identity type", json);
  }
}

function userDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "user is not an object", json);
  }
  let match = json["user_id"];
  let match$1 = json["identity"];
  if (match === undefined) {
    return Spice.error(undefined, "user missing user_id/identity", json);
  }
  if (typeof match !== "string") {
    return Spice.error(undefined, "user missing user_id/identity", json);
  }
  if (match$1 === undefined) {
    return Spice.error(undefined, "user missing user_id/identity", json);
  }
  let identity = userIdentityDecode(match$1);
  if (identity.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: identity._0
    };
  }
  let connectedX = Stdlib_Option.flatMap(json["connected_x"], json => Stdlib_Result.mapOr(xAccountData_decode(json), undefined, value => value));
  return {
    TAG: "Ok",
    _0: {
      userId: match,
      identity: identity._0,
      connectedX: connectedX
    }
  };
}

function sessionResponseDecode(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Spice.error(undefined, "session response is not an object", json);
  }
  let match = json["user"];
  let match$1 = json["expires_at"];
  let match$2 = json["auth_method"];
  let match$3 = json["is_beta"];
  if (match === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (match$1 === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (typeof match$1 !== "number") {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (match$2 === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (match$3 === undefined) {
    return Spice.error(undefined, "session response missing fields", json);
  }
  if (typeof match$3 !== "boolean") {
    return Spice.error(undefined, "session response missing fields", json);
  }
  let match$4 = userDecode(match);
  let match$5 = t_decode(match$2);
  if (match$4.TAG === "Ok") {
    if (match$5.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          user: match$4._0,
          expiresAt: match$1,
          authMethod: match$5._0,
          isBeta: match$3
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: match$5._0
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: match$4._0
    };
  }
}

function nonceResponse_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let nonce = Stdlib_Option.getOr(Stdlib_Option.map(v["nonce"], Spice.stringFromJson), Spice.error(undefined, "nonce" + " missing", v));
  if (nonce.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        nonce: nonce._0
      }
    };
  }
  let e = nonce._0;
  return Spice.error("." + ("nonce" + e.path), e.message, e.value);
}

let bytesToIntArray = ((bytes) => Array.from(bytes));

function signinMessage(nonce) {
  return `Sign in to Lightcone\nNonce: ` + nonce;
}

async function signLoginMessage(keypair, nonce) {
  let message = signinMessage(nonce);
  let messageBytes = Kit.getUtf8Encoder().encode(message);
  let signature = await Kit.signBytes(keypair.privateKey, messageBytes);
  let address = await Kit.getAddressFromPublicKey(keypair.publicKey);
  return {
    message: message,
    signatureBs58: Kit.getBase58Decoder().decode(signature),
    pubkeyBytes: bytesToIntArray(Kit.getAddressEncoder().encode(address))
  };
}

async function getNonce(client) {
  return Stdlib_Result.map(await Http.get(client.http, "/api/auth/nonce", undefined, undefined, undefined, nonceResponse_decode), response => response.nonce);
}

async function loginWithMessage(client, signed, useEmbeddedWallet) {
  let fields = [
    [
      "message",
      signed.message
    ],
    [
      "signature_bs58",
      signed.signatureBs58
    ],
    [
      "pubkey_bytes",
      signed.pubkeyBytes.map(byte => (byte))
    ]
  ];
  Stdlib_Option.forEach(useEmbeddedWallet, value => {
    fields.push([
      "use_embedded_wallet",
      value
    ]);
  });
  let body = Object.fromEntries(fields);
  return await Http.post(client.http, "/api/auth/login_or_register_with_message", body, undefined, undefined, sessionResponseDecode);
}

async function login(client, useEmbeddedWallet) {
  let address = Client.signerAddress(client);
  if (address === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no signing strategy configured; call Client.useNativeSigner or Client.useExternalSigner first"
      }
    };
  }
  let error = await getNonce(client);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let message = signinMessage(error._0);
  let messageBytes = Kit.getUtf8Encoder().encode(message);
  let error$1 = await Client.signMessageBytes(client, messageBytes);
  if (error$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error$1._0
    };
  }
  let signed_signatureBs58 = Kit.getBase58Decoder().decode(error$1._0);
  let signed_pubkeyBytes = bytesToIntArray(Kit.getAddressEncoder().encode(Primitive_option.valFromOption(address)));
  let signed = {
    message: message,
    signatureBs58: signed_signatureBs58,
    pubkeyBytes: signed_pubkeyBytes
  };
  return await loginWithMessage(client, signed, useEmbeddedWallet);
}

async function registerPrivy(client) {
  return await Http.post(client.http, "/api/auth/register-privy", {}, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
}

async function disconnectX(client) {
  return await Http.post(client.http, "/api/auth/disconnect_x", {}, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
}

function connectXUrl(client) {
  return Http.baseUrl(client.http) + `/api/auth/oauth/link/x`;
}

async function checkSession(client, cookieHeader) {
  return await Http.get(client.http, "/api/auth/me", undefined, undefined, cookieHeader, sessionResponseDecode);
}

function isAuthenticated(client) {
  return Stdlib_Option.isSome(Client.authToken(client));
}

async function logout(client) {
  let result = await Http.post(client.http, "/api/auth/logout", {}, undefined, undefined, param => ({
    TAG: "Ok",
    _0: undefined
  }));
  Client.clearAuth(client);
  return result;
}

let AuthMethod = {};

let ChainType = {};

export {
  AuthMethod,
  ChainType,
  signLoginMessage,
  getNonce,
  loginWithMessage,
  login,
  checkSession,
  isAuthenticated,
  logout,
  registerPrivy,
  disconnectX,
  connectXUrl,
}
/* Http Not a pure module */
