// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Env from "./Env.res.mjs";
import * as Http from "./Http.res.mjs";
import * as Kit from "@solana/kit";
import * as RpcFailover from "./RpcFailover.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function make(envOpt, baseUrl, wsUrl, rpcUrl, backupRpcUrl, programId, depositSourceOpt, param) {
  let env = envOpt !== undefined ? envOpt : "prod";
  let depositSource = depositSourceOpt !== undefined ? depositSourceOpt : "global";
  let resolvedRpcUrl = Stdlib_Option.getOr(rpcUrl, Env.rpcUrl(env));
  let rpc = Kit.createSolanaRpc(resolvedRpcUrl);
  return {
    http: Http.make(Stdlib_Option.getOr(baseUrl, Env.apiUrl(env))),
    env: env,
    programId: Kit.address(Stdlib_Option.getOr(programId, Env.programId(env))),
    wsUrl: Stdlib_Option.getOr(wsUrl, Env.wsUrl(env)),
    rpcUrl: resolvedRpcUrl,
    backupRpcUrl: backupRpcUrl,
    rpc: rpc,
    backupRpc: Stdlib_Option.mapOr(backupRpcUrl, rpc, url => Kit.createSolanaRpc(url)),
    rpcFailover: RpcFailover.make(),
    depositSource: depositSource,
    orderNonce: undefined,
    signingStrategy: undefined
  };
}

function http(client) {
  return client.http;
}

function depositSource(client) {
  return client.depositSource;
}

function setDepositSource(client, source) {
  client.depositSource = source;
}

function orderNonce(client) {
  return client.orderNonce;
}

function setOrderNonce(client, nonce) {
  client.orderNonce = nonce;
}

function clearOrderNonce(client) {
  client.orderNonce = undefined;
}

function signerAddress(client) {
  let match = client.signingStrategy;
  if (match !== undefined) {
    if (match.TAG === "NativeSigner") {
      return Primitive_option.some(match.address);
    } else {
      return Primitive_option.some(match._0.address);
    }
  }
}

async function useNativeSigner(client, secretKey) {
  let keypair = await Kit.createKeyPairFromBytes(secretKey);
  let signer = await Kit.createKeyPairSignerFromBytes(secretKey);
  client.signingStrategy = {
    TAG: "NativeSigner",
    keypair: keypair,
    signer: signer,
    address: signer.address
  };
}

function useExternalSigner(client, address, signMessage, signTransaction) {
  client.signingStrategy = {
    TAG: "ExternalSigner",
    _0: {
      address: address,
      signMessage: signMessage,
      signTransaction: signTransaction
    }
  };
}

function clearSigningStrategy(client) {
  client.signingStrategy = undefined;
}

async function signMessageBytes(client, message) {
  let match = client.signingStrategy;
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no signing strategy configured; call Client.useNativeSigner or Client.useExternalSigner first"
      }
    };
  }
  if (match.TAG === "NativeSigner") {
    return {
      TAG: "Ok",
      _0: await Kit.signBytes(match.keypair.privateKey, message)
    };
  }
  let signature;
  try {
    signature = await match._0.signMessage(message);
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "Signing",
          _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "external signer failed to sign message")
        }
      };
    }
    throw error;
  }
  return {
    TAG: "Ok",
    _0: signature
  };
}

function clearAuth(client) {
  Http.clearAuthToken(client.http);
}

function authToken(client) {
  return Http.authToken(client.http);
}

export {
  make,
  http,
  depositSource,
  setDepositSource,
  orderNonce,
  setOrderNonce,
  clearOrderNonce,
  signerAddress,
  useNativeSigner,
  useExternalSigner,
  clearSigningStrategy,
  signMessageBytes,
  clearAuth,
  authToken,
}
/* Http Not a pure module */
