// Generated by ReScript, PLEASE EDIT WITH CARE


let getEnv = (function (key) {
  return (typeof process !== "undefined" && process.env) ? process.env[key] : undefined;
});

function apiUrl(env) {
  let url = getEnv("SDK_API_URL");
  if (url !== undefined) {
    return url;
  }
  switch (env) {
    case "local" :
      return "https://api.local.lightcone.xyz";
    case "staging" :
      return "https://api.staging.lightcone.xyz";
    case "prod" :
      return "https://api.lightcone.xyz";
  }
}

function wsUrl(env) {
  let url = getEnv("SDK_WS_URL");
  if (url !== undefined) {
    return url;
  }
  switch (env) {
    case "local" :
      return "wss://ws.local.lightcone.xyz/ws";
    case "staging" :
      return "wss://ws.staging.lightcone.xyz/ws";
    case "prod" :
      return "wss://ws.lightcone.xyz/ws";
  }
}

function rpcUrl(env) {
  let url = getEnv("SDK_RPC_URL");
  if (url !== undefined) {
    return url;
  }
  switch (env) {
    case "local" :
    case "staging" :
      return "https://api.devnet.solana.com";
    case "prod" :
      return "https://api.mainnet-beta.solana.com";
  }
}

function programId(env) {
  let id = getEnv("SDK_PROGRAM_ID");
  if (id !== undefined) {
    return id;
  }
  switch (env) {
    case "local" :
      return "HQZW84F7WbpDLDdd6eaDsBh6LjDQ2uCxpkZgkLakcago";
    case "staging" :
      return "5G2fWZGHB5BA8gbABVBuR1bU4Ziri9cRxFoojz5C5Rxk";
    case "prod" :
      return "B9rCvafkkjh749284jfDu5UB268pHeRLkzFpFf7t4mxK";
  }
}

function toString(env) {
  switch (env) {
    case "local" :
      return "local";
    case "staging" :
      return "staging";
    case "prod" :
      return "prod";
  }
}

function fromString(raw) {
  let match = raw.toLowerCase();
  switch (match) {
    case "local" :
      return "local";
    case "prod" :
      return "prod";
    case "staging" :
      return "staging";
    default:
      return;
  }
}

export {
  getEnv,
  apiUrl,
  wsUrl,
  rpcUrl,
  programId,
  toString,
  fromString,
}
/* No side effect */
