// Generated by ReScript, PLEASE EDIT WITH CARE


let strictNumber = ((s) => Number(s));

function parseDecimal(value) {
  let trimmed = value.trim();
  if (trimmed === "") {
    return;
  }
  let parsed = strictNumber(trimmed);
  if (Number.isNaN(parsed)) {
    return;
  } else {
    return parsed;
  }
}

function formatDecimal(value, precision) {
  return value.toFixed(precision);
}

export {
  parseDecimal,
  formatDecimal,
}
/* No side effect */
