// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function toWire(code) {
  if (typeof code === "object") {
    return code._0;
  }
  switch (code) {
    case "InsufficientBalance" :
      return "INSUFFICIENT_BALANCE";
    case "Expired" :
      return "EXPIRED";
    case "NonceMismatch" :
      return "NONCE_MISMATCH";
    case "SelfTrade" :
      return "SELF_TRADE";
    case "MarketInactive" :
      return "MARKET_INACTIVE";
    case "BelowMinOrderSize" :
      return "BELOW_MIN_ORDER_SIZE";
    case "InvalidNonce" :
      return "INVALID_NONCE";
    case "BroadcastFailure" :
      return "BROADCAST_FAILURE";
    case "OrderNotFound" :
      return "ORDER_NOT_FOUND";
    case "NotOrderMaker" :
      return "NOT_ORDER_MAKER";
    case "OrderAlreadyFilled" :
      return "ORDER_ALREADY_FILLED";
    case "OrderAlreadyCancelled" :
      return "ORDER_ALREADY_CANCELLED";
    case "DuplicateOrder" :
      return "DUPLICATE_ORDER";
    case "PostOnlyWouldCross" :
      return "POST_ONLY_WOULD_CROSS";
    case "FokNoFill" :
      return "FOK_NO_FILL";
    case "IocNoFill" :
      return "IOC_NO_FILL";
    case "WouldCrossUnavailableLiquidity" :
      return "WOULD_CROSS_UNAVAILABLE_LIQUIDITY";
    case "WouldCrossBook" :
      return "WOULD_CROSS_BOOK";
    case "MarketNotFound" :
      return "MARKET_NOT_FOUND";
    case "OrderbookNotFound" :
      return "ORDERBOOK_NOT_FOUND";
    case "TokenPairMismatch" :
      return "TOKEN_PAIR_MISMATCH";
    case "InsufficientMarketFeeBuffer" :
      return "INSUFFICIENT_MARKET_FEE_BUFFER";
    case "SignatureExpired" :
      return "SIGNATURE_EXPIRED";
  }
}

function fromWire(raw) {
  let match = raw.toUpperCase();
  switch (match) {
    case "BELOW_MIN_ORDER_SIZE" :
      return "BelowMinOrderSize";
    case "BROADCAST_FAILURE" :
      return "BroadcastFailure";
    case "DUPLICATE_ORDER" :
      return "DuplicateOrder";
    case "EXPIRED" :
      return "Expired";
    case "FOK_NO_FILL" :
      return "FokNoFill";
    case "INSUFFICIENT_BALANCE" :
      return "InsufficientBalance";
    case "INSUFFICIENT_MARKET_FEE_BUFFER" :
      return "InsufficientMarketFeeBuffer";
    case "INVALID_NONCE" :
      return "InvalidNonce";
    case "IOC_NO_FILL" :
      return "IocNoFill";
    case "MARKET_INACTIVE" :
      return "MarketInactive";
    case "MARKET_NOT_FOUND" :
      return "MarketNotFound";
    case "NONCE_MISMATCH" :
      return "NonceMismatch";
    case "NOT_ORDER_MAKER" :
      return "NotOrderMaker";
    case "ORDERBOOK_NOT_FOUND" :
      return "OrderbookNotFound";
    case "ORDER_ALREADY_CANCELLED" :
      return "OrderAlreadyCancelled";
    case "ORDER_ALREADY_FILLED" :
      return "OrderAlreadyFilled";
    case "ORDER_NOT_FOUND" :
      return "OrderNotFound";
    case "POST_ONLY_WOULD_CROSS" :
      return "PostOnlyWouldCross";
    case "SELF_TRADE" :
      return "SelfTrade";
    case "SIGNATURE_EXPIRED" :
      return "SignatureExpired";
    case "TOKEN_PAIR_MISMATCH" :
      return "TokenPairMismatch";
    case "WOULD_CROSS_BOOK" :
      return "WouldCrossBook";
    case "WOULD_CROSS_UNAVAILABLE_LIQUIDITY" :
      return "WouldCrossUnavailableLiquidity";
    default:
      return {
        TAG: "Unknown",
        _0: raw
      };
  }
}

function label(code) {
  if (typeof code !== "object") {
    return toWire(code).split("_").map(word => {
      let lower = word.toLowerCase();
      let length = lower.length;
      if (length !== 0) {
        return lower.slice(0, 1).toUpperCase() + lower.slice(1, length);
      } else {
        return "";
      }
    }).join(" ");
  } else {
    return code._0;
  }
}

function decodeRejectedDetails(json) {
  let str = key => {
    if (typeof json !== "object" || json === null || Array.isArray(json)) {
      return;
    }
    let match = json[key];
    if (typeof match === "string") {
      return match;
    }
  };
  return {
    reason: Stdlib_Option.getOr(str("reason"), ""),
    rejectionCode: Stdlib_Option.map(str("rejection_code"), fromWire),
    errorCode: str("error_code"),
    errorLogId: str("error_log_id")
  };
}

function httpErrorToMessage(error) {
  if (typeof error !== "object") {
    if (error === "Unauthorized") {
      return "Unauthorized";
    } else {
      return "Timeout";
    }
  }
  switch (error.TAG) {
    case "ServerError" :
      return `Server error ` + error.status.toString() + `: ` + error.body;
    case "RateLimited" :
      let retryAfterMs = error.retryAfterMs;
      if (retryAfterMs !== undefined) {
        return `Rate limited (retry after ` + retryAfterMs.toString() + `ms)`;
      } else {
        return "Rate limited";
      }
    case "NotFound" :
      return `Not found: ` + error._0;
    case "BadRequest" :
      return `Bad request: ` + error._0;
    case "Network" :
      return `Request failed: ` + error._0;
    case "MaxRetriesExceeded" :
      return `Max retries exceeded after ` + error.attempts.toString() + ` attempts: ` + Stdlib_Option.getOr(error.lastError, "");
  }
}

function wsErrorToMessage(error) {
  if (typeof error !== "object") {
    return "Not connected";
  }
  switch (error.TAG) {
    case "ConnectionFailed" :
      return `Connection failed: ` + error._0;
    case "SendFailed" :
      return `Send failed: ` + error._0;
    case "DeserializationError" :
      return `Deserialization error: ` + error._0;
    case "ProtocolError" :
      return `Protocol error: ` + error._0;
    case "Closed" :
      return `Connection closed: code=` + Stdlib_Option.getOr(Stdlib_Option.map(error.code, c => c.toString()), "?") + ` reason=` + error.reason;
  }
}

function authErrorToMessage(error) {
  if (typeof error === "object") {
    return `Login failed: ` + error._0;
  }
  switch (error) {
    case "NotAuthenticated" :
      return "Not authenticated";
    case "SignatureVerificationFailed" :
      return "Signature verification failed";
    case "TokenExpired" :
      return "Token expired";
  }
}

function toMessage(error) {
  if (typeof error !== "object") {
    return "User cancelled signing";
  }
  switch (error.TAG) {
    case "Http" :
      return `HTTP error: ` + httpErrorToMessage(error._0);
    case "Ws" :
      return `WebSocket error: ` + wsErrorToMessage(error._0);
    case "Auth" :
      return `Auth error: ` + authErrorToMessage(error._0);
    case "Validation" :
      return `Validation error: ` + error._0;
    case "Decode" :
      return `Serialization error: ` + error._0;
    case "Program" :
      return `Program error: ` + error._0;
    case "MissingMarketContext" :
      return `Missing required market context for Market deposit source: ` + error._0;
    case "Signing" :
      return `Signing error: ` + error._0;
    case "ApiRejected" :
      let details = error._0;
      let parts = [`Reason: ` + details.reason];
      Stdlib_Option.forEach(details.rejectionCode, code => {
        parts.push(`Rejection Code: ` + label(code));
      });
      Stdlib_Option.forEach(details.errorCode, code => {
        parts.push(`Error Code: ` + code);
      });
      Stdlib_Option.forEach(details.errorLogId, id => {
        parts.push(`Error Log ID: ` + id);
      });
      Stdlib_Option.forEach(details.requestId, id => {
        parts.push(`Request ID: ` + id);
      });
      return parts.join("\n");
    case "Other" :
      return error._0;
  }
}

function stripNulls(json) {
  if (Array.isArray(json)) {
    return json.map(stripNulls);
  }
  if (json === null) {
    return json;
  }
  switch (typeof json) {
    case "object" :
      return Object.fromEntries(Stdlib_Array.filterMap(Object.entries(json), param => {
        let value = param[1];
        if (value === null) {
          return;
        } else {
          return [
            param[0],
            stripNulls(value)
          ];
        }
      }));
    default:
      return json;
  }
}

function parseApiResponse(bodyDecode, json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Decode",
        _0: "response is not an object"
      }
    };
  }
  let match = json["status"];
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Decode",
        _0: "response missing 'status'"
      }
    };
  }
  if (typeof match !== "string") {
    return {
      TAG: "Error",
      _0: {
        TAG: "Decode",
        _0: "response missing 'status'"
      }
    };
  }
  switch (match) {
    case "error" :
      let details = json["error_details"];
      if (details !== undefined) {
        return {
          TAG: "Error",
          _0: {
            TAG: "ApiRejected",
            _0: decodeRejectedDetails(details)
          }
        };
      } else {
        return {
          TAG: "Error",
          _0: {
            TAG: "Other",
            _0: "error response missing 'error_details'"
          }
        };
      }
    case "success" :
      let body = json["body"];
      if (body !== undefined) {
        return Stdlib_Result.mapError(bodyDecode(stripNulls(body)), error => ({
          TAG: "Decode",
          _0: error.message
        }));
      } else {
        return {
          TAG: "Error",
          _0: {
            TAG: "Decode",
            _0: "success response missing 'body'"
          }
        };
      }
    default:
      return {
        TAG: "Error",
        _0: {
          TAG: "Decode",
          _0: "response missing 'status'"
        }
      };
  }
}

let throwAsJsError = (function (message, sdkError) {
  const err = new Error(message);
  err.name = "LightconeError";
  err.sdkError = sdkError;
  throw err;
});

async function unwrap(promised) {
  let value = await promised;
  if (value.TAG === "Ok") {
    return value._0;
  }
  let error = value._0;
  return throwAsJsError(toMessage(error), error);
}

let RejectionCode = {
  label: label
};

export {
  RejectionCode,
  toMessage,
  stripNulls,
  parseApiResponse,
  throwAsJsError,
  unwrap,
}
/* No side effect */
