// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

let orderBookId_encode = Spice.stringToJson;

let orderBookId_encodeJson = Spice.stringToJson;

let orderBookId_decode = Spice.stringFromJson;

let pubkeyStr_encode = Spice.stringToJson;

let pubkeyStr_encodeJson = Spice.stringToJson;

let pubkeyStr_decode = Spice.stringFromJson;

function t_encode(v) {
  if (v === "bid") {
    return "bid";
  } else {
    return "ask";
  }
}

function t_encodeJson(v) {
  if (v === "bid") {
    return "bid";
  } else {
    return "ask";
  }
}

function t_decode(v) {
  switch (typeof v) {
    case "string" :
      if ("bid" === v) {
        return {
          TAG: "Ok",
          _0: "bid"
        };
      } else if ("ask" === v) {
        return {
          TAG: "Ok",
          _0: "ask"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function toString(side) {
  if (side === "bid") {
    return "bid";
  } else {
    return "ask";
  }
}

function label(side) {
  if (side === "bid") {
    return "Buy";
  } else {
    return "Sell";
  }
}

let Side = {
  t_encode: t_encode,
  t_encodeJson: t_encodeJson,
  t_decode: t_decode,
  toString: toString,
  label: label
};

function t_encode$1(v) {
  if (v === "Base") {
    return "Base";
  } else {
    return "Quote";
  }
}

function t_encodeJson$1(v) {
  if (v === "Base") {
    return "Base";
  } else {
    return "Quote";
  }
}

function t_decode$1(v) {
  switch (typeof v) {
    case "string" :
      if ("Base" === v) {
        return {
          TAG: "Ok",
          _0: "Base"
        };
      } else if ("Quote" === v) {
        return {
          TAG: "Ok",
          _0: "Quote"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let Denominator = {
  t_encode: t_encode$1,
  t_encodeJson: t_encodeJson$1,
  t_decode: t_decode$1
};

function spendDenominator(side) {
  if (side === "bid") {
    return "Quote";
  } else {
    return "Base";
  }
}

function receiveDenominator(side) {
  if (side === "bid") {
    return "Base";
  } else {
    return "Quote";
  }
}

function t_encode$2(v) {
  switch (v) {
    case "GTC" :
      return "GTC";
    case "IOC" :
      return "IOC";
    case "FOK" :
      return "FOK";
    case "ALO" :
      return "ALO";
  }
}

function t_encodeJson$2(v) {
  switch (v) {
    case "GTC" :
      return "GTC";
    case "IOC" :
      return "IOC";
    case "FOK" :
      return "FOK";
    case "ALO" :
      return "ALO";
  }
}

function t_decode$2(v) {
  switch (typeof v) {
    case "string" :
      if ("GTC" === v) {
        return {
          TAG: "Ok",
          _0: "GTC"
        };
      } else if ("IOC" === v) {
        return {
          TAG: "Ok",
          _0: "IOC"
        };
      } else if ("FOK" === v) {
        return {
          TAG: "Ok",
          _0: "FOK"
        };
      } else if ("ALO" === v) {
        return {
          TAG: "Ok",
          _0: "ALO"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let TimeInForce = {
  t_encode: t_encode$2,
  t_encodeJson: t_encodeJson$2,
  t_decode: t_decode$2
};

function t_encode$3(v) {
  if (v === "TP") {
    return "TP";
  } else {
    return "SL";
  }
}

function t_encodeJson$3(v) {
  if (v === "TP") {
    return "TP";
  } else {
    return "SL";
  }
}

function t_decode$3(v) {
  switch (typeof v) {
    case "string" :
      if ("TP" === v) {
        return {
          TAG: "Ok",
          _0: "TP"
        };
      } else if ("SL" === v) {
        return {
          TAG: "Ok",
          _0: "SL"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let TriggerType = {
  t_encode: t_encode$3,
  t_encodeJson: t_encodeJson$3,
  t_decode: t_decode$3
};

function t_encode$4(v) {
  switch (v) {
    case "created" :
      return "created";
    case "triggered" :
      return "triggered";
    case "failed" :
      return "failed";
    case "expired" :
      return "expired";
    case "invalidated" :
      return "invalidated";
  }
}

function t_encodeJson$4(v) {
  switch (v) {
    case "created" :
      return "created";
    case "triggered" :
      return "triggered";
    case "failed" :
      return "failed";
    case "expired" :
      return "expired";
    case "invalidated" :
      return "invalidated";
  }
}

function t_decode$4(v) {
  switch (typeof v) {
    case "string" :
      if ("created" === v) {
        return {
          TAG: "Ok",
          _0: "created"
        };
      } else if ("triggered" === v) {
        return {
          TAG: "Ok",
          _0: "triggered"
        };
      } else if ("failed" === v) {
        return {
          TAG: "Ok",
          _0: "failed"
        };
      } else if ("expired" === v) {
        return {
          TAG: "Ok",
          _0: "expired"
        };
      } else if ("invalidated" === v) {
        return {
          TAG: "Ok",
          _0: "invalidated"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let TriggerStatus = {
  t_encode: t_encode$4,
  t_encodeJson: t_encodeJson$4,
  t_decode: t_decode$4
};

function t_encode$5(v) {
  switch (v) {
    case "PLACEMENT" :
      return "PLACEMENT";
    case "UPDATE" :
      return "UPDATE";
    case "CANCELLATION" :
      return "CANCELLATION";
  }
}

function t_encodeJson$5(v) {
  switch (v) {
    case "PLACEMENT" :
      return "PLACEMENT";
    case "UPDATE" :
      return "UPDATE";
    case "CANCELLATION" :
      return "CANCELLATION";
  }
}

function t_decode$5(v) {
  switch (typeof v) {
    case "string" :
      if ("PLACEMENT" === v) {
        return {
          TAG: "Ok",
          _0: "PLACEMENT"
        };
      } else if ("UPDATE" === v) {
        return {
          TAG: "Ok",
          _0: "UPDATE"
        };
      } else if ("CANCELLATION" === v) {
        return {
          TAG: "Ok",
          _0: "CANCELLATION"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let OrderUpdateType = {
  t_encode: t_encode$5,
  t_encodeJson: t_encodeJson$5,
  t_decode: t_decode$5
};

function t_encode$6(v) {
  switch (v) {
    case "CREATED" :
      return "CREATED";
    case "TRIGGERED" :
      return "TRIGGERED";
    case "FAILED" :
      return "FAILED";
    case "EXPIRED" :
      return "EXPIRED";
    case "INVALIDATED" :
      return "INVALIDATED";
  }
}

function t_encodeJson$6(v) {
  switch (v) {
    case "CREATED" :
      return "CREATED";
    case "TRIGGERED" :
      return "TRIGGERED";
    case "FAILED" :
      return "FAILED";
    case "EXPIRED" :
      return "EXPIRED";
    case "INVALIDATED" :
      return "INVALIDATED";
  }
}

function t_decode$6(v) {
  switch (typeof v) {
    case "string" :
      if ("CREATED" === v) {
        return {
          TAG: "Ok",
          _0: "CREATED"
        };
      } else if ("TRIGGERED" === v) {
        return {
          TAG: "Ok",
          _0: "TRIGGERED"
        };
      } else if ("FAILED" === v) {
        return {
          TAG: "Ok",
          _0: "FAILED"
        };
      } else if ("EXPIRED" === v) {
        return {
          TAG: "Ok",
          _0: "EXPIRED"
        };
      } else if ("INVALIDATED" === v) {
        return {
          TAG: "Ok",
          _0: "INVALIDATED"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let TriggerUpdateType = {
  t_encode: t_encode$6,
  t_encodeJson: t_encodeJson$6,
  t_decode: t_decode$6
};

function t_encode$7(v) {
  switch (v) {
    case "filled" :
      return "filled";
    case "accepted" :
      return "accepted";
    case "rejected" :
      return "rejected";
  }
}

function t_encodeJson$7(v) {
  switch (v) {
    case "filled" :
      return "filled";
    case "accepted" :
      return "accepted";
    case "rejected" :
      return "rejected";
  }
}

function t_decode$7(v) {
  switch (typeof v) {
    case "string" :
      if ("filled" === v) {
        return {
          TAG: "Ok",
          _0: "filled"
        };
      } else if ("accepted" === v) {
        return {
          TAG: "Ok",
          _0: "accepted"
        };
      } else if ("rejected" === v) {
        return {
          TAG: "Ok",
          _0: "rejected"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let TriggerResultStatus = {
  t_encode: t_encode$7,
  t_encodeJson: t_encodeJson$7,
  t_decode: t_decode$7
};

function t_encode$8(v) {
  if (v === "global") {
    return "global";
  } else {
    return "market";
  }
}

function t_encodeJson$8(v) {
  if (v === "global") {
    return "global";
  } else {
    return "market";
  }
}

function t_decode$8(v) {
  switch (typeof v) {
    case "string" :
      if ("global" === v) {
        return {
          TAG: "Ok",
          _0: "global"
        };
      } else if ("market" === v) {
        return {
          TAG: "Ok",
          _0: "market"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

let DepositSource = {
  t_encode: t_encode$8,
  t_encodeJson: t_encodeJson$8,
  t_decode: t_decode$8
};

function t_encode$9(v) {
  switch (v) {
    case "1m" :
      return "1m";
    case "5m" :
      return "5m";
    case "15m" :
      return "15m";
    case "1h" :
      return "1h";
    case "4h" :
      return "4h";
    case "1d" :
      return "1d";
  }
}

function t_encodeJson$9(v) {
  switch (v) {
    case "1m" :
      return "1m";
    case "5m" :
      return "5m";
    case "15m" :
      return "15m";
    case "1h" :
      return "1h";
    case "4h" :
      return "4h";
    case "1d" :
      return "1d";
  }
}

function t_decode$9(v) {
  switch (typeof v) {
    case "string" :
      if ("1m" === v) {
        return {
          TAG: "Ok",
          _0: "1m"
        };
      } else if ("5m" === v) {
        return {
          TAG: "Ok",
          _0: "5m"
        };
      } else if ("15m" === v) {
        return {
          TAG: "Ok",
          _0: "15m"
        };
      } else if ("1h" === v) {
        return {
          TAG: "Ok",
          _0: "1h"
        };
      } else if ("4h" === v) {
        return {
          TAG: "Ok",
          _0: "4h"
        };
      } else if ("1d" === v) {
        return {
          TAG: "Ok",
          _0: "1d"
        };
      } else {
        return Spice.error(undefined, "Not matched", v);
      }
    case "number" :
      return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

function toString$1(resolution) {
  switch (resolution) {
    case "1m" :
      return "1m";
    case "5m" :
      return "5m";
    case "15m" :
      return "15m";
    case "1h" :
      return "1h";
    case "4h" :
      return "4h";
    case "1d" :
      return "1d";
  }
}

function seconds(resolution) {
  switch (resolution) {
    case "1m" :
      return 60;
    case "5m" :
      return 300;
    case "15m" :
      return 900;
    case "1h" :
      return 3600;
    case "4h" :
      return 14400;
    case "1d" :
      return 86400;
  }
}

function fromString(s) {
  switch (s) {
    case "15m" :
      return "15m";
    case "1d" :
      return "1d";
    case "1h" :
      return "1h";
    case "1m" :
      return "1m";
    case "4h" :
      return "4h";
    case "5m" :
      return "5m";
    default:
      return;
  }
}

let Resolution = {
  t_encode: t_encode$9,
  t_encodeJson: t_encodeJson$9,
  t_decode: t_decode$9,
  toString: toString$1,
  seconds: seconds,
  fromString: fromString
};

function deriveOrderbookId(baseToken, quoteToken) {
  let prefix = s => s.slice(0, Primitive_int.min(8, s.length));
  return prefix(baseToken) + `_` + prefix(quoteToken);
}

export {
  orderBookId_encode,
  orderBookId_encodeJson,
  orderBookId_decode,
  pubkeyStr_encode,
  pubkeyStr_encodeJson,
  pubkeyStr_decode,
  Side,
  Denominator,
  spendDenominator,
  receiveDenominator,
  TimeInForce,
  TriggerType,
  TriggerStatus,
  OrderUpdateType,
  TriggerUpdateType,
  TriggerResultStatus,
  DepositSource,
  Resolution,
  deriveOrderbookId,
}
/* No side effect */
