// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ws from "./ws/Ws.res.mjs";
import * as Rpc from "./Rpc.res.mjs";
import * as Auth from "./Auth.res.mjs";
import * as Order from "./domain/Order.res.mjs";
import * as Trade from "./domain/Trade.res.mjs";
import * as Client from "./Client.res.mjs";
import * as Faucet from "./domain/Faucet.res.mjs";
import * as Market from "./domain/Market.res.mjs";
import * as Metrics from "./domain/Metrics.res.mjs";
import * as Envelope from "./program/Envelope.res.mjs";
import * as Position from "./domain/Position.res.mjs";
import * as Referral from "./domain/Referral.res.mjs";
import * as SdkError from "./SdkError.res.mjs";
import * as Orderbook from "./domain/Orderbook.res.mjs";
import * as OrderState from "./domain/OrderState.res.mjs";
import * as TradeState from "./domain/TradeState.res.mjs";
import * as Kit from "@solana/kit";
import * as Notification from "./domain/Notification.res.mjs";
import * as PriceHistory from "./domain/PriceHistory.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as OrderbookState from "./domain/OrderbookState.res.mjs";
import * as PositionBuilders from "./program/PositionBuilders.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as DepositPriceState from "./domain/DepositPriceState.res.mjs";
import * as PriceHistoryState from "./domain/PriceHistoryState.res.mjs";

function make(envOpt, baseUrl, wsUrl, rpcUrl, backupRpcUrl, programId, depositSourceOpt, param) {
  let env = envOpt !== undefined ? envOpt : "prod";
  let depositSource = depositSourceOpt !== undefined ? depositSourceOpt : "global";
  return Client.make(env, baseUrl, wsUrl, rpcUrl, backupRpcUrl, programId, depositSource, undefined);
}

function makeForEnv(env) {
  return Client.make(env, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
}

let useNativeSigner = Client.useNativeSigner;

function useExternalSigner(client, address, signMessage, signTransaction) {
  Client.useExternalSigner(client, Kit.address(address), signMessage, signTransaction);
}

let clearSigningStrategy = Client.clearSigningStrategy;

let clearOrderNonce = Client.clearOrderNonce;

function signerAddress(client) {
  return Stdlib_Option.map(Client.signerAddress(client), prim => prim);
}

function signerAddressOrThrow(client) {
  let address = Client.signerAddress(client);
  if (address !== undefined) {
    return Primitive_option.valFromOption(address);
  }
  let error = {
    TAG: "Signing",
    _0: "no signing strategy set; call useNativeSigner or useExternalSigner first"
  };
  return SdkError.throwAsJsError(SdkError.toMessage(error), error);
}

function getNonce(client) {
  return SdkError.unwrap(Auth.getNonce(client));
}

function login(client, useEmbeddedWallet) {
  return SdkError.unwrap(Auth.login(client, useEmbeddedWallet));
}

function checkSession(client, cookieHeader) {
  return SdkError.unwrap(Auth.checkSession(client, cookieHeader));
}

function logout(client) {
  return SdkError.unwrap(Auth.logout(client));
}

let isAuthenticated = Auth.isAuthenticated;

function registerPrivy(client) {
  return SdkError.unwrap(Auth.registerPrivy(client));
}

function disconnectX(client) {
  return SdkError.unwrap(Auth.disconnectX(client));
}

let connectXUrl = Auth.connectXUrl;

let AuthClient = {
  getNonce: getNonce,
  login: login,
  checkSession: checkSession,
  logout: logout,
  isAuthenticated: isAuthenticated,
  registerPrivy: registerPrivy,
  disconnectX: disconnectX,
  connectXUrl: connectXUrl
};

function get(client, cursor, limit) {
  return SdkError.unwrap(Market.get(client, cursor, limit));
}

function featured(client) {
  return SdkError.unwrap(Market.featured(client));
}

function getBySlug(client, slug) {
  return SdkError.unwrap(Market.getBySlug(client, slug));
}

function getByPubkey(client, pubkey) {
  return SdkError.unwrap(Market.getByPubkey(client, pubkey));
}

function search(client, query, limit) {
  return SdkError.unwrap(Market.search(client, query, limit));
}

function globalDepositAssets(client) {
  return SdkError.unwrap(Market.globalDepositAssets(client));
}

function depositMints(client, marketPubkey) {
  return SdkError.unwrap(Market.getDepositMints(client, marketPubkey));
}

let MarketClient = {
  get: get,
  featured: featured,
  getBySlug: getBySlug,
  getByPubkey: getByPubkey,
  search: search,
  globalDepositAssets: globalDepositAssets,
  depositMints: depositMints
};

function get$1(client, orderbookId, depth) {
  return SdkError.unwrap(Orderbook.get(client, orderbookId, depth, undefined, undefined));
}

let OrderbookClient = {
  get: get$1
};

function forOrderbook(client, orderbookId, limit, cursor) {
  return SdkError.unwrap(Trade.get(client, orderbookId, limit, cursor));
}

function forMarket(client, marketPubkey, limit, cursor) {
  return SdkError.unwrap(Trade.getByMarket(client, marketPubkey, limit, cursor));
}

let TradeClient = {
  forOrderbook: forOrderbook,
  forMarket: forMarket
};

function forUser(client, limit, cursor) {
  return SdkError.unwrap(Order.getUserOrders(client, limit, cursor, undefined));
}

async function submitLimit(client, market, baseMint, quoteMint, side, price, size, baseDecimals, quoteDecimals, priceDecimals, tickSize, orderbookId, timeInForce) {
  let decimals = {
    baseDecimals: baseDecimals,
    quoteDecimals: quoteDecimals,
    priceDecimals: priceDecimals,
    tickSize: tickSize
  };
  return await SdkError.unwrap(Envelope.submitLimitOrderSigned(client, Kit.address(market), Kit.address(baseMint), Kit.address(quoteMint), side, price, size, decimals, orderbookId, undefined, undefined, undefined, timeInForce, undefined));
}

async function submitTrigger(client, market, baseMint, quoteMint, side, price, size, baseDecimals, quoteDecimals, priceDecimals, tickSize, orderbookId, triggerPrice, triggerType, timeInForce) {
  let decimals = {
    baseDecimals: baseDecimals,
    quoteDecimals: quoteDecimals,
    priceDecimals: priceDecimals,
    tickSize: tickSize
  };
  return await SdkError.unwrap(Envelope.submitTriggerOrderSigned(client, Kit.address(market), Kit.address(baseMint), Kit.address(quoteMint), side, price, size, decimals, orderbookId, triggerPrice, triggerType, undefined, undefined, undefined, timeInForce, undefined));
}

function cancel(client, orderHash) {
  return SdkError.unwrap(Order.cancelSigned(client, orderHash));
}

function cancelTrigger(client, triggerOrderId) {
  return SdkError.unwrap(Order.cancelTriggerSigned(client, triggerOrderId));
}

function cancelAll(client, orderbookId) {
  return SdkError.unwrap(Order.cancelAllSigned(client, orderbookId));
}

function fills(client, marketPubkey, limit, cursor) {
  return SdkError.unwrap(Order.getUserOrderFills(client, marketPubkey, limit, cursor, undefined));
}

function fillsByWallet(client, walletAddress, marketPubkey, limit, cursor) {
  return SdkError.unwrap(Order.getUserOrderFillsByWallet(client, walletAddress, marketPubkey, limit, cursor));
}

let OrderClient = {
  forUser: forUser,
  submitLimit: submitLimit,
  submitTrigger: submitTrigger,
  cancel: cancel,
  cancelTrigger: cancelTrigger,
  cancelAll: cancelAll,
  fills: fills,
  fillsByWallet: fillsByWallet
};

function forUser$1(client, userPubkey) {
  return SdkError.unwrap(Position.get(client, userPubkey));
}

function forMarket$1(client, userPubkey, marketPubkey) {
  return SdkError.unwrap(Position.getForMarket(client, userPubkey, marketPubkey));
}

function mine(client) {
  return SdkError.unwrap(Position.positions(client, undefined));
}

function depositTokenBalances(client) {
  return SdkError.unwrap(Position.depositTokenBalances(client, undefined));
}

async function depositToGlobal(client, mint, amount) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.depositToGlobal(client, user, Kit.address(mint), amount));
}

async function withdrawFromGlobal(client, mint, amount) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.withdrawFromGlobal(client, user, Kit.address(mint), amount));
}

async function globalToMarketDeposit(client, market, mint, amount, numOutcomes) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.globalToMarketDeposit(client, user, Kit.address(market), Kit.address(mint), amount, numOutcomes));
}

async function merge(client, market, mint, amount, numOutcomes) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.merge(client, user, Kit.address(market), Kit.address(mint), amount, numOutcomes));
}

async function redeemWinnings(client, market, mint, amount, outcomeIndex) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.redeemWinnings(client, user, Kit.address(market), Kit.address(mint), amount, outcomeIndex));
}

async function deposit(client, market, mint, amount, numOutcomes) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.deposit(client, user, Kit.address(market), Kit.address(mint), amount, numOutcomes));
}

async function withdrawFromPosition(client, market, mint, amount, outcomeIndex) {
  let user = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.withdrawFromPosition(client, user, Kit.address(market), Kit.address(mint), amount, outcomeIndex));
}

async function extendPositionTokens(client, user, market, lookupTable, depositMints, numOutcomes) {
  let operator = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.extendPositionTokens(client, operator, Kit.address(user), Kit.address(market), Kit.address(lookupTable), depositMints.map(prim => Kit.address(prim)), numOutcomes));
}

async function closePositionAlt(client, position, market, lookupTable) {
  let operator = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.closePositionAlt(client, operator, Kit.address(position), Kit.address(market), Kit.address(lookupTable)));
}

async function closePositionTokenAccounts(client, market, position, depositMints, numOutcomes) {
  let operator = signerAddressOrThrow(client);
  return await SdkError.unwrap(PositionBuilders.closePositionTokenAccounts(client, operator, Kit.address(market), Kit.address(position), depositMints.map(prim => Kit.address(prim)), numOutcomes));
}

let PositionClient = {
  forUser: forUser$1,
  forMarket: forMarket$1,
  mine: mine,
  depositTokenBalances: depositTokenBalances,
  depositToGlobal: depositToGlobal,
  withdrawFromGlobal: withdrawFromGlobal,
  globalToMarketDeposit: globalToMarketDeposit,
  merge: merge,
  redeemWinnings: redeemWinnings,
  deposit: deposit,
  withdrawFromPosition: withdrawFromPosition,
  extendPositionTokens: extendPositionTokens,
  closePositionAlt: closePositionAlt,
  closePositionTokenAccounts: closePositionTokenAccounts
};

function platform(client) {
  return SdkError.unwrap(Metrics.platform(client));
}

function markets(client) {
  return SdkError.unwrap(Metrics.markets(client));
}

function market(client, marketPubkey) {
  return SdkError.unwrap(Metrics.market(client, marketPubkey));
}

function orderbookTickers(client, depositAsset) {
  return SdkError.unwrap(Metrics.orderbookTickers(client, depositAsset));
}

function categories(client) {
  return SdkError.unwrap(Metrics.categories(client));
}

function depositTokens(client) {
  return SdkError.unwrap(Metrics.depositTokens(client));
}

function leaderboard(client, limit) {
  return SdkError.unwrap(Metrics.leaderboard(client, limit));
}

function orderbook(client, orderbookId) {
  return SdkError.unwrap(Metrics.orderbook(client, orderbookId));
}

function depositTokensVolumeHistory(client, fromMs, toMs, limit) {
  return SdkError.unwrap(Metrics.depositTokensVolumeHistory(client, fromMs, toMs, limit));
}

function openInterestHistory(client, fromMs, toMs, limit) {
  return SdkError.unwrap(Metrics.openInterestHistory(client, fromMs, toMs, limit));
}

function uniqueTradersHistory(client, scope, scopeKey, fromMs, toMs, limit) {
  return SdkError.unwrap(Metrics.uniqueTradersHistory(client, scope, scopeKey, fromMs, toMs, limit));
}

function history(client, scope, scopeKey, resolutionOpt, fromMs, toMs, limit) {
  let resolution = resolutionOpt !== undefined ? resolutionOpt : "1h";
  return SdkError.unwrap(Metrics.history(client, scope, scopeKey, resolution, fromMs, toMs, limit));
}

function user(client) {
  return SdkError.unwrap(Metrics.user(client, undefined));
}

function userByWallet(client, walletAddress) {
  return SdkError.unwrap(Metrics.userByWallet(client, walletAddress));
}

let MetricsClient = {
  platform: platform,
  markets: markets,
  market: market,
  orderbookTickers: orderbookTickers,
  categories: categories,
  depositTokens: depositTokens,
  leaderboard: leaderboard,
  orderbook: orderbook,
  depositTokensVolumeHistory: depositTokensVolumeHistory,
  openInterestHistory: openInterestHistory,
  uniqueTradersHistory: uniqueTradersHistory,
  history: history,
  user: user,
  userByWallet: userByWallet
};

function get$2(client, orderbookId, resolution, fromMs, toMs) {
  return SdkError.unwrap(PriceHistory.get(client, orderbookId, resolution, fromMs, toMs));
}

function lineData(client, orderbookId, resolution, fromMs, toMs, cursor, limit) {
  return SdkError.unwrap(PriceHistory.getLineData(client, orderbookId, resolution, fromMs, toMs, cursor, limit));
}

function depositAssetSnapshot(client) {
  return SdkError.unwrap(PriceHistory.getDepositAssetPricesSnapshot(client));
}

let PriceHistoryClient = {
  get: get$2,
  lineData: lineData,
  depositAssetSnapshot: depositAssetSnapshot
};

function list(client) {
  return SdkError.unwrap(Notification.fetch(client, undefined));
}

function dismiss(client, notificationId) {
  return SdkError.unwrap(Notification.dismiss(client, notificationId));
}

let NotificationClient = {
  list: list,
  dismiss: dismiss
};

function status(client) {
  return SdkError.unwrap(Referral.getStatus(client, undefined));
}

function redeem(client, code) {
  return SdkError.unwrap(Referral.redeem(client, code));
}

let ReferralClient = {
  status: status,
  redeem: redeem
};

function claim(client, walletAddress) {
  return SdkError.unwrap(Faucet.claim(client, walletAddress));
}

let FaucetClient = {
  claim: claim
};

let activeRpc = Rpc.activeRpc;

function latestBlockhash(client) {
  return SdkError.unwrap(Rpc.getLatestBlockhash(client));
}

function exchange(client) {
  return SdkError.unwrap(Rpc.getExchange(client));
}

function market$1(client, marketPubkey) {
  return SdkError.unwrap(Rpc.getMarket(client, Kit.address(marketPubkey)));
}

function orderbook$1(client, baseMint, quoteMint) {
  return SdkError.unwrap(Rpc.getOrderbook(client, Kit.address(baseMint), Kit.address(quoteMint)));
}

function position(client, userPubkey, marketPubkey) {
  return SdkError.unwrap(Rpc.getPosition(client, Kit.address(userPubkey), Kit.address(marketPubkey)));
}

function nonce(client, userPubkey) {
  return SdkError.unwrap(Rpc.getNonce(client, Kit.address(userPubkey)));
}

async function exchangePda(client) {
  return await Rpc.exchangePda(client);
}

async function marketPda(client, marketId) {
  return await Rpc.marketPda(client, marketId);
}

async function positionPda(client, userPubkey, marketPubkey) {
  return await Rpc.positionPda(client, Kit.address(userPubkey), Kit.address(marketPubkey));
}

async function globalDepositTokenPda(client, mint) {
  return await Rpc.globalDepositTokenPda(client, Kit.address(mint));
}

let RpcClient = {
  activeRpc: activeRpc,
  latestBlockhash: latestBlockhash,
  exchange: exchange,
  market: market$1,
  orderbook: orderbook$1,
  position: position,
  nonce: nonce,
  exchangePda: exchangePda,
  marketPda: marketPda,
  positionPda: positionPda,
  globalDepositTokenPda: globalDepositTokenPda
};

function connect(client, onMessage, onConnectedOpt, onErrorOpt) {
  let onConnected = onConnectedOpt !== undefined ? onConnectedOpt : () => {};
  let onError = onErrorOpt !== undefined ? onErrorOpt : param => {};
  return Ws.connect(client.wsUrl, onMessage, onConnected, undefined, onError, undefined, undefined);
}

function subscribe(connection, subscription) {
  Ws.subscribe(connection, subscription);
}

function unsubscribe(connection, subscription) {
  Ws.unsubscribe(connection, subscription);
}

let disconnect = Ws.disconnect;

let isConnected = Ws.isConnected;

let readyState = Ws.readyState;

let clearAuthedSubscriptions = Ws.clearAuthedSubscriptions;

let WsClient = {
  connect: connect,
  subscribe: subscribe,
  unsubscribe: unsubscribe,
  disconnect: disconnect,
  isConnected: isConnected,
  readyState: readyState,
  clearAuthedSubscriptions: clearAuthedSubscriptions
};

let LiveOrderbook = OrderbookState;

let LivePriceHistory = PriceHistoryState;

let LiveDepositPrice = DepositPriceState;

let make$1 = OrderState.UserOpenLimitOrders.make;

let get$3 = OrderState.UserOpenLimitOrders.get;

let getByMarket = OrderState.UserOpenLimitOrders.getByMarket;

let insert = OrderState.UserOpenLimitOrders.insert;

let upsert = OrderState.UserOpenLimitOrders.upsert;

let remove = OrderState.UserOpenLimitOrders.remove;

let clear = OrderState.UserOpenLimitOrders.clear;

let isEmpty = OrderState.UserOpenLimitOrders.isEmpty;

let LiveOpenLimitOrders = {
  make: make$1,
  get: get$3,
  getByMarket: getByMarket,
  insert: insert,
  upsert: upsert,
  remove: remove,
  clear: clear,
  isEmpty: isEmpty,
  limitOrderOfUpdate: OrderState.limitOrderOfUpdate,
  ofSnapshotOrders: OrderState.ofSnapshotOrders
};

let make$2 = OrderState.UserTriggerOrders.make;

let get$4 = OrderState.UserTriggerOrders.get;

let getByMarket$1 = OrderState.UserTriggerOrders.getByMarket;

let all = OrderState.UserTriggerOrders.all;

let getById = OrderState.UserTriggerOrders.getById;

let insert$1 = OrderState.UserTriggerOrders.insert;

let remove$1 = OrderState.UserTriggerOrders.remove;

let clear$1 = OrderState.UserTriggerOrders.clear;

let isEmpty$1 = OrderState.UserTriggerOrders.isEmpty;

let size = OrderState.UserTriggerOrders.size;

let LiveTriggerOrders = {
  make: make$2,
  get: get$4,
  getByMarket: getByMarket$1,
  all: all,
  getById: getById,
  insert: insert$1,
  remove: remove$1,
  clear: clear$1,
  isEmpty: isEmpty$1,
  size: size,
  triggerOrderOfUpdate: OrderState.triggerOrderOfUpdate,
  limitPrice: OrderState.limitPrice
};

let LiveTrades = TradeState;

let make$3 = Position.UserMarketBalanceIndex.make;

let get$5 = Position.UserMarketBalanceIndex.get;

let insert$2 = Position.UserMarketBalanceIndex.insert;

let remove$2 = Position.UserMarketBalanceIndex.remove;

let extend = Position.UserMarketBalanceIndex.extend;

let marketPubkeys = Position.UserMarketBalanceIndex.marketPubkeys;

let ofMarketBalance = Position.UserMarketBalanceIndex.ofMarketBalance;

let ofMarketBalances = Position.UserMarketBalanceIndex.ofMarketBalances;

let LiveUserBalances = {
  make: make$3,
  get: get$5,
  insert: insert$2,
  remove: remove$2,
  extend: extend,
  marketPubkeys: marketPubkeys,
  ofMarketBalance: ofMarketBalance,
  ofMarketBalances: ofMarketBalances
};

let unwrap = SdkError.unwrap;

export {
  make,
  makeForEnv,
  useNativeSigner,
  useExternalSigner,
  clearSigningStrategy,
  clearOrderNonce,
  signerAddress,
  unwrap,
  signerAddressOrThrow,
  AuthClient,
  MarketClient,
  OrderbookClient,
  TradeClient,
  OrderClient,
  PositionClient,
  MetricsClient,
  PriceHistoryClient,
  NotificationClient,
  ReferralClient,
  FaucetClient,
  RpcClient,
  WsClient,
  LiveOrderbook,
  LivePriceHistory,
  LiveDepositPrice,
  LiveOpenLimitOrders,
  LiveTriggerOrders,
  LiveTrades,
  LiveUserBalances,
}
/* Ws Not a pure module */
