"""On-chain program interaction module for Lightcone.

This module provides the client and utilities for interacting with
the Lightcone smart contract on Solana.
"""

# Types
from .types import (
    MarketStatus,
    OrderSide,
    Exchange,
    Market,
    Position,
    OrderStatus,
    UserNonce,
    Orderbook,
    FullOrder,
    Order,
    CompactOrder,
    OutcomeMetadata,
    MakerFill,
    InitializeParams,
    CreateMarketParams,
    AddDepositMintParams,
    MintCompleteSetParams,
    MergeCompleteSetParams,
    SettleMarketParams,
    RedeemWinningsParams,
    WithdrawFromPositionParams,
    ActivateMarketParams,
    MatchOrdersMultiParams,
    CreateOrderbookParams,
    SetAuthorityParams,
    BidOrderParams,
    AskOrderParams,
    BuildResult,
)

# Constants
from .constants import (
    PROGRAM_ID,
    ALT_PROGRAM_ID,
    TOKEN_PROGRAM_ID,
    TOKEN_2022_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID,
    SYSTEM_PROGRAM_ID,
    RENT_SYSVAR_ID,
    INSTRUCTIONS_SYSVAR_ID,
    EXCHANGE_DISCRIMINATOR,
    MARKET_DISCRIMINATOR,
    ORDER_STATUS_DISCRIMINATOR,
    USER_NONCE_DISCRIMINATOR,
    POSITION_DISCRIMINATOR,
    ORDERBOOK_DISCRIMINATOR,
    SEED_CENTRAL_STATE,
    SEED_MARKET,
    SEED_VAULT,
    SEED_MINT_AUTHORITY,
    SEED_CONDITIONAL_MINT,
    SEED_ORDER_STATUS,
    SEED_USER_NONCE,
    SEED_POSITION,
    ORDERBOOK_SEED,
    EXCHANGE_SIZE,
    MARKET_SIZE,
    ORDER_STATUS_SIZE,
    USER_NONCE_SIZE,
    POSITION_SIZE,
    ORDERBOOK_SIZE,
    SIGNED_ORDER_SIZE,
    ORDER_SIZE,
    FULL_ORDER_SIZE,
    COMPACT_ORDER_SIZE,
    SIGNATURE_SIZE,
    ORDER_HASH_SIZE,
    MAX_OUTCOMES,
    MIN_OUTCOMES,
    MAX_MAKERS,
    NO_WINNING_OUTCOME,
    INSTRUCTION_SET_AUTHORITY,
    INSTRUCTION_CREATE_ORDERBOOK,
)

# Errors
from .errors import (
    LightconeError,
    InvalidDiscriminatorError,
    AccountNotFoundError,
    InvalidAccountDataError,
    InvalidOrderError,
    InvalidSignatureError,
    OrderExpiredError,
    InsufficientBalanceError,
    MarketNotActiveError,
    ExchangePausedError,
    InvalidOutcomeError,
    TooManyMakersError,
    OrdersDoNotCrossError,
)

# Utils
from .utils import (
    keccak256,
    derive_condition_id,
    get_associated_token_address,
    get_associated_token_address_2022,
    orders_cross,
    encode_u8,
    encode_u16,
    encode_u32,
    encode_u64,
    encode_i64,
    decode_u8,
    decode_u16,
    decode_u32,
    decode_u64,
    decode_i64,
    decode_pubkey,
    decode_bool,
)

# Account deserialization
from .accounts import (
    deserialize_exchange,
    deserialize_market,
    deserialize_order_status,
    deserialize_orderbook,
    deserialize_position,
    deserialize_user_nonce,
)

# Client
from .client import LightconePinocchioClient

# Instruction builders
from .instructions import (
    build_activate_market_instruction,
    build_add_deposit_mint_instruction,
    build_cancel_order_instruction,
    build_create_market_instruction,
    build_create_market_instruction_with_id,
    build_create_orderbook_instruction,
    build_increment_nonce_instruction,
    build_initialize_instruction,
    build_match_orders_multi_instruction,
    build_merge_complete_set_instruction,
    build_mint_complete_set_instruction,
    build_redeem_winnings_instruction,
    build_set_authority_instruction,
    build_set_operator_instruction,
    build_set_paused_instruction,
    build_settle_market_instruction,
    build_withdraw_from_position_instruction,
)

# Order functions
from .orders import (
    create_ask_order,
    create_bid_order,
    create_signed_ask_order,
    create_signed_bid_order,
    deserialize_order,
    deserialize_compact_order,
    deserialize_full_order,
    hash_order,
    hash_order_hex,
    is_signed,
    serialize_order,
    serialize_compact_order,
    serialize_full_order,
    sign_order,
    signature_hex,
    to_order,
    to_compact_order,
    to_submit_request,
    validate_order,
    validate_signed_order,
    verify_order_signature,
)

# PDA functions
from .pda import (
    get_all_conditional_mints,
    get_alt_pda,
    get_conditional_mint_pda,
    get_exchange_pda,
    get_market_pda,
    get_mint_authority_pda,
    get_order_status_pda,
    get_orderbook_pda,
    get_position_pda,
    get_user_nonce_pda,
    get_vault_pda,
)

__all__ = [
    # Types
    "MarketStatus",
    "OrderSide",
    "Exchange",
    "Market",
    "Position",
    "OrderStatus",
    "UserNonce",
    "Orderbook",
    "FullOrder",
    "Order",
    "CompactOrder",
    "OutcomeMetadata",
    "MakerFill",
    "InitializeParams",
    "CreateMarketParams",
    "AddDepositMintParams",
    "MintCompleteSetParams",
    "MergeCompleteSetParams",
    "SettleMarketParams",
    "RedeemWinningsParams",
    "WithdrawFromPositionParams",
    "ActivateMarketParams",
    "MatchOrdersMultiParams",
    "CreateOrderbookParams",
    "SetAuthorityParams",
    "BidOrderParams",
    "AskOrderParams",
    "BuildResult",
    # Constants
    "PROGRAM_ID",
    "ALT_PROGRAM_ID",
    "TOKEN_PROGRAM_ID",
    "TOKEN_2022_PROGRAM_ID",
    "ASSOCIATED_TOKEN_PROGRAM_ID",
    "SYSTEM_PROGRAM_ID",
    "RENT_SYSVAR_ID",
    "INSTRUCTIONS_SYSVAR_ID",
    "ORDERBOOK_DISCRIMINATOR",
    "ORDERBOOK_SEED",
    "ORDERBOOK_SIZE",
    "SIGNED_ORDER_SIZE",
    "ORDER_SIZE",
    "MAX_OUTCOMES",
    "MIN_OUTCOMES",
    "MAX_MAKERS",
    "FULL_ORDER_SIZE",
    "COMPACT_ORDER_SIZE",
    "SIGNATURE_SIZE",
    "ORDER_HASH_SIZE",
    # Errors
    "LightconeError",
    "InvalidDiscriminatorError",
    "AccountNotFoundError",
    "InvalidAccountDataError",
    "InvalidOrderError",
    "InvalidSignatureError",
    "OrderExpiredError",
    "InsufficientBalanceError",
    "MarketNotActiveError",
    "ExchangePausedError",
    "InvalidOutcomeError",
    "TooManyMakersError",
    "OrdersDoNotCrossError",
    # Utils
    "keccak256",
    "derive_condition_id",
    "get_associated_token_address",
    "get_associated_token_address_2022",
    "orders_cross",
    # Client
    "LightconePinocchioClient",
    # Account Deserialization
    "deserialize_exchange",
    "deserialize_market",
    "deserialize_position",
    "deserialize_order_status",
    "deserialize_orderbook",
    "deserialize_user_nonce",
    # PDA Functions
    "get_exchange_pda",
    "get_market_pda",
    "get_vault_pda",
    "get_mint_authority_pda",
    "get_conditional_mint_pda",
    "get_order_status_pda",
    "get_user_nonce_pda",
    "get_position_pda",
    "get_orderbook_pda",
    "get_alt_pda",
    "get_all_conditional_mints",
    # Order Functions
    "create_bid_order",
    "create_ask_order",
    "create_signed_bid_order",
    "create_signed_ask_order",
    "hash_order",
    "hash_order_hex",
    "sign_order",
    "verify_order_signature",
    "serialize_full_order",
    "deserialize_full_order",
    "serialize_order",
    "serialize_compact_order",
    "deserialize_order",
    "deserialize_compact_order",
    "to_order",
    "to_compact_order",
    "to_submit_request",
    "is_signed",
    "signature_hex",
    "validate_order",
    "validate_signed_order",
    # Instruction Builders
    "build_initialize_instruction",
    "build_create_market_instruction",
    "build_create_market_instruction_with_id",
    "build_add_deposit_mint_instruction",
    "build_mint_complete_set_instruction",
    "build_merge_complete_set_instruction",
    "build_cancel_order_instruction",
    "build_increment_nonce_instruction",
    "build_settle_market_instruction",
    "build_redeem_winnings_instruction",
    "build_set_paused_instruction",
    "build_set_operator_instruction",
    "build_withdraw_from_position_instruction",
    "build_activate_market_instruction",
    "build_match_orders_multi_instruction",
    "build_create_orderbook_instruction",
    "build_set_authority_instruction",
]
