// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Order__Raw from "../order/Order__Raw.res.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

function make() {
  return {};
}

function get(index, marketPubkey) {
  return index[marketPubkey];
}

function insert(index, marketPubkey, entry) {
  index[marketPubkey] = entry;
}

let remove = Stdlib_Dict.$$delete;

function extend(index, other) {
  Object.entries(other).forEach(param => {
    let marketPubkey = param[0];
    let existing = index[marketPubkey];
    let target;
    if (existing !== undefined) {
      target = existing;
    } else {
      let created = {};
      index[marketPubkey] = created;
      target = created;
    }
    Object.entries(param[1]).forEach(param => {
      target[param[0]] = param[1];
    });
  });
}

function marketPubkeys(index) {
  return Object.keys(index).toSorted(Primitive_string.compare);
}

function fromMarketBalance(marketBalance) {
  let marketEntry = {};
  marketBalance.depositAssets.forEach(depositAssetBalance => {
    let outcomes = {};
    depositAssetBalance.outcomes.forEach(outcome => {
      if (!Order__Raw.UserOutcomeBalance.isZero(outcome)) {
        outcomes[outcome.conditionalToken] = outcome;
        return;
      }
    });
    if (Object.keys(outcomes).length !== 0) {
      marketEntry[depositAssetBalance.depositAsset] = outcomes;
      return;
    }
  });
  let match = Object.keys(marketEntry).length;
  if (match === 0) {
    return;
  }
  let index = {};
  index[marketBalance.marketPubkey] = marketEntry;
  return index;
}

function fromMarketBalances(marketBalances) {
  let index = {};
  marketBalances.forEach(marketBalance => {
    let marketIndex = fromMarketBalance(marketBalance);
    if (marketIndex !== undefined) {
      return extend(index, marketIndex);
    }
  });
  return index;
}

export {
  make,
  get,
  insert,
  remove,
  extend,
  marketPubkeys,
  fromMarketBalance,
  fromMarketBalances,
}
/* Order__Raw Not a pure module */
