// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "@mununki/ppx-spice/src/rescript/Spice.res.mjs";
import * as Shared from "../../Shared.res.mjs";
import DecimalJs from "decimal.js";
import * as Fmt__Decimal from "../../fmt/Fmt__Decimal.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let Outcome = {};

let WalletHolding = {};

let Portfolio = {};

function t_encode(v) {
  let extra = v.description;
  return Object.fromEntries(Spice.filterOptional([
    [
      "symbol",
      Spice.stringToJson(v.symbol)
    ],
    [
      "short_symbol",
      Spice.stringToJson(v.shortSymbol)
    ],
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "deposit_asset",
      Shared.pubkeyStr_encodeJson(v.depositAsset)
    ],
    [
      "icon_url_low",
      Spice.stringToJson(v.iconUrlLow)
    ],
    [
      "icon_url_medium",
      Spice.stringToJson(v.iconUrlMedium)
    ],
    [
      "icon_url_high",
      Spice.stringToJson(v.iconUrlHigh)
    ],
    [
      "description",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "decimals",
      Spice.floatToJson(v.decimals)
    ]
  ]));
}

function t_encodeJson(v) {
  let extra = v.description;
  return Object.fromEntries(Spice.filterOptional([
    [
      "symbol",
      Spice.stringToJson(v.symbol)
    ],
    [
      "short_symbol",
      Spice.stringToJson(v.shortSymbol)
    ],
    [
      "name",
      Spice.stringToJson(v.name)
    ],
    [
      "deposit_asset",
      Shared.pubkeyStr_encodeJson(v.depositAsset)
    ],
    [
      "icon_url_low",
      Spice.stringToJson(v.iconUrlLow)
    ],
    [
      "icon_url_medium",
      Spice.stringToJson(v.iconUrlMedium)
    ],
    [
      "icon_url_high",
      Spice.stringToJson(v.iconUrlHigh)
    ],
    [
      "description",
      Spice.optionToJson(Spice.stringToJson, extra)
    ],
    [
      "decimals",
      Spice.floatToJson(v.decimals)
    ]
  ]));
}

function t_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let symbol = Stdlib_Option.getOr(Stdlib_Option.map(v["symbol"], Spice.stringFromJson), Spice.error(undefined, "symbol" + " missing", v));
  if (symbol.TAG === "Ok") {
    let shortSymbol = Stdlib_Option.getOr(Stdlib_Option.map(v["short_symbol"], Spice.stringFromJson), Spice.error(undefined, "short_symbol" + " missing", v));
    if (shortSymbol.TAG === "Ok") {
      let name = Stdlib_Option.getOr(Stdlib_Option.map(v["name"], Spice.stringFromJson), Spice.error(undefined, "name" + " missing", v));
      if (name.TAG === "Ok") {
        let depositAsset = Stdlib_Option.getOr(Stdlib_Option.map(v["deposit_asset"], Shared.pubkeyStr_decode), Spice.error(undefined, "deposit_asset" + " missing", v));
        if (depositAsset.TAG === "Ok") {
          let iconUrlLow = Stdlib_Option.getOr(Stdlib_Option.map(v["icon_url_low"], Spice.stringFromJson), Spice.error(undefined, "icon_url_low" + " missing", v));
          if (iconUrlLow.TAG === "Ok") {
            let iconUrlMedium = Stdlib_Option.getOr(Stdlib_Option.map(v["icon_url_medium"], Spice.stringFromJson), Spice.error(undefined, "icon_url_medium" + " missing", v));
            if (iconUrlMedium.TAG === "Ok") {
              let iconUrlHigh = Stdlib_Option.getOr(Stdlib_Option.map(v["icon_url_high"], Spice.stringFromJson), Spice.error(undefined, "icon_url_high" + " missing", v));
              if (iconUrlHigh.TAG === "Ok") {
                let description = Stdlib_Option.getOr(Stdlib_Option.map(v["description"], json => Stdlib_Result.map(Spice.stringFromJson(json), v => v)), {
                  TAG: "Ok",
                  _0: undefined
                });
                if (description.TAG === "Ok") {
                  let decimals = Stdlib_Option.getOr(Stdlib_Option.map(v["decimals"], Spice.floatFromJson), Spice.error(undefined, "decimals" + " missing", v));
                  if (decimals.TAG === "Ok") {
                    return {
                      TAG: "Ok",
                      _0: {
                        symbol: symbol._0,
                        shortSymbol: shortSymbol._0,
                        name: name._0,
                        depositAsset: depositAsset._0,
                        iconUrlLow: iconUrlLow._0,
                        iconUrlMedium: iconUrlMedium._0,
                        iconUrlHigh: iconUrlHigh._0,
                        description: description._0,
                        decimals: decimals._0
                      }
                    };
                  }
                  let e = decimals._0;
                  return Spice.error("." + ("decimals" + e.path), e.message, e.value);
                }
                let e$1 = description._0;
                return Spice.error("." + ("description" + e$1.path), e$1.message, e$1.value);
              }
              let e$2 = iconUrlHigh._0;
              return Spice.error("." + ("icon_url_high" + e$2.path), e$2.message, e$2.value);
            }
            let e$3 = iconUrlMedium._0;
            return Spice.error("." + ("icon_url_medium" + e$3.path), e$3.message, e$3.value);
          }
          let e$4 = iconUrlLow._0;
          return Spice.error("." + ("icon_url_low" + e$4.path), e$4.message, e$4.value);
        }
        let e$5 = depositAsset._0;
        return Spice.error("." + ("deposit_asset" + e$5.path), e$5.message, e$5.value);
      }
      let e$6 = name._0;
      return Spice.error("." + ("name" + e$6.path), e$6.message, e$6.value);
    }
    let e$7 = shortSymbol._0;
    return Spice.error("." + ("short_symbol" + e$7.path), e$7.message, e$7.value);
  }
  let e$8 = symbol._0;
  return Spice.error("." + ("symbol" + e$8.path), e$8.message, e$8.value);
}

let DepositAssetMetadata = {
  t_encode: t_encode,
  t_encodeJson: t_encodeJson,
  t_decode: t_decode
};

function decimalOrZero(value) {
  try {
    return new DecimalJs(value);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return new DecimalJs(0);
    }
    throw exn;
  }
}

function decimalIsPositive(value) {
  return decimalOrZero(value).gt(new DecimalJs(0));
}

function computedBase(balance, conditionalPrice) {
  let price = decimalOrZero(conditionalPrice);
  let size = decimalOrZero(balance.idle).plus(decimalOrZero(balance.onBook));
  return {
    value: Fmt__Decimal.display(size.times(price)),
    size: Fmt__Decimal.display(size),
    price: Fmt__Decimal.display(price)
  };
}

function computedQuote(balance) {
  return Fmt__Decimal.display(decimalOrZero(balance.idle).plus(decimalOrZero(balance.onBook)));
}

let TokenBalance = {
  computedBase: computedBase,
  computedQuote: computedQuote
};

function total(delta) {
  return decimalOrZero(delta.idle).plus(decimalOrZero(delta.onBook)).toString();
}

function isZero(delta) {
  return !(decimalIsPositive(delta.idle) || decimalIsPositive(delta.onBook));
}

function toTokenBalance(delta) {
  return {
    mint: delta.conditionalToken,
    idle: delta.idle,
    onBook: delta.onBook,
    tokenType: {
      TAG: "ConditionalToken",
      orderbookId: Stdlib_Option.getOr(delta.orderbookId, ""),
      marketPubkey: delta.marketPubkey,
      outcomeIndex: delta.outcomeIndex
    }
  };
}

function toUserOutcomeBalance(delta) {
  return {
    outcomeIndex: delta.outcomeIndex,
    conditionalToken: delta.conditionalToken,
    balance: total(delta),
    balanceIdle: delta.idle,
    balanceOnBook: delta.onBook
  };
}

let ConditionalBalanceDelta = {
  total: total,
  isZero: isZero,
  toTokenBalance: toTokenBalance,
  toUserOutcomeBalance: toUserOutcomeBalance
};

export {
  Outcome,
  WalletHolding,
  Portfolio,
  DepositAssetMetadata,
  TokenBalance,
  ConditionalBalanceDelta,
}
/* Shared Not a pure module */
