// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "../../Http.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Orderbook__Raw from "./Orderbook__Raw.res.mjs";
import * as Orderbook__Model from "./Orderbook__Model.res.mjs";

function optionalQuery(query, key, value) {
  Stdlib_Option.forEach(value, value => {
    query.push([
      key,
      value
    ]);
  });
}

async function get(client, orderbookId, depth, aggregationOpt, cookieHeader) {
  let aggregation = aggregationOpt !== undefined ? aggregationOpt : Orderbook__Model.Aggregation.full;
  let message = Orderbook__Model.Aggregation.validate(aggregation.nSigFigs, aggregation.mantissa);
  if (message.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        TAG: "Validation",
        _0: message._0
      }
    };
  }
  let validated = message._0;
  let query = [];
  optionalQuery(query, "depth", Stdlib_Option.map(depth, value => value.toString()));
  optionalQuery(query, "nSigFigs", Stdlib_Option.map(validated.nSigFigs, value => value.toString()));
  optionalQuery(query, "mantissa", Stdlib_Option.map(validated.mantissa, value => value.toString()));
  return await Http.get(client.http, `/api/orderbook/` + orderbookId, query, undefined, cookieHeader, Orderbook__Raw.DepthResponse.t_decode);
}

function getWithAggregation(client, orderbookId, aggregation, depth, cookieHeader) {
  return get(client, orderbookId, depth, aggregation, cookieHeader);
}

function getWithCookies(client, orderbookId, cookieHeader, depth, aggregationOpt) {
  let aggregation = aggregationOpt !== undefined ? aggregationOpt : Orderbook__Model.Aggregation.full;
  return get(client, orderbookId, depth, aggregation, cookieHeader);
}

export {
  get,
  getWithAggregation,
  getWithCookies,
}
/* Http Not a pure module */
