// Generated by ReScript, PLEASE EDIT WITH CARE

import DecimalJs from "decimal.js";
import * as SortedBtree from "../../../bindings/sorted-btree/SortedBtree.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function make(orderbookId) {
  return {
    orderbookId: orderbookId,
    seq: 0.0,
    bids: SortedBtree.make(undefined, (prim0, prim1) => prim0.cmp(prim1), undefined),
    asks: SortedBtree.make(undefined, (prim0, prim1) => prim0.cmp(prim1), undefined)
  };
}

function parseDecimal(value) {
  let decimal;
  try {
    decimal = new DecimalJs(value);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return;
    }
    throw exn;
  }
  return Primitive_option.some(decimal);
}

function rebuild(book, levels) {
  book.clear();
  levels.forEach(level => {
    let match = parseDecimal(level.price);
    let match$1 = parseDecimal(level.size);
    if (match === undefined) {
      return;
    }
    if (match$1 === undefined) {
      return;
    }
    let size = Primitive_option.valFromOption(match$1);
    if (!size.isZero()) {
      book.set(Primitive_option.valFromOption(match), size);
      return;
    }
  });
}

function apply(state, book) {
  if (book.resync) {
    return {
      TAG: "RefreshRequired",
      _0: "ServerResync"
    };
  } else {
    rebuild(state.bids, book.bids);
    rebuild(state.asks, book.asks);
    state.seq = book.seq;
    return "Applied";
  }
}

function bestBid(state) {
  return Stdlib_Option.map(state.bids.maxKey(), prim => prim.toString());
}

function bestAsk(state) {
  return Stdlib_Option.map(state.asks.minKey(), prim => prim.toString());
}

function midPrice(state) {
  let match = state.bids.maxKey();
  let match$1 = state.asks.minKey();
  if (match !== undefined && match$1 !== undefined) {
    return Primitive_option.valFromOption(match).plus(Primitive_option.valFromOption(match$1)).div(new DecimalJs(2)).toString();
  }
}

function spread(state) {
  let match = state.bids.maxKey();
  let match$1 = state.asks.minKey();
  if (match !== undefined && match$1 !== undefined) {
    return Primitive_option.valFromOption(match$1).minus(Primitive_option.valFromOption(match)).toString();
  }
}

function levelToStrings(param) {
  return [
    param[0].toString(),
    param[1].toString()
  ];
}

function bids(state) {
  return state.bids.toArray().toReversed().map(levelToStrings);
}

function asks(state) {
  return state.asks.toArray().map(levelToStrings);
}

function isEmpty(state) {
  if (state.bids.size === 0) {
    return state.asks.size === 0;
  } else {
    return false;
  }
}

function seq(state) {
  return state.seq;
}

function orderbookId(state) {
  return state.orderbookId;
}

function clear(state) {
  state.bids.clear();
  state.asks.clear();
  state.seq = 0.0;
}

export {
  make,
  apply,
  bestBid,
  bestAsk,
  midPrice,
  spread,
  bids,
  asks,
  isEmpty,
  seq,
  orderbookId,
  clear,
}
/* decimal.js Not a pure module */
