// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";
import * as Kit from "@solana/kit";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let u8Decoder = Kit.getU8Decoder();

let u16Decoder = Kit.getU16Decoder();

let u32Decoder = Kit.getU32Decoder();

let u64Decoder = Kit.getU64Decoder();

let addressDecoder = Kit.getAddressDecoder();

let base16Decoder = Kit.getBase16Decoder();

let bytesAt = (function (bytes, offset, length) {
  return bytes.subarray(offset, offset + length);
});

let byteLength = ((bytes) => bytes.length);

function u8At(bytes, offset) {
  return u8Decoder.decode(bytesAt(bytes, offset, 1));
}

function u16At(bytes, offset) {
  return u16Decoder.decode(bytesAt(bytes, offset, 2));
}

function u32At(bytes, offset) {
  return u32Decoder.decode(bytesAt(bytes, offset, 4));
}

function u64At(bytes, offset) {
  return u64Decoder.decode(bytesAt(bytes, offset, 8));
}

function boolAt(bytes, offset) {
  return u8At(bytes, offset) !== 0;
}

function i16At(bytes, offset) {
  let raw = u16At(bytes, offset);
  if (raw >= 32768) {
    return raw - 65536 | 0;
  } else {
    return raw;
  }
}

function addressAt(bytes, offset) {
  return addressDecoder.decode(bytesAt(bytes, offset, 32));
}

function hexAt(bytes, offset, length) {
  return base16Decoder.decode(bytesAt(bytes, offset, length));
}

let discriminatorMatches = (function (bytes, expected) {
  if (bytes.length < expected.length) return false;
  for (let i = 0; i < expected.length; i++) { if (bytes[i] !== expected[i]) return false; }
  return true;
});

function fromU8(value) {
  switch (value) {
    case 0 :
      return {
        TAG: "Ok",
        _0: "Pending"
      };
    case 1 :
      return {
        TAG: "Ok",
        _0: "Active"
      };
    case 2 :
      return {
        TAG: "Ok",
        _0: "Resolved"
      };
    case 3 :
      return {
        TAG: "Ok",
        _0: "Cancelled"
      };
    default:
      return {
        TAG: "Error",
        _0: {
          TAG: "Program",
          _0: `Invalid market status: ` + value.toString()
        }
      };
  }
}

function toString(status) {
  switch (status) {
    case "Pending" :
      return "Pending";
    case "Active" :
      return "Active";
    case "Resolved" :
      return "Resolved";
    case "Cancelled" :
      return "Cancelled";
  }
}

function fromU8$1(value) {
  switch (value) {
    case 0 :
      return {
        TAG: "Ok",
        _0: "None"
      };
    case 1 :
      return {
        TAG: "Ok",
        _0: "Authority"
      };
    case 2 :
      return {
        TAG: "Ok",
        _0: "Manager"
      };
    case 3 :
      return {
        TAG: "Ok",
        _0: "Operator"
      };
    default:
      return {
        TAG: "Error",
        _0: {
          TAG: "Program",
          _0: `Invalid pending role kind: ` + value.toString()
        }
      };
  }
}

function checkHeader(bytes, size, discriminator, name) {
  if (byteLength(bytes) < size) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Program",
        _0: name + `: invalid data length (expected ` + size.toString() + `, got ` + byteLength(bytes).toString() + `)`
      }
    };
  } else if (discriminatorMatches(bytes, discriminator)) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "Program",
        _0: name + `: invalid account discriminator`
      }
    };
  }
}

function guard(name, body) {
  try {
    return body();
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "Program",
          _0: name + `: decode failed (` + Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "decode error") + `)`
        }
      };
    }
    throw error;
  }
}

function decodeExchange(bytes) {
  return guard("Exchange", () => {
    let error = checkHeader(bytes, 216, Constants.Discriminator.exchange, "Exchange");
    if (error.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
    let error$1 = fromU8$1(u8At(bytes, 180));
    if (error$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          authority: addressAt(bytes, 8),
          operator: addressAt(bytes, 40),
          manager: addressAt(bytes, 72),
          marketCount: u64At(bytes, 104),
          paused: boolAt(bytes, 112),
          bump: u8At(bytes, 113),
          depositTokenCount: u16At(bytes, 114),
          feeReceiver: addressAt(bytes, 116),
          pendingRole: addressAt(bytes, 148),
          pendingRoleKind: error$1._0
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error$1._0
      };
    }
  });
}

function decodeMarket(bytes) {
  return guard("Market", () => {
    let error = checkHeader(bytes, 216, Constants.Discriminator.market, "Market");
    if (error.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
    let error$1 = fromU8(u8At(bytes, 17));
    if (error$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          marketId: u64At(bytes, 8),
          numOutcomes: u8At(bytes, 16),
          status: error$1._0,
          bump: u8At(bytes, 18),
          makerFeeBps: i16At(bytes, 20),
          takerFeeBps: i16At(bytes, 22),
          oracle: addressAt(bytes, 24),
          questionId: hexAt(bytes, 56, 32),
          conditionId: hexAt(bytes, 88, 32),
          payoutNumerators: [
            u32At(bytes, 120),
            u32At(bytes, 124),
            u32At(bytes, 128),
            u32At(bytes, 132),
            u32At(bytes, 136),
            u32At(bytes, 140)
          ].map(prim => prim),
          payoutDenominator: u32At(bytes, 144)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error$1._0
      };
    }
  });
}

function decodeOrderbook(bytes) {
  return guard("Orderbook", () => {
    let error = checkHeader(bytes, 144, Constants.Discriminator.orderbook, "Orderbook");
    if (error.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          market: addressAt(bytes, 8),
          mintA: addressAt(bytes, 40),
          mintB: addressAt(bytes, 72),
          lookupTable: addressAt(bytes, 104),
          baseIndex: u8At(bytes, 136),
          bump: u8At(bytes, 137)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
  });
}

function decodePosition(bytes) {
  return guard("Position", () => {
    let error = checkHeader(bytes, 80, Constants.Discriminator.position, "Position");
    if (error.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          owner: addressAt(bytes, 8),
          market: addressAt(bytes, 40),
          bump: u8At(bytes, 72)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
  });
}

function decodeUserNonce(bytes) {
  return guard("UserNonce", () => {
    let error = checkHeader(bytes, 16, Constants.Discriminator.userNonce, "UserNonce");
    if (error.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          nonce: u64At(bytes, 8)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
  });
}

function decodeOrderStatus(bytes) {
  return guard("OrderStatus", () => {
    let error = checkHeader(bytes, 32, Constants.Discriminator.orderStatus, "OrderStatus");
    if (error.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          remaining: u64At(bytes, 8),
          baseRemaining: u64At(bytes, 16),
          isCancelled: boolAt(bytes, 24)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
  });
}

function decodeGlobalDepositToken(bytes) {
  return guard("GlobalDepositToken", () => {
    let error = checkHeader(bytes, 47, Constants.Discriminator.globalDepositToken, "GlobalDepositToken");
    if (error.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          mint: addressAt(bytes, 8),
          bump: u8At(bytes, 40),
          index: u16At(bytes, 41),
          active: boolAt(bytes, 43)
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: error._0
      };
    }
  });
}

let MarketStatus = {
  toString: toString
};

let PendingRoleKind = {};

export {
  MarketStatus,
  PendingRoleKind,
  decodeExchange,
  decodeMarket,
  decodeOrderbook,
  decodePosition,
  decodeUserNonce,
  decodeOrderStatus,
  decodeGlobalDepositToken,
}
/* u8Decoder Not a pure module */
