// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Env from "../Env.res.mjs";
import * as Kit from "@solana/kit";
import * as Token from "@solana-program/token";

let altProgram = Kit.address("AddressLookupTab1e1111111111111111111111111");

let systemProgram = Kit.address("11111111111111111111111111111111");

let rentSysvar = Kit.address("SysvarRent111111111111111111111111111111111");

let mplTokenMetadataProgram = Kit.address("metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s");

let tokenProgram = Token.TOKEN_PROGRAM_ADDRESS;

let associatedTokenProgram = Token.ASSOCIATED_TOKEN_PROGRAM_ADDRESS;

function programIdFor(env) {
  return Kit.address(Env.programId(env));
}

let Instruction = {
  mintCompleteSet: 3,
  mergeCompleteSet: 4,
  cancelOrder: 5,
  incrementNonce: 6,
  redeemWinnings: 8,
  depositToGlobal: 17,
  globalToMarketDeposit: 18,
  initPositionTokens: 19,
  extendPositionTokens: 21,
  withdrawFromGlobal: 22
};

let exchange = [
  30,
  200,
  220,
  149,
  3,
  61,
  104,
  50
];

let market = [
  219,
  190,
  213,
  55,
  0,
  227,
  198,
  154
];

let orderStatus = [
  46,
  90,
  241,
  73,
  178,
  104,
  65,
  3
];

let userNonce = [
  235,
  133,
  1,
  243,
  18,
  135,
  88,
  224
];

let position = [
  170,
  188,
  143,
  228,
  122,
  64,
  247,
  208
];

let orderbook = [
  43,
  34,
  25,
  113,
  195,
  69,
  72,
  7
];

let globalDepositToken = [
  37,
  190,
  161,
  232,
  123,
  146,
  42,
  87
];

let Discriminator = {
  exchange: exchange,
  market: market,
  orderStatus: orderStatus,
  userNonce: userNonce,
  position: position,
  orderbook: orderbook,
  globalDepositToken: globalDepositToken
};

let signedOrderSize = 233;

let orderSize = 37;

let signatureSize = 64;

let maxOutcomes = 6;

let minOutcomes = 2;

export {
  altProgram,
  systemProgram,
  rentSysvar,
  mplTokenMetadataProgram,
  tokenProgram,
  associatedTokenProgram,
  programIdFor,
  Instruction,
  Discriminator,
  signedOrderSize,
  orderSize,
  signatureSize,
  maxOutcomes,
  minOutcomes,
}
/* altProgram Not a pure module */
