// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Shared from "../Shared.res.mjs";
import * as Constants from "./Constants.res.mjs";
import * as Kit from "@solana/kit";
import * as Primitive_bigint from "@rescript/runtime/lib/es6/Primitive_bigint.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as Sha3Js from "@noble/hashes/sha3.js";

let concatBytes = (function (parts) {
  let total = 0;
  for (const part of parts) total += part.length;
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) { out.set(part, offset); offset += part.length; }
  return out;
});

function signingMessage(order) {
  return concatBytes([
    Kit.getU64Encoder().encode(order.nonce),
    Kit.getU64Encoder().encode(order.salt),
    Kit.getAddressEncoder().encode(order.maker),
    Kit.getAddressEncoder().encode(order.market),
    Kit.getAddressEncoder().encode(order.baseMint),
    Kit.getAddressEncoder().encode(order.quoteMint),
    Kit.getU8Encoder().encode(order.side),
    Kit.getU64Encoder().encode(order.amountIn),
    Kit.getU64Encoder().encode(order.amountOut),
    Kit.getI64Encoder().encode(order.expiration)
  ]);
}

function hash(order) {
  return Sha3Js.keccak_256(signingMessage(order));
}

function hashHex(order) {
  return Kit.getBase16Decoder().decode(Sha3Js.keccak_256(signingMessage(order)));
}

async function sign(order, keypair) {
  let hexBytes = Kit.getUtf8Encoder().encode(hashHex(order));
  return await Kit.signBytes(keypair.privateKey, hexBytes);
}

function signatureHex(signature) {
  return Kit.getBase16Decoder().decode(signature);
}

function signatureBs58(signature) {
  return Kit.getBase58Decoder().decode(signature);
}

function newBid(nonce, salt, maker, market, baseMint, quoteMint, amountIn, amountOut, expirationOpt) {
  let expiration = expirationOpt !== undefined ? expirationOpt : 0n;
  return {
    nonce: nonce,
    salt: salt,
    maker: maker,
    market: market,
    baseMint: baseMint,
    quoteMint: quoteMint,
    side: 0,
    amountIn: amountIn,
    amountOut: amountOut,
    expiration: expiration
  };
}

function newAsk(nonce, salt, maker, market, baseMint, quoteMint, amountIn, amountOut, expirationOpt) {
  let expiration = expirationOpt !== undefined ? expirationOpt : 0n;
  return {
    nonce: nonce,
    salt: salt,
    maker: maker,
    market: market,
    baseMint: baseMint,
    quoteMint: quoteMint,
    side: 1,
    amountIn: amountIn,
    amountOut: amountOut,
    expiration: expiration
  };
}

function serialize(order, signature) {
  return concatBytes([
    signingMessage(order),
    signature
  ]);
}

let bytesAt = (function (bytes, offset, length) {
  return bytes.subarray(offset, offset + length);
});

let byteLength = ((bytes) => bytes.length);

function u64At(bytes, offset) {
  return Kit.getU64Decoder().decode(bytesAt(bytes, offset, 8));
}

function i64At(bytes, offset) {
  return Kit.getI64Decoder().decode(bytesAt(bytes, offset, 8));
}

function u8At(bytes, offset) {
  return Kit.getU8Decoder().decode(bytesAt(bytes, offset, 1));
}

function addressAt(bytes, offset) {
  return Kit.getAddressDecoder().decode(bytesAt(bytes, offset, 32));
}

function deserialize(bytes) {
  if (byteLength(bytes) < Constants.signedOrderSize) {
    return {
      TAG: "Error",
      _0: `invalid signed-order length (expected ` + Constants.signedOrderSize.toString() + `, got ` + byteLength(bytes).toString() + `)`
    };
  }
  let side = u8At(bytes, 144);
  if (side !== 0 && side !== 1) {
    return {
      TAG: "Error",
      _0: `invalid order side: ` + side.toString()
    };
  } else {
    return {
      TAG: "Ok",
      _0: [
        {
          nonce: u64At(bytes, 0),
          salt: u64At(bytes, 8),
          maker: addressAt(bytes, 16),
          market: addressAt(bytes, 48),
          baseMint: addressAt(bytes, 80),
          quoteMint: addressAt(bytes, 112),
          side: side,
          amountIn: u64At(bytes, 145),
          amountOut: u64At(bytes, 153),
          expiration: i64At(bytes, 161)
        },
        bytesAt(bytes, 169, 64)
      ]
    };
  }
}

let publicKeyFromBytes = ((bytes) =>
  crypto.subtle.importKey("raw", bytes, "Ed25519", true, ["verify"]));

async function verifySignature(order, signature) {
  let makerKey = await publicKeyFromBytes(Kit.getAddressEncoder().encode(order.maker));
  let hexBytes = Kit.getUtf8Encoder().encode(hashHex(order));
  return await Kit.verifySignature(makerKey, signature, hexBytes);
}

function signatureFromBs58(sigBs58) {
  let bytes;
  try {
    bytes = Kit.getBase58Encoder().encode(sigBs58);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: "invalid signature: not base58"
      };
    }
    throw exn;
  }
  if (byteLength(bytes) === 64) {
    return {
      TAG: "Ok",
      _0: bytes
    };
  } else {
    return {
      TAG: "Error",
      _0: "invalid signature: expected 64 bytes"
    };
  }
}

function deriveOrderbookId(order) {
  return Shared.deriveOrderbookId(order.baseMint, order.quoteMint);
}

function u32At(bytes, offset) {
  return Kit.getU32Decoder().decode(bytesAt(bytes, offset, 4));
}

function serialize$1(order) {
  return concatBytes([
    Kit.getU32Encoder().encode(order.nonce),
    Kit.getU64Encoder().encode(order.salt),
    Kit.getU8Encoder().encode(order.side),
    Kit.getU64Encoder().encode(order.amountIn),
    Kit.getU64Encoder().encode(order.amountOut),
    Kit.getI64Encoder().encode(order.expiration)
  ]);
}

function deserialize$1(bytes) {
  if (byteLength(bytes) < Constants.orderSize) {
    return {
      TAG: "Error",
      _0: `invalid order length (expected ` + Constants.orderSize.toString() + `, got ` + byteLength(bytes).toString() + `)`
    };
  }
  let side = u8At(bytes, 12);
  if (side !== 0 && side !== 1) {
    return {
      TAG: "Error",
      _0: `invalid order side: ` + side.toString()
    };
  } else {
    return {
      TAG: "Ok",
      _0: {
        nonce: u32At(bytes, 0),
        salt: u64At(bytes, 4),
        side: side,
        amountIn: u64At(bytes, 13),
        amountOut: u64At(bytes, 21),
        expiration: i64At(bytes, 29)
      }
    };
  }
}

function toOrder(order) {
  return {
    nonce: Number(Primitive_bigint.mod_(order.nonce, 4294967296n)) | 0,
    salt: order.salt,
    side: order.side,
    amountIn: order.amountIn,
    amountOut: order.amountOut,
    expiration: order.expiration
  };
}

function ofOrder(compact, maker, market, baseMint, quoteMint) {
  return {
    nonce: BigInt(compact.nonce),
    salt: compact.salt,
    maker: maker,
    market: market,
    baseMint: baseMint,
    quoteMint: quoteMint,
    side: compact.side,
    amountIn: compact.amountIn,
    amountOut: compact.amountOut,
    expiration: compact.expiration
  };
}

function isOrderExpired(order, currentTime) {
  if (order.expiration !== 0n) {
    return currentTime >= order.expiration;
  } else {
    return false;
  }
}

function ordersCanCross(buyOrder, sellOrder) {
  if (buyOrder.side !== 0 || sellOrder.side !== 1 || buyOrder.amountIn === 0n || buyOrder.amountOut === 0n || sellOrder.amountIn === 0n || sellOrder.amountOut === 0n) {
    return false;
  } else {
    return buyOrder.amountIn * sellOrder.amountIn >= buyOrder.amountOut * sellOrder.amountOut;
  }
}

function calculateTakerFill(makerOrder, makerFillAmount) {
  if (makerOrder.amountIn === 0n) {
    return {
      TAG: "Error",
      _0: "maker order has zero amount_in"
    };
  }
  let value = Primitive_bigint.div(makerFillAmount * makerOrder.amountOut, makerOrder.amountIn);
  if (value > 18446744073709551615n) {
    return {
      TAG: "Error",
      _0: "taker fill overflows u64"
    };
  } else {
    return {
      TAG: "Ok",
      _0: value
    };
  }
}

function deriveConditionId(oracle, questionId, numOutcomes) {
  return Sha3Js.keccak_256(concatBytes([
    Kit.getAddressEncoder().encode(oracle),
    questionId,
    Kit.getU8Encoder().encode(numOutcomes)
  ]));
}

let Compact = {
  serialize: serialize$1,
  deserialize: deserialize$1
};

export {
  concatBytes,
  signingMessage,
  hash,
  hashHex,
  sign,
  signatureHex,
  signatureBs58,
  newBid,
  newAsk,
  serialize,
  deserialize,
  verifySignature,
  signatureFromBs58,
  deriveOrderbookId,
  Compact,
  toOrder,
  ofOrder,
  isOrderExpired,
  ordersCanCross,
  calculateTakerFill,
  deriveConditionId,
}
/* Shared Not a pure module */
