// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";
import * as Kit from "@solana/kit";

let bytesLte = (function (a, b) {
  for (let i = 0; i < a.length; i++) { if (a[i] !== b[i]) return a[i] < b[i]; }
  return true;
});

function exchange(programId) {
  let seeds = [Kit.getUtf8Encoder().encode("central_state")];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function market(programId, marketId) {
  let seeds = [
    Kit.getUtf8Encoder().encode("market"),
    Kit.getU64Encoder().encode(marketId)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function userNonce(programId, user) {
  let seeds = [
    Kit.getUtf8Encoder().encode("user_nonce"),
    Kit.getAddressEncoder().encode(user)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function position(programId, owner, market) {
  let seeds = [
    Kit.getUtf8Encoder().encode("position"),
    Kit.getAddressEncoder().encode(owner),
    Kit.getAddressEncoder().encode(market)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function vault(programId, depositMint, market) {
  let seeds = [
    Kit.getUtf8Encoder().encode("market_deposit_token_account"),
    Kit.getAddressEncoder().encode(depositMint),
    Kit.getAddressEncoder().encode(market)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function mintAuthority(programId, market) {
  let seeds = [
    Kit.getUtf8Encoder().encode("market_mint_authority"),
    Kit.getAddressEncoder().encode(market)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function conditionalMint(programId, market, depositMint, outcomeIndex) {
  let seeds = [
    Kit.getUtf8Encoder().encode("conditional_mint"),
    Kit.getAddressEncoder().encode(market),
    Kit.getAddressEncoder().encode(depositMint),
    Kit.getU8Encoder().encode(outcomeIndex)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function condition(programId, conditionId) {
  let seeds = [
    Kit.getUtf8Encoder().encode("condition"),
    conditionId
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function orderStatus(programId, orderHash) {
  let seeds = [
    Kit.getUtf8Encoder().encode("order_status"),
    orderHash
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function globalDepositToken(programId, mint) {
  let seeds = [
    Kit.getUtf8Encoder().encode("global_deposit"),
    Kit.getAddressEncoder().encode(mint)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function userGlobalDeposit(programId, user, mint) {
  let seeds = [
    Kit.getUtf8Encoder().encode("global_deposit"),
    Kit.getAddressEncoder().encode(user),
    Kit.getAddressEncoder().encode(mint)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function orderbook(programId, mintA, mintB) {
  let bytesA = Kit.getAddressEncoder().encode(mintA);
  let bytesB = Kit.getAddressEncoder().encode(mintB);
  let match = bytesLte(bytesA, bytesB) ? [
      bytesA,
      bytesB
    ] : [
      bytesB,
      bytesA
    ];
  let seeds = [
    Kit.getUtf8Encoder().encode("orderbook"),
    match[0],
    match[1]
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: programId,
    seeds: seeds
  });
}

function mplMetadata(conditionalMint) {
  let seeds = [
    Kit.getUtf8Encoder().encode("metadata"),
    Kit.getAddressEncoder().encode(Constants.mplTokenMetadataProgram),
    Kit.getAddressEncoder().encode(conditionalMint)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: Constants.mplTokenMetadataProgram,
    seeds: seeds
  });
}

function alt(orderbook, recentSlot) {
  let seeds = [
    Kit.getAddressEncoder().encode(orderbook),
    Kit.getU64Encoder().encode(recentSlot)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: Constants.altProgram,
    seeds: seeds
  });
}

function positionAlt(position, recentSlot) {
  let seeds = [
    Kit.getAddressEncoder().encode(position),
    Kit.getU64Encoder().encode(recentSlot)
  ];
  return Kit.getProgramDerivedAddress({
    programAddress: Constants.altProgram,
    seeds: seeds
  });
}

export {
  exchange,
  market,
  userNonce,
  position,
  vault,
  mintAuthority,
  conditionalMint,
  condition,
  orderStatus,
  globalDepositToken,
  userGlobalDeposit,
  orderbook,
  mplMetadata,
  alt,
  positionAlt,
}
/* Constants Not a pure module */
