// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kit from "@solana/kit";
import * as Instructions from "./Instructions.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let blockhashLifetimeOfResponse = (function (response) {
  return response.value;
});

async function signAndSend(client, makeInstruction) {
  let match = client.signingStrategy;
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no native signer configured on the client; call Client.useNativeSigner first"
      }
    };
  }
  let signer = match.signer;
  let run = async () => {
    let instruction = await makeInstruction();
    let blockhashResponse = await client.rpc.getLatestBlockhash().send();
    let lifetime = blockhashLifetimeOfResponse(blockhashResponse);
    let message = Kit.setTransactionMessageLifetimeUsingBlockhash(lifetime, Kit.appendTransactionMessageInstruction(instruction, Kit.setTransactionMessageFeePayerSigner(signer, Kit.createTransactionMessage({
      version: 0
    }))));
    let signedTransaction = await Kit.signTransactionMessageWithSigners(message);
    let wire = Kit.getBase64EncodedWireTransaction(signedTransaction);
    return await client.rpc.sendTransaction(wire, {
      encoding: "base64"
    }).send();
  };
  let signature;
  try {
    signature = await run();
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "Other",
          _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "failed to sign and send transaction")
        }
      };
    }
    throw error;
  }
  return {
    TAG: "Ok",
    _0: signature
  };
}

function depositToGlobal(client, user, mint, amount) {
  return signAndSend(client, () => Instructions.depositToGlobal(client.programId, user, mint, amount));
}

function withdrawFromGlobal(client, user, mint, amount) {
  return signAndSend(client, () => Instructions.withdrawFromGlobal(client.programId, user, mint, amount));
}

function globalToMarketDeposit(client, user, market, mint, amount, numOutcomes) {
  return signAndSend(client, () => Instructions.globalToMarketDeposit(client.programId, user, market, mint, amount, numOutcomes));
}

function merge(client, user, market, mint, amount, numOutcomes) {
  return signAndSend(client, () => Instructions.mergeCompleteSet(client.programId, user, market, mint, amount, numOutcomes));
}

function redeemWinnings(client, user, market, mint, amount, outcomeIndex) {
  return signAndSend(client, () => Instructions.redeemWinnings(client.programId, user, market, mint, amount, outcomeIndex));
}

export {
  depositToGlobal,
  withdrawFromGlobal,
  globalToMarketDeposit,
  merge,
  redeemWinnings,
}
/* @solana/kit Not a pure module */
