// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Decimal from "../../bindings/decimal/Decimal.res.mjs";
import DecimalJs from "decimal.js";

let decimalToBigInt = ((decimal) => BigInt(decimal.toFixed(0)));

let isBigIntZero = ((value) => value === 0n);

let fitsU64 = ((value) => value >= 0n && value <= 18446744073709551615n);

function scalePriceSize(price, size, side, decimals) {
  let zero = new DecimalJs(0);
  let priceDecimal = new DecimalJs(price);
  let sizeDecimal = new DecimalJs(size);
  if (!priceDecimal.gt(zero)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "NonPositivePrice",
        _0: price
      }
    };
  }
  if (!sizeDecimal.gt(zero)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "NonPositiveSize",
        _0: size
      }
    };
  }
  let ten = new DecimalJs(10);
  let baseMultiplier = ten.pow(decimals.baseDecimals);
  let quoteMultiplier = ten.pow(decimals.quoteDecimals);
  let sizeTruncated = sizeDecimal.toDecimalPlaces(decimals.baseDecimals, Decimal.roundDown);
  let decimal = sizeTruncated.times(baseMultiplier);
  let baseLamports = decimal.toDecimalPlaces(0, Decimal.roundDown);
  let decimal$1 = priceDecimal.times(sizeTruncated).times(quoteMultiplier);
  let quoteLamports = decimal$1.toDecimalPlaces(0, Decimal.roundDown);
  let baseAmount = decimalToBigInt(baseLamports);
  let quoteAmount = decimalToBigInt(quoteLamports);
  if (fitsU64(baseAmount)) {
    if (fitsU64(quoteAmount)) {
      if (isBigIntZero(baseAmount) || isBigIntZero(quoteAmount)) {
        return {
          TAG: "Error",
          _0: "ZeroAmount"
        };
      } else if (side !== 0) {
        return {
          TAG: "Ok",
          _0: {
            amountIn: baseAmount,
            amountOut: quoteAmount
          }
        };
      } else {
        return {
          TAG: "Ok",
          _0: {
            amountIn: quoteAmount,
            amountOut: baseAmount
          }
        };
      }
    } else {
      return {
        TAG: "Error",
        _0: {
          TAG: "Overflow",
          _0: "quote_lamports does not fit in u64"
        }
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "Overflow",
        _0: "base_lamports does not fit in u64"
      }
    };
  }
}

function alignPriceToTick(price, decimals) {
  if (decimals.tickSize <= 1.0) {
    return price;
  }
  let priceDecimal = new DecimalJs(price);
  let quoteMultiplier = new DecimalJs(10).pow(decimals.quoteDecimals);
  let tick = new DecimalJs(decimals.tickSize);
  let decimal = priceDecimal.times(quoteMultiplier);
  let lamports = decimal.toDecimalPlaces(0, Decimal.roundDown);
  let decimal$1 = lamports.div(tick);
  let alignedLamports = decimal$1.toDecimalPlaces(0, Decimal.roundDown).times(tick);
  return alignedLamports.div(quoteMultiplier).toString();
}

export {
  scalePriceSize,
  alignPriceToTick,
}
/* decimal.js Not a pure module */
