// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kit from "@solana/kit";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let blockhashLifetimeOfResponse = (function (response) {
  return response.value;
});

async function fetchLifetime(client) {
  return blockhashLifetimeOfResponse(await client.rpc.getLatestBlockhash().send());
}

function broadcastBase64(client, wire) {
  return client.rpc.sendTransaction(wire, {
    encoding: "base64"
  }).send();
}

async function externalSignAndBroadcast(client, external_, unsigned) {
  let unsignedWire = Kit.getBase64EncodedWireTransaction(unsigned);
  let wireBytes = Kit.getBase64Encoder().encode(unsignedWire);
  let signedBytes = await external_.signTransaction(wireBytes);
  let signedWire = Kit.getBase64Decoder().decode(signedBytes);
  return await broadcastBase64(client, signedWire);
}

async function signAndSubmit(client, makeInstruction) {
  let match = client.signingStrategy;
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no signing strategy configured on the client; call Client.useNativeSigner or Client.useExternalSigner first"
      }
    };
  }
  if (match.TAG === "NativeSigner") {
    let signer = match.signer;
    let run = async () => {
      let instruction = await makeInstruction();
      let lifetime = await fetchLifetime(client);
      let message = Kit.setTransactionMessageLifetimeUsingBlockhash(lifetime, Kit.appendTransactionMessageInstruction(instruction, Kit.setTransactionMessageFeePayerSigner(signer, Kit.createTransactionMessage({
        version: 0
      }))));
      let signedTransaction = await Kit.signTransactionMessageWithSigners(message);
      return await broadcastBase64(client, Kit.getBase64EncodedWireTransaction(signedTransaction));
    };
    let signature;
    try {
      signature = await run();
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === "JsExn") {
        return {
          TAG: "Error",
          _0: {
            TAG: "Other",
            _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "failed to sign and send transaction")
          }
        };
      }
      throw error;
    }
    return {
      TAG: "Ok",
      _0: signature
    };
  }
  let external_ = match._0;
  let run$1 = async () => {
    let instruction = await makeInstruction();
    let lifetime = await fetchLifetime(client);
    let __x = Kit.createTransactionMessage({
      version: 0
    });
    let unsigned = Kit.compileTransaction(Kit.setTransactionMessageLifetimeUsingBlockhash(lifetime, Kit.appendTransactionMessageInstruction(instruction, Kit.setTransactionMessageFeePayer(external_.address, __x))));
    return await externalSignAndBroadcast(client, external_, unsigned);
  };
  let signature$1;
  try {
    signature$1 = await run$1();
  } catch (raw_error$1) {
    let error$1 = Primitive_exceptions.internalToException(raw_error$1);
    if (error$1.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "Signing",
          _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error$1._1), "external signer failed to sign transaction")
        }
      };
    }
    throw error$1;
  }
  return {
    TAG: "Ok",
    _0: signature$1
  };
}

async function signAndSubmitMessage(client, message) {
  let match = client.signingStrategy;
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "Signing",
        _0: "no signing strategy configured on the client; call Client.useNativeSigner or Client.useExternalSigner first"
      }
    };
  }
  if (match.TAG === "NativeSigner") {
    let keypair = match.keypair;
    let run = async () => {
      let lifetime = await fetchLifetime(client);
      let unsigned = Kit.compileTransaction(Kit.setTransactionMessageLifetimeUsingBlockhash(lifetime, message));
      let signedTransaction = await Kit.signTransaction([keypair], unsigned);
      return await broadcastBase64(client, Kit.getBase64EncodedWireTransaction(signedTransaction));
    };
    let signature;
    try {
      signature = await run();
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === "JsExn") {
        return {
          TAG: "Error",
          _0: {
            TAG: "Other",
            _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error._1), "failed to sign and send transaction")
          }
        };
      }
      throw error;
    }
    return {
      TAG: "Ok",
      _0: signature
    };
  }
  let external_ = match._0;
  let run$1 = async () => {
    let lifetime = await fetchLifetime(client);
    let unsigned = Kit.compileTransaction(Kit.setTransactionMessageLifetimeUsingBlockhash(lifetime, message));
    return await externalSignAndBroadcast(client, external_, unsigned);
  };
  let signature$1;
  try {
    signature$1 = await run$1();
  } catch (raw_error$1) {
    let error$1 = Primitive_exceptions.internalToException(raw_error$1);
    if (error$1.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "Signing",
          _0: Stdlib_Option.getOr(Stdlib_JsExn.message(error$1._1), "external signer failed to sign transaction")
        }
      };
    }
    throw error$1;
  }
  return {
    TAG: "Ok",
    _0: signature$1
  };
}

export {
  signAndSubmit,
  signAndSubmitMessage,
}
/* @solana/kit Not a pure module */
