// Generated by ReScript, PLEASE EDIT WITH CARE


function shorten(value, qty) {
  let length = value.length;
  if (length <= qty) {
    return value;
  }
  let charsToShow = qty / 2 | 0;
  let head = value.slice(0, charsToShow);
  let tail = value.slice(length - charsToShow | 0, length);
  return head + `...` + tail;
}

export {
  shorten,
}
/* No side effect */
