// Generated by ReScript, PLEASE EDIT WITH CARE


function displayDecimalsBy(gteThreshold) {
  if (gteThreshold("10000")) {
    return 0;
  } else if (gteThreshold("1000")) {
    return 1;
  } else if (gteThreshold("100")) {
    return 2;
  } else if (gteThreshold("10")) {
    return 3;
  } else if (gteThreshold("0.1")) {
    return 4;
  } else {
    return 5;
  }
}

export {
  displayDecimalsBy,
}
/* No side effect */
