// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_BigInt from "@rescript/runtime/lib/es6/Stdlib_BigInt.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Fmt__Constants from "./Fmt__Constants.res.mjs";

function displayFormattedString(formatted) {
  let match = formatted.split(".");
  let match$1;
  if (match.length !== 2) {
    match$1 = [
      formatted,
      undefined
    ];
  } else {
    let integer = match[0];
    let fraction = match[1];
    match$1 = [
      integer,
      fraction
    ];
  }
  let fraction$1 = match$1[1];
  let integer$1 = match$1[0];
  let match$2 = integer$1.startsWith("-") ? [
      "-",
      integer$1.slice(1)
    ] : [
      "",
      integer$1
    ];
  let digits = match$2[1];
  let sign = match$2[0];
  let grouped = [];
  let length = digits.length;
  for (let index = 0; index < length; ++index) {
    if (index > 0 && (length - index | 0) % 3 === 0) {
      grouped.push(",");
    }
    grouped.push(digits.slice(index, index + 1 | 0));
  }
  let integerPart = grouped.join("");
  if (fraction$1 !== undefined) {
    return sign + integerPart + `.` + fraction$1;
  } else {
    return sign + integerPart;
  }
}

function isFormattedZero(formatted) {
  return formatted.split("").every(char => {
    if (char === "0" || char === ".") {
      return true;
    } else {
      return char === "-";
    }
  });
}

function displayDefaultFormattedString(formatted) {
  if (isFormattedZero(formatted)) {
    return "0";
  } else {
    return displayFormattedString(formatted);
  }
}

function displayDecimals(absValue) {
  return Fmt__Constants.displayDecimalsBy(threshold => absValue >= Stdlib_Option.getOr(Stdlib_Float.fromString(threshold), 0.0));
}

function display(amount) {
  return displayDefaultFormattedString(amount.toFixed(displayDecimals(Math.abs(amount))));
}

function displayWithDecimals(amount, decimals) {
  return displayFormattedString(amount.toFixed(decimals));
}

function displayPct(value, paddingOpt) {
  let padding = paddingOpt !== undefined ? paddingOpt : true;
  let truncated = Math.trunc(value * 100.0) / 100.0;
  if (padding) {
    return displayFormattedString(truncated.toFixed(2));
  }
  let formatted = truncated.toFixed(2);
  let tmp;
  if (formatted.includes(".")) {
    let noZeros = formatted.replace(/0+$/, "");
    tmp = noZeros.endsWith(".") ? noZeros.slice(0, -1) : noZeros;
  } else {
    tmp = formatted;
  }
  return displayFormattedString(tmp);
}

function toDecimalValue(value, decimals) {
  return Number(value) / Math.pow(10.0, decimals);
}

function fromDecimalValue(value, decimals) {
  let scaled = Math.trunc(value * Math.pow(10.0, decimals));
  return Stdlib_Option.getOr(Stdlib_BigInt.fromFloat(Math.max(scaled, 0.0)), 0n);
}

export {
  displayFormattedString,
  displayDefaultFormattedString,
  display,
  displayWithDecimals,
  displayPct,
  toDecimalValue,
  fromDecimalValue,
}
/* No side effect */
