// Generated by ReScript, PLEASE EDIT WITH CARE


import SortedBtreeDefault from "sorted-btree"
;

let makeWith = (function (entries, compare) {
    // Node: the default import is module.exports, so the class is at .default; Bun already
    // unwraps to the class (its .default is undefined), so fall back to the import itself.
    const BTree = SortedBtreeDefault.default || SortedBtreeDefault;
    return new BTree(entries, compare);
  });

function make(entries, compare, param) {
  return makeWith(entries, compare);
}

export {
  makeWith,
  make,
}
/*  Not a pure module */
