name: PR Check

on:
  pull_request:
    branches: [staging, prod]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test_examples:
    uses: ./.github/workflows/test-examples.yml
    with:
      lightcone-env: ${{ github.base_ref == 'prod' && 'prod' || 'staging' }}
    secrets: inherit

  publish:
    needs: [test_examples]
    uses: ./.github/workflows/publish.yml
    with:
      dry-run: true
    secrets: inherit
