name: Release

on:
  push:
    branches: [prod]
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      dry-run: false
    secrets: inherit
