// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as OrderbookState from "../src/domain/OrderbookState.res.mjs";

function level(side, price, size) {
  return {
    side: side,
    price: price,
    size: size
  };
}

function bookOf(bids, asks, seqOpt, resyncOpt, param) {
  let seq = seqOpt !== undefined ? seqOpt : 1.0;
  let resync = resyncOpt !== undefined ? resyncOpt : false;
  return {
    id: "ob_1",
    isSnapshot: true,
    seq: seq,
    resync: resync,
    bids: bids,
    asks: asks
  };
}

Buntest.describe("OrderbookState.apply", () => {
  Buntest.test("builds a book; best bid = max price, best ask = min price", () => {
    let state = OrderbookState.make("ob_1");
    let result = OrderbookState.apply(state, bookOf([
      {
        side: "bid",
        price: "100.5",
        size: "2"
      },
      {
        side: "bid",
        price: "100",
        size: "1"
      }
    ], [
      {
        side: "ask",
        price: "101",
        size: "3"
      },
      {
        side: "ask",
        price: "101.5",
        size: "1"
      }
    ], undefined, undefined, undefined));
    let applied;
    applied = typeof result !== "object";
    Buntest.expect(applied).toBe(true);
    Buntest.expect(OrderbookState.bestBid(state)).toBe("100.5");
    Buntest.expect(OrderbookState.bestAsk(state)).toBe("101");
    Buntest.expect(OrderbookState.bids(state).map(param => param[0])).toEqual([
      "100.5",
      "100"
    ]);
    Buntest.expect(OrderbookState.asks(state).map(param => param[0])).toEqual([
      "101",
      "101.5"
    ]);
  });
  Buntest.test("midPrice = (bid+ask)/2 and spread = ask−bid", () => {
    let state = OrderbookState.make("ob_1");
    OrderbookState.apply(state, bookOf([{
        side: "bid",
        price: "100.5",
        size: "1"
      }], [{
        side: "ask",
        price: "101",
        size: "1"
      }], undefined, undefined, undefined));
    Buntest.expect(OrderbookState.midPrice(state)).toBe("100.75");
    Buntest.expect(OrderbookState.spread(state)).toBe("0.5");
  });
  Buntest.test("zero-size levels are omitted", () => {
    let state = OrderbookState.make("ob_1");
    OrderbookState.apply(state, bookOf([
      {
        side: "bid",
        price: "100",
        size: "1"
      },
      {
        side: "bid",
        price: "99",
        size: "0"
      }
    ], [{
        side: "ask",
        price: "101",
        size: "1"
      }], undefined, undefined, undefined));
    Buntest.expect(OrderbookState.bids(state).length).toBe(1);
    Buntest.expect(OrderbookState.bestBid(state)).toBe("100");
  });
  Buntest.test("duplicate price within a frame: last size wins", () => {
    let state = OrderbookState.make("ob_1");
    OrderbookState.apply(state, bookOf([
      {
        side: "bid",
        price: "100",
        size: "1"
      },
      {
        side: "bid",
        price: "100",
        size: "5"
      }
    ], [{
        side: "ask",
        price: "101",
        size: "1"
      }], undefined, undefined, undefined));
    Buntest.expect(OrderbookState.bids(state).length).toBe(1);
    let match = OrderbookState.bids(state)[0];
    Buntest.expect(match[1]).toBe("5");
  });
  Buntest.test("a second snapshot replaces the book wholesale and updates seq", () => {
    let state = OrderbookState.make("ob_1");
    OrderbookState.apply(state, bookOf([{
        side: "bid",
        price: "100",
        size: "1"
      }], [{
        side: "ask",
        price: "101",
        size: "1"
      }], undefined, undefined, undefined));
    OrderbookState.apply(state, bookOf([{
        side: "bid",
        price: "200",
        size: "1"
      }], [{
        side: "ask",
        price: "201",
        size: "1"
      }], 7.0, undefined, undefined));
    Buntest.expect(OrderbookState.bestBid(state)).toBe("200");
    Buntest.expect(OrderbookState.bestAsk(state)).toBe("201");
    Buntest.expect(OrderbookState.seq(state)).toBe(7.0);
  });
  Buntest.test("resync frame returns RefreshRequired and leaves the book untouched", () => {
    let state = OrderbookState.make("ob_1");
    OrderbookState.apply(state, bookOf([{
        side: "bid",
        price: "100",
        size: "1"
      }], [{
        side: "ask",
        price: "101",
        size: "1"
      }], undefined, undefined, undefined));
    let result = OrderbookState.apply(state, bookOf([], [], undefined, true, undefined));
    let isRefresh;
    isRefresh = typeof result === "object";
    Buntest.expect(isRefresh).toBe(true);
    Buntest.expect(OrderbookState.bestBid(state)).toBe("100");
  });
  Buntest.test("empty book: best bid / mid / spread are None", () => {
    let state = OrderbookState.make("ob_1");
    Buntest.expect(OrderbookState.isEmpty(state)).toBe(true);
    Buntest.expect(OrderbookState.bestBid(state)).toBe(undefined);
    Buntest.expect(OrderbookState.midPrice(state)).toBe(undefined);
    Buntest.expect(OrderbookState.spread(state)).toBe(undefined);
  });
});

export {
  level,
  bookOf,
}
/*  Not a pure module */
