// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pda from "../src/program/Pda.res.mjs";
import * as Scaling from "../src/program/Scaling.res.mjs";
import * as Buntest from "bun:test";
import * as Kit from "@solana/kit";
import * as OrderPayload from "../src/program/OrderPayload.res.mjs";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

let byteLength = ((a) => a.length);

let byteAt = ((a, i) => a[i]);

function bigStr(value) {
  return value.toString();
}

let decimals66 = {
  baseDecimals: 6,
  quoteDecimals: 6,
  priceDecimals: 2,
  tickSize: 0.0
};

let decimals69 = {
  baseDecimals: 6,
  quoteDecimals: 9,
  priceDecimals: 2,
  tickSize: 0.0
};

Buntest.describe("Scaling", () => {
  Buntest.test("BID basic: 0.65 * 100 @ 6/6", () => {
    let match = Scaling.scalePriceSize("0.65", "100", 0, decimals66);
    if (match.TAG === "Ok") {
      let match$1 = match._0;
      Buntest.expect(match$1.amountIn.toString()).toBe("65000000");
      Buntest.expect(match$1.amountOut.toString()).toBe("100000000");
      return;
    }
    Buntest.expect("error").toBe("ok");
  });
  Buntest.test("ASK basic swaps amount_in/out", () => {
    let match = Scaling.scalePriceSize("0.65", "100", 1, decimals66);
    if (match.TAG === "Ok") {
      let match$1 = match._0;
      Buntest.expect(match$1.amountIn.toString()).toBe("100000000");
      Buntest.expect(match$1.amountOut.toString()).toBe("65000000");
      return;
    }
    Buntest.expect("error").toBe("ok");
  });
  Buntest.test("different decimals 6/9", () => {
    let match = Scaling.scalePriceSize("0.65", "100", 0, decimals69);
    if (match.TAG === "Ok") {
      let match$1 = match._0;
      Buntest.expect(match$1.amountIn.toString()).toBe("65000000000");
      Buntest.expect(match$1.amountOut.toString()).toBe("100000000");
      return;
    }
    Buntest.expect("error").toBe("ok");
  });
  Buntest.test("f64 noise in size is truncated", () => {
    let match = Scaling.scalePriceSize("1", "15.763000000000002", 0, decimals66);
    if (match.TAG === "Ok") {
      let match$1 = match._0;
      Buntest.expect(match$1.amountIn.toString()).toBe("15763000");
      Buntest.expect(match$1.amountOut.toString()).toBe("15763000");
      return;
    }
    Buntest.expect("error").toBe("ok");
  });
  Buntest.test("zero price rejected", () => {
    Buntest.expect(Stdlib_Result.isError(Scaling.scalePriceSize("0", "100", 0, decimals66))).toBe(true);
  });
  Buntest.test("sub-lamport size → ZeroAmount", () => {
    Buntest.expect(Stdlib_Result.isError(Scaling.scalePriceSize("1", "0.0000001", 0, decimals66))).toBe(true);
  });
});

Buntest.describe("OrderPayload", () => {
  Buntest.test("169-byte LE message + keccak digest + sign/verify roundtrip", async () => {
    let seed = (new Uint8Array(32).fill(3));
    let keypair = await Kit.createKeyPairFromPrivateKeyBytes(seed);
    let maker = await Kit.getAddressFromPublicKey(keypair.publicKey);
    let order = {
      nonce: 1n,
      salt: 0n,
      maker: maker,
      market: maker,
      baseMint: maker,
      quoteMint: maker,
      side: 0,
      amountIn: 65000000n,
      amountOut: 100000000n,
      expiration: 0n
    };
    let message = OrderPayload.signingMessage(order);
    Buntest.expect(byteLength(message)).toBe(169);
    Buntest.expect(byteAt(message, 0)).toBe(1);
    Buntest.expect(byteAt(message, 144)).toBe(0);
    let digest = OrderPayload.hash(order);
    Buntest.expect(byteLength(digest)).toBe(32);
    let signature = await OrderPayload.sign(order, keypair);
    Buntest.expect(byteLength(signature)).toBe(64);
    let hexBytes = Kit.getUtf8Encoder().encode(OrderPayload.hashHex(order));
    let verified = await Kit.verifySignature(keypair.publicKey, signature, hexBytes);
    Buntest.expect(verified).toBe(true);
  });
});

Buntest.describe("Pda", () => {
  Buntest.test("exchange derives; orderbook canonicalizes mint order", async () => {
    let programId = Kit.address("9cCFQnmWqWmZF3LNdAVWTh7ECGJK4tCVPtgPMcYum81A");
    let match = await Pda.exchange(programId);
    Buntest.expect(match[0].length > 30 && match[1] >= 0).toBe(true);
    let mintA = Kit.address("So11111111111111111111111111111111111111112");
    let mintB = Kit.address("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");
    let match$1 = await Pda.orderbook(programId, mintA, mintB);
    let match$2 = await Pda.orderbook(programId, mintB, mintA);
    Buntest.expect(match$1[0]).toBe(match$2[0]);
  });
});

export {
  byteLength,
  byteAt,
  bigStr,
  decimals66,
  decimals69,
}
/*  Not a pure module */
