// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as RpcFailover from "../src/RpcFailover.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

Buntest.describe("RpcFailover state machine", () => {
  Buntest.test("default state is primary with no flip timestamp", () => {
    let state = RpcFailover.make();
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("primary");
    Buntest.expect(Stdlib_Option.isNone(state.flippedToBackupAtMs)).toBe(true);
  });
  Buntest.test("flipTo Backup records a timestamp", () => {
    let state = RpcFailover.make();
    RpcFailover.flipTo(state, "backup");
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("backup");
    Buntest.expect(Stdlib_Option.isSome(state.flippedToBackupAtMs)).toBe(true);
  });
  Buntest.test("flipTo Primary clears the timestamp", () => {
    let state = RpcFailover.make();
    RpcFailover.flipTo(state, "backup");
    RpcFailover.flipTo(state, "primary");
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("primary");
    Buntest.expect(Stdlib_Option.isNone(state.flippedToBackupAtMs)).toBe(true);
  });
  Buntest.test("no recovery to primary before the cooldown elapses", () => {
    let state = RpcFailover.make();
    RpcFailover.flipTo(state, "backup");
    RpcFailover.maybeRecoverToPrimary(state);
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("backup");
  });
  Buntest.test("maybeRecover is a no-op when never flipped", () => {
    let state = RpcFailover.make();
    RpcFailover.maybeRecoverToPrimary(state);
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("primary");
  });
  Buntest.test("other flips the endpoint", () => {
    Buntest.expect(RpcFailover.toString(RpcFailover.other("primary"))).toBe("backup");
    Buntest.expect(RpcFailover.toString(RpcFailover.other("backup"))).toBe("primary");
  });
});

Buntest.describe("RpcFailover.withFailover", () => {
  Buntest.test("dead primary + live backup → Ok, and flips state to backup", async () => {
    let state = RpcFailover.make();
    let tryOn = async target => {
      if (target === "primary") {
        return {
          TAG: "Error",
          _0: {
            TAG: "Other",
            _0: "primary down"
          }
        };
      } else {
        return {
          TAG: "Ok",
          _0: "blockhash-from-backup"
        };
      }
    };
    let value = await RpcFailover.withFailover(state, true, tryOn);
    if (value.TAG === "Ok") {
      Buntest.expect(value._0).toBe("blockhash-from-backup");
    } else {
      Buntest.expect("unexpected error").toBe("ok");
    }
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("backup");
  });
  Buntest.test("live primary → Ok without flipping", async () => {
    let state = RpcFailover.make();
    let tryOn = async _target => ({
      TAG: "Ok",
      _0: "blockhash-from-primary"
    });
    let value = await RpcFailover.withFailover(state, true, tryOn);
    if (value.TAG === "Ok") {
      Buntest.expect(value._0).toBe("blockhash-from-primary");
    } else {
      Buntest.expect("unexpected error").toBe("ok");
    }
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("primary");
  });
  Buntest.test("no backup → surfaces the error and stays on primary", async () => {
    let state = RpcFailover.make();
    let tryOn = async _target => ({
      TAG: "Error",
      _0: {
        TAG: "Other",
        _0: "down"
      }
    });
    let result = await RpcFailover.withFailover(state, false, tryOn);
    let isError;
    isError = result.TAG !== "Ok";
    Buntest.expect(isError).toBe(true);
    Buntest.expect(RpcFailover.toString(RpcFailover.active(state))).toBe("primary");
  });
});

/*  Not a pure module */
