// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Market from "../src/domain/Market.res.mjs";
import * as Shared from "../src/Shared.res.mjs";
import * as Buntest from "bun:test";
import * as TradeState from "../src/domain/TradeState.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function trade(id, sequence) {
  return {
    orderbookId: "ob1",
    tradeId: id,
    timestamp: 1700000000000.0,
    price: "0.5",
    size: "1",
    side: "bid",
    sequence: sequence
  };
}

function ids(state) {
  return TradeState.trades(state).map(entry => entry.tradeId);
}

Buntest.describe("TradeState", () => {
  Buntest.test("WS trades insert newest-first by sequence, even out of order", () => {
    let state = TradeState.make("ob1", 5);
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "a",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 1.0
    });
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "c",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 3.0
    });
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "b",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 2.0
    });
    Buntest.expect(ids(state)).toEqual([
      "c",
      "b",
      "a"
    ]);
    Buntest.expect(Stdlib_Option.mapOr(TradeState.latest(state), "", entry => entry.tradeId)).toBe("c");
  });
  Buntest.test("REST trades (sequence 0) prepend and evict the oldest", () => {
    let state = TradeState.make("ob1", 2);
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "a",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 0.0
    });
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "b",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 0.0
    });
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "c",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 0.0
    });
    Buntest.expect(ids(state)).toEqual([
      "c",
      "b"
    ]);
  });
  Buntest.test("a full buffer drops trades older than everything retained", () => {
    let state = TradeState.make("ob1", 2);
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "b",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 2.0
    });
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "c",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 3.0
    });
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "a",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 1.0
    });
    Buntest.expect(ids(state)).toEqual([
      "c",
      "b"
    ]);
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "d",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 4.0
    });
    Buntest.expect(ids(state)).toEqual([
      "d",
      "c"
    ]);
  });
  Buntest.test("replace truncates to capacity; clear empties", () => {
    let state = TradeState.make("ob1", 2);
    TradeState.replace(state, [
      {
        orderbookId: "ob1",
        tradeId: "a",
        timestamp: 1700000000000.0,
        price: "0.5",
        size: "1",
        side: "bid",
        sequence: 3.0
      },
      {
        orderbookId: "ob1",
        tradeId: "b",
        timestamp: 1700000000000.0,
        price: "0.5",
        size: "1",
        side: "bid",
        sequence: 2.0
      },
      {
        orderbookId: "ob1",
        tradeId: "c",
        timestamp: 1700000000000.0,
        price: "0.5",
        size: "1",
        side: "bid",
        sequence: 1.0
      }
    ]);
    Buntest.expect(TradeState.size(state)).toBe(2);
    Buntest.expect(ids(state)).toEqual([
      "a",
      "b"
    ]);
    TradeState.clear(state);
    Buntest.expect(TradeState.isEmpty(state)).toBe(true);
  });
  Buntest.test("a zero-capacity history is disabled", () => {
    let state = TradeState.make("ob1", 0);
    TradeState.push(state, {
      orderbookId: "ob1",
      tradeId: "a",
      timestamp: 1700000000000.0,
      price: "0.5",
      size: "1",
      side: "bid",
      sequence: 1.0
    });
    Buntest.expect(TradeState.isEmpty(state)).toBe(true);
  });
});

Buntest.describe("Market token/pair helpers", () => {
  Buntest.test("stablecoin detection + currency symbol", () => {
    Buntest.expect(Market.isUsdStablecoin(Market.usdcMainnet)).toBe(true);
    Buntest.expect(Market.isUsdStablecoin(Market.usdtMainnet)).toBe(true);
    Buntest.expect(Market.isUsdStablecoin(Market.usdcDevnetLc)).toBe(true);
    Buntest.expect(Market.isUsdStablecoin("So11111111111111111111111111111111111111112")).toBe(false);
    Buntest.expect(Market.currencySymbol(Market.usdcMainnet)).toBe("$");
    Buntest.expect(Market.currencySymbol("So11111111111111111111111111111111111111112")).toBe("");
  });
  Buntest.test("sortByDisplayPriority: BTC/ETH/SOL groups first, then alphabetical", () => {
    let sorted = Market.sortByDisplayPriority([
      "ZZZ",
      "SOL",
      "AAA",
      "ETH",
      "WBTC",
      "BTC"
    ], symbol => symbol);
    Buntest.expect(sorted).toEqual([
      "BTC",
      "WBTC",
      "ETH",
      "SOL",
      "AAA",
      "ZZZ"
    ]);
  });
  Buntest.test("impact / impactPct", () => {
    let match = Market.impactPct("100", "110");
    Buntest.expect(match[0]).toBe(10.0);
    Buntest.expect(match[1]).toBe("+");
    let impact = Market.impact("100", "90");
    Buntest.expect(impact.sign).toBe("-");
    Buntest.expect(impact.isPositive).toBe(false);
    Buntest.expect(impact.pct).toBe(10.0);
    Buntest.expect(impact.dollar).toBe("10");
    let zero = Market.impact("0", "90");
    Buntest.expect(zero.pct).toBe(0.0);
    Buntest.expect(zero.sign).toBe("");
  });
});

Buntest.describe("Shared Side/Denominator helpers", () => {
  Buntest.test("applyImpactProtection pads in the fill direction", () => {
    Buntest.expect(Shared.Side.applyImpactProtection("bid", "100", "10")).toBe("110");
    Buntest.expect(Shared.Side.applyImpactProtection("ask", "100", "10")).toBe("90");
    Buntest.expect(Shared.Side.applyImpactProtection("bid", "0", "10")).toBe(undefined);
  });
  Buntest.test("Denominator.convertTo crosses at the price; identity needs no price", () => {
    Buntest.expect(Shared.Denominator.convertTo("Base", "Quote", "2", "0.5")).toBe("1");
    Buntest.expect(Shared.Denominator.convertTo("Quote", "Base", "1", "0.5")).toBe("2");
    Buntest.expect(Shared.Denominator.convertTo("Base", "Base", "7", "0")).toBe("7");
    Buntest.expect(Shared.Denominator.convertTo("Base", "Quote", "7", "0")).toBe(undefined);
  });
});

export {
  trade,
  ids,
}
/*  Not a pure module */
